#version 450
#extension GL_GOOGLE_include_directive : require

layout(local_size_x = 8, local_size_y = 8) in;
layout(set = 0, binding = 1) uniform sampler2DMS rawDepth;

float GTAOLoadRawDepth(ivec2 pixel)
{
    float depth = 1.0;
    for (int sampleIndex = 0; sampleIndex < textureSamples(rawDepth); ++sampleIndex)
        depth = min(depth, texelFetch(rawDepth, pixel, sampleIndex).r);
    return depth;
}

#include "GTAONormalsCommon.glsl"

void main() { GTAONormalsMain(); }
