//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by SimpleExport.rc
//
#define IDS_ACT1_DESC                   1
#define IDS_ACT1_NAME                   2
#define IDS_ACT2_DESC                   3
#define IDS_ACT2_NAME                   4
#define IDS_ACT3_NAME                   5
#define IDS_ACT4_NAME                   6
#define IDS_ACT5_NAME                   7
#define IDS_ACT6_NAME                   8
#define IDS_ACT7_NAME                   9
#define IDS_ACT8_DESC                   10
#define IDS_ACT8_NAME                   11
#define IDS_ACT9_DESC                   12
#define IDS_ACT9_NAME                   13
#define IDS_ACT10_NAME                  14
#define IDS_PLASMA_EXPORT               15
#define IDS_ACT11_NAME                  16
#define IDS_ACT11_DESC                  17
#define IDS_ACT12_NAME                  18
#define IDS_ACT12_DESC                  19
#define IDS_ACT_CAT                     30
#define IDD_COMP_PANEL                  103
#define IDD_SCENEVIEWER                 105
#define IDD_GET_LOCATION                106
#define IDD_COMP_MAIN                   107
#define IDD_AGE_DESC                    108
#define IDD_AGE_NAME                    109
#define IDD_UTILS_RES                   110
#define IDD_UTILS                       111
#define IDB_CURSOR_UP                   112
#define IDD_FIND_TEXTURE                112
#define IDB_CURSOR_DOWN                 113
#define IDD_EXPORT                      113
#define IDB_CURSOR_RIGHT                114
#define IDD_REF_BY                      114
#define IDB_CURSOR_LEFT                 115
#define IDB_CURSOR_OPEN                 116
#define IDB_CURSOR_GRAB                 117
#define IDB_CURSOR_CLICKED              118
#define IDB_CURSOR_POISED               119
#define IDR_COMP_MENU                   120
#define IDD_AGE_SEQNUM                  121
#define IDD_AGE_CHECKIN                 122
#define IDD_AGE_SAVEYESNO               123
#define IDC_COMPLIST                    1007
#define IDC_BACK                        1009
#define IDC_FORWARD                     1010
#define IDC_NUM_TARGS                   1011
#define IDC_TREE                        1014
#define IDC_ATTACH                      1015
#define IDC_UPDATE                      1017
#define IDC_SPINNER                     1019
#define IDC_EDIT                        1020
#define IDC_LIST_LOC                    1021
#define IDC_CAP_EDIT                    1021
#define IDC_CHECK_DEFAULT               1022
#define IDC_CAP_SPINNER                 1022
#define IDC_PROMPT                      1023
#define IDC_DIR                         1024
#define IDC_BROWSE_EXPORT               1025
#define IDC_COMMENT_TEXT                1026
#define IDC_COMMENTS                    1028
#define IDC_AGE_NEW                     1030
#define IDC_PAGE_NEW                    1032
#define IDC_PAGE_DEL                    1033
#define IDC_DATE                        1034
#define IDC_TIME                        1035
#define IDC_AGE_NAME                    1036
#define IDC_RESHADE                     1037
#define IDC_DAYLEN_EDIT                 1038
#define IDC_DAYLEN_SPINNER              1039
#define IDC_REG_TREE                    1040
#define IDC_SEQPREFIX_EDIT              1040
#define IDC_RES                         1041
#define IDC_SEQPREFIX_SPIN              1041
#define IDC_REFRESH                     1042
#define IDC_CLIENT_PATH                 1044
#define IDC_REUSE_DATA                  1045
#define IDC_EXPORT_PATH                 1045
#define IDC_EXE                         1046
#define IDC_START                       1047
#define IDC_PAGE_LIST                   1048
#define IDC_FIND_EDIT                   1049
#define IDC_UPDATE_BUTTON               1050
#define IDC_REPLACE_ALL_BUTTON          1052
#define IDC_TEXTURE_LIST                1053
#define IDC_SET_ALL_BUTTON              1054
#define IDC_REPLACE_BUTTON              1055
#define IDC_PRESHADE_CHECK              1056
#define IDC_PHYSICAL_CHECK              1057
#define IDC_EXPORT                      1058
#define IDC_LAST_EXPORT                 1059
#define IDC_PAGE_COMBO                  1060
#define IDC_LIGHTMAP_CHECK              1061
#define IDC_REF_BY_BUTTON               1062
#define IDC_UV_CHECK                    1062
#define IDC_REF_LIST                    1063
#define IDC_CLOSE                       1064
#define IDC_AGE_LIST                    1065
#define IDC_RSVDCHECK                   1066
#define IDC_EDITREG                     1067
#define IDC_AGEMSG                      1069
#define IDC_ADMMSG                      1070
#define IDC_INFOMSG                     1071
#define IDC_AGEDESC                     1071
#define IDC_RADIO_FILE                  1072
#define IDC_RADIO_DIR                   1073
#define IDC_AGE_CHECKOUT                1074
#define IDC_AGE_CHECKIN                 1075
#define IDC_AGE_UNDOCHECKOUT            1076
#define IDC_AGELIST_STATIC              1077
#define IDC_ADM_DONTLOAD                1078
#define IDC_ADM_LOADSDL                 1079
#define IDC_SIZE_COMBO                  1081
#define IDC_HIGH_SDL_CHECK              1082
#define IDC_BRANCHCOMBO                 1083
#define IDC_ADM_LOCAL_ONLY              1084
#define IDC_ADM_VOLATILE                1085
#define ID_REFRESH                      40002
#define ID_REMOVE_UNUSED                40003

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        123
#define _APS_NEXT_COMMAND_VALUE         40004
#define _APS_NEXT_CONTROL_VALUE         1086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
