# -*- coding: utf-8 -*-
""" *==LICENSE==*

CyanWorlds.com Engine - MMOG client, server and tools
Copyright (C) 2011  Cyan Worlds, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Additional permissions under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or
combining it with any of RAD Game Tools Bink SDK, Autodesk 3ds Max SDK,
NVIDIA PhysX SDK, Microsoft DirectX SDK, OpenSSL library, Independent
JPEG Group JPEG library, Microsoft Windows Media SDK, or Apple QuickTime SDK
(or a modified version of those libraries),
containing parts covered by the terms of the Bink SDK EULA, 3ds Max EULA,
PhysX SDK EULA, DirectX SDK EULA, OpenSSL and SSLeay licenses, IJG
JPEG Library README, Windows Media SDK EULA, or QuickTime SDK EULA, the
licensors of this Program grant you additional
permission to convey the resulting work. Corresponding Source for a
non-source form of such a combination shall include the source code for
the parts of OpenSSL and IJG JPEG Library used as well as that of the covered
work.

You can contact Cyan Worlds, Inc. by email legal@cyan.com
 or by snail mail at:
      Cyan Worlds, Inc.
      14617 N Newport Hwy
      Mead, WA   99021

 *==LICENSE==* """

# NOTE: This stub file was generated automatically from Plasma's Python interface.
# Do not edit this file manually.
# To change any of the docstrings or function signatures,
# edit the corresponding C++ glue code in pfPython.
# If the Python interface has changed, regenerate these stubs
# by running the following call in the in-game Python console:
# >>> __import__("generate_stubs").run()

from __future__ import annotations
from typing import *

class ptGameCli:
    """Abstract bass class for legacy game clients."""

    gameID: int
    """The ID of the game instance on the server."""

    handler: Any
    """The game event handler."""

    isLocallyOwned: bool
    """Whether or not we are the owner of this game instance."""

    ownerID: int
    """The ID of the player who owns this game instance."""

    def __init__(self):
        """None"""
        pass

    def leaveGame(self) -> None:
        """Explicitly ask the server to allow us to leave the game."""
        pass

class ptGmBlueSpiral(ptGameCli):
    """Legacy blue spiral game client."""

    gameID: int
    """The ID of the game instance on the server."""

    handler: Any
    """The game event handler."""

    isLocallyOwned: bool
    """Whether or not we are the owner of this game instance."""

    ownerID: int
    """The ID of the player who owns this game instance."""

    def __init__(self):
        """None"""
        pass

    def hitCloth(self):
        """Request for the server to hit a specific cloth index and validate the correct sequence of cloth inputs."""
        pass

    @staticmethod
    def isSupported():
        """Checks for the presence of a server-side blue spiral game manager."""
        pass

    @staticmethod
    def join():
        """Join a common blue spiral game in the current Age."""
        pass

    def leaveGame(self) -> None:
        """Explicitly ask the server to allow us to leave the game."""
        pass

    def startGame(self):
        """Request for the server to start the game timer."""
        pass

class ptGmMarker(ptGameCli):
    """Legacy marker game client."""

    gameID: int
    """The ID of the game instance on the server."""

    handler: Any
    """The game event handler."""

    isLocallyOwned: bool
    """Whether or not we are the owner of this game instance."""

    ownerID: int
    """The ID of the player who owns this game instance."""

    def __init__(self):
        """None"""
        pass

    def addMarker(self,x: float, y: float, z: float, name: str, age: str) -> None:
        """Request for the server to add a new marker to the game."""
        pass

    def captureMarker(self,markerId: int) -> None:
        """Request for the server to register a capture of the specified marker for our team."""
        pass

    def changeGameName(self,name: str) -> None:
        """Request for the server to change the internal marker game name."""
        pass

    def changeMarkerName(self,markerID: int) -> None:
        """Request for the server to change the name of a specific marker from the game."""
        pass

    def changeTimeLimit(self,timeLimit: int) -> None:
        """Request for the server to change the marker game's time limit."""
        pass

    @staticmethod
    def create(handler: Any, gameType: int, templateId: Optional[str]) -> None:
        """Initialize a new marker game client with the server."""
        pass

    def deleteGame(self) -> None:
        """Request for the server to delete all data associated with this game, including the marker definitions and game name."""
        pass

    def deleteMarker(self,markerID: int) -> None:
        """Request for the server to delete a specific marker from the game."""
        pass

    @staticmethod
    def isSupported() -> bool:
        """Checks for the presence of a server-side marker game manager."""
        pass

    def leaveGame(self) -> None:
        """Explicitly ask the server to allow us to leave the game."""
        pass

    def pauseGame(self) -> None:
        """Request for the server to pause the marker game."""
        pass

    def resetGame(self) -> None:
        """Request for the server to clear all markers to the uncaptured state."""
        pass

    def startGame(self) -> None:
        """Request for the server to start the marker game."""
        pass
