//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by plComponent.rc
//
#define IDS_COMP_ANIM                   31
#define IDS_PLASMA_ATTRIB               32
#define IDS_CHECK                       33
#define IDS_COMP_ACTIVE                 34
#define IDS_COMP_RESPOND                35
#define IDS_COMP_ALIASS                 36
#define IDS_COMP_STDPORTALS             37
#define IDS_COMP_TARGS                  38
#define IDS_COMP_INTERESTS              39
#define IDS_COMP_FOOTPRINT              40
#define IDS_COMP_AUTO                   41
#define IDS_COMP_VIEWFACES              42
#define IDS_COMP_SOUND3DS               43
#define IDS_COMP_BARNEYS                44
#define IDS_COMP_SOUNDGUI               45
#define IDS_COMP_CAMERAS                46
#define IDS_COMP_BLENDONTO              47
#define IDS_COMP_PHYS_CHOSEN_BASE       48
#define IDS_COMP_PHYS_CHOSEN_SIMP       49
#define IDS_COMP_PHYS_CHOSEN_TERRAIN    50
#define IDS_COMP_PHYS_CHOSEN_PLAYER     51
#define IDS_COMP_ROOMS                  52
#define IDS_COMP_CAMVIEWS               53
#define IDS_COMP_LODFADE_BASE           54
#define IDS_COMP_ANIM_AVATARS           55
#define IDS_COMP_SOUND_REVERBS          56
#define IDS_COMP_AVATARS                57
#define IDS_COMP_AVATAR_MODELS          58
#define IDS_COMP_AVATAR_PROXYS          59
#define IDS_COMP_LIGHTMAPS              60
#define IDS_COMP_IGNORES                61
#define IDS_COMP_FORCE_RTLIGHT          62
#define IDS_COMP_SOUNDMOD_CHORUSS       63
#define IDS_COMP_SOUNDMOD_COMPRESSORS   64
#define IDS_COMP_SOUNDMOD_DISTORTIONS   65
#define IDS_COMP_SOUNDMOD_ECHOS         66
#define IDS_COMP_SOUNDMOD_FLANGERS      67
#define IDS_COMP_SOUNDMOD_GARGLES       68
#define IDS_COMP_SOUNDMOD_REVERBS       69
#define IDS_COMP_SOUNDMOD_WETS          70
#define IDS_COMP_SOUNDMOD_DELAYMODS     71
#define IDS_COMP_SOUNDMOD_FEEDBACKS     72
#define IDS_COMP_SOUNDMOD_FREQ_OSC_CUTOFFS 73
#define IDS_COMP_SOUNDMOD_FEEDBACK_DELAYS 74
#define IDS_COMP_SOUNDMOD_GAINS         75
#define IDS_COMP_SOUNDMOD_ATTACKS       76
#define IDS_COMP_SOUNDMOD_RELEASES      77
#define IDS_COMP_SOUNDMOD_COMP_RATIOS   78
#define IDS_COMP_SOUNDMOD_ATTACK_PREDELAYS 79
#define IDS_COMP_SOUNDMOD_COMPTHRESHS   80
#define IDS_COMP_SOUNDMOD_INTENSITYS    81
#define IDS_COMP_SOUNDMOD_EFFECTCS      82
#define IDS_COMP_SOUNDMOD_EFFECTWS      83
#define IDS_COMP_SOUNDMOD_LOWFREQ_CUTOFFS 84
#define IDS_COMP_SOUNDMOD_LEFTFBDS      85
#define IDS_COMP_SOUNDMOD_RIGHTFBDS     86
#define IDS_COMP_SOUNDMOD_SWAPRLS       87
#define IDS_COMP_SOUNDMOD_FBDELAYFS     88
#define IDS_COMP_SOUNDMOD_MODRATES      89
#define IDS_COMP_SOUNDMOD_REVERBGAINS   90
#define IDS_COMP_SOUNDMOD_REVERBMIXS    91
#define IDS_COMP_SOUNDMOD_REVERBDELAYS  92
#define IDS_COMP_SOUNDMOD_GAINDS        93
#define IDS_COMP_OCCLUSIONS             94
#define IDS_COMP_OCCLUSION_PROXY        95
#define IDS_COMP_LODFADE                96
#define IDS_COMP_SOUNDMOD_BINDINGSS     97
#define IDS_COMP_PARTICLE_ROLL          98
#define IDS_COMP_CAMERACMD              99
#define IDS_COMP_PAGEINFOS              100
#define IDS_COMP_SOUNDBGND              101
#define IDS_COMP_SMOOTHS                102
#define IDS_COMP_LINEFOLLOWS            103
#define IDS_COMP_LINE_CHOSE_OBJECT      104
#define IDS_COMP_LINE_CHOSE_PATH        105
#define IDS_COMP_DETECTOR_CLICKABLE     106
#define IDS_COMP_CMD_PARAMS             107
#define IDS_COMP_RANDOMSOUNDS           108
#define IDS_COMP_DETECTOR_CLICK_DRAGGABLE 109
#define IDS_COMP_LIGHTINCS              110
#define IDS_COMP_LIGHTINC_CHOSE_LIGHT   111
#define IDS_COMP_PARTICLE_VOLUME_ROLL   112
#define IDS_COMP_PARTICLE_FADE_ROLL     113
#define IDS_COMP_FOLLOWS                114
#define IDS_COMP_INV_OBJECTS            115
#define IDS_COMP_SOFTVOLUMES            116
#define IDS_COMP_PYTHON                 117
#define IDS_COMP_SOUND_REVERB_PARAMS    118
#define IDS_COMP_DETECTOR_REGION        119
#define IDS_COMP_UNLEASH                120
#define IDS_COMP_DETECTOR_COLLISION     121
#define IDS_COMP_SOFTVOLUME_UNION       122
#define IDS_COMP_PHYS_WHEEL_CONSTRAINTS 123
#define IDS_COMP_PHYS_HINGE_CONSTRAINTS 124
#define IDS_COMP_PHYS_SS_CONSTRAINTS    125
#define IDS_COMP_SOFTVOLUME_ISECT       126
#define IDS_COMP_SOFTVOLUME_NEGATE      127
#define IDS_COMP_LIGHTREGION            128
#define IDS_COMP_GEO_DICE               129
#define IDS_COMP_ONESHOTS               130
#define IDS_COMP_WAIT                   131
#define IDS_COMP_SOUNDFADEPARAMS        132
#define IDS_COMP_SOUNDSOFTPARAMS        133
#define IDS_COMP_SOUNDSOFTSELECT        134
#define IDS_COMP_LOD_AVATARS            135
#define IDS_CAMERARGN                   136
#define IDS_COMP_PARTICLE_WIND          137
#define IDS_COMP_BLENDONTOADV           138
#define IDS_COMP_PARTICLE_UNIWIND       139
#define IDS_COMP_DISTFADE               140
#define IDS_COMP_SHADOW_CAST            141
#define IDS_COMP_GUIDIALOG              142
#define IDS_CAMERA_OCCLUDERS            143
#define IDS_COMP_SHADOW_RCV             144
#define IDS_COMP_AUTOCAM                145
#define IDS_COMP_GUIBUTTON              146
#define IDS_COMP_DISTRIBUTORS           147
#define IDS_COMP_GUIDRAGGABLE           148
#define IDS_COMP_CLUSTERS               149
#define IDS_COMP_XREGION                150
#define IDS_COMP_GUILISTBOX             151
#define IDS_COMP_GUITEXTBOX             152
#define IDS_COMP_ANIM_EASE              153
#define IDS_COMP_IGNORELITES            154
#define IDS_COMP_GUIEDITBOX             155
#define IDS_COMP_FLEXIBILITYS           156
#define IDS_COMP_GUITAG                 157
#define IDS_COMP_BLOWS                  158
#define IDS_COMP_CLUSTER_CHOSE_WINDBONE 159
#define IDS_COMP_PHYS_PUPPET_ROOT       160
#define IDS_COMP_GZ_FADE                160
#define IDS_COMP_ANIM_GROUPED           161
#define IDS_COMP_XFORMS                 162
#define IDS_COMP_BEHAVIOR_SITTINGS      163
#define IDS_COMP_GUIUDSCROLL            164
#define IDS_COMP_GUI_SELECTUDCTRL       165
#define IDS_COMP_GUI_SELECTSCROLL       166
#define IDS_COMP_PHYS_MEMBER            167
#define IDS_COMP_PHYS_BOUNCE            168
#define IDS_COMP_PHYS_REPORT            169
#define IDS_COMP_NAV_LADDERS            170
#define IDS_COMP_CLONE_INST             171
#define IDS_COMP_CLONE_TEMPLATE         172
#define IDS_COMP_GUIKNOB                173
#define IDS_PARTICLE_VELOCITY_MIN       174
#define IDS_PARTICLE_VELOCITY_MAX       175
#define IDS_PARTICLE_LIFE_MIN           176
#define IDS_PARTICLE_LIFE_MAX           177
#define IDS_PARTICLE_SCALE_MIN          178
#define IDS_PARTICLE_SCALE_MAX          179
#define IDS_PARTICLE_PPS                180
#define IDS_PARTICLE_CONE_ANGLE         181
#define IDS_COMP_GUIDRAGBAR             182
#define IDS_COMP_DIST_TEMPLATES         183
#define IDS_COMP_DIST_SPACING           184
#define IDS_COMP_DIST_ORIENT            185
#define IDS_COMP_DIST_ANGPROB           186
#define IDS_COMP_DIST_ALTPROB           187
#define IDS_COMP_DIST_CONFORM           188
#define IDS_COMP_DIST_BITMAP            189
#define IDS_COMP_DIST_FADE              190
#define IDS_COMP_DIST_WIND              191
#define IDS_COMP_DIST_RANDOMIZE         192
#define IDS_COMP_DIST_SCALE             193
#define IDS_COMP_GUICHECKBOX            194
#define IDS_COMP_GUI_SELECTANIM         195
#define IDS_COMP_DIST_ACTION            196
#define IDS_COMP_GUIRADIOGROUP          197
#define IDS_COMP_GUI_SELECTCHECK        198
#define IDS_COMP_GUIPROCROLLOUT         199
#define IDS_COMP_GUISCHEME              200
#define IDS_COMP_PHYS_DEBUG             201
#define IDS_COMP_PHYS_SIMPLE            202
#define IDS_COMP_PHYS_TERRAIN           203
#define IDS_COMP_PHYS_PROXY_TERRAIN     204
#define IDS_COMP_PHYS_INVISIBLE         205
#define IDS_COMP_PHYS_WALKABLE          206
#define IDS_COMP_GUI_SELECTMOUSEOVERANIM 207
#define IDS_COMP_PHYS_CLIMBABLE         208
#define IDS_COMP_PHYS_SWIMSURF          209
#define IDS_COMP_PHYS_SWIM3D            210
#define IDS_COMP_PHYS_PUPPET            211
#define IDS_COMP_DYNMAT                 211
#define IDS_COMP_PHYS_CRITTER           212
#define IDS_COMP_GUIDYNDISPLAY          213
#define IDS_COMP_CLOTHING               214
#define IDS_COMP_RAILCAMERA             215
#define IDS_COMP_CIRCLECAMERA           216
#define IDS_COMP_ALLOW_PAN              217
#define IDS_COMP_DETECTOR_ANIM          218
#define IDS_COMP_CAMERAZOOM             219
#define IDS_AVATARPOA                   220
#define IDS_COMP_CAMERATRANS            221
#define IDS_COMP_OBJECTPOA              222
#define IDS_COMP_FIRST_PERSONCAM        223
#define IDS_COMP_DETECTOR_MTL           224
#define IDS_COMP_VEHICLE                225
#define IDS_COMP_SHADOW_LIGHT           226
#define IDS_COMP_SOUNDSRC               227
#define IDS_COMP_RANDOMSOUNDS_GROUPS    228
#define IDS_COMP_FOOTSTEP_SOUND         229
#define IDS_COMP_EAXLISTENER            230
#define IDS_COMP_EAXBUFFER              231
#define IDS_SND_VOLUME                  232
#define IDS_COMP_FP_SOURCENODE          233
#define IDS_COMP_RIPPLE                 234
#define IDS_COMP_FP_DIRTY               235
#define IDS_COMP_FP_PRINTSHAPE          236
#define IDS_COMP_PUDDLE                 237
#define IDS_COMP_SUBWORLD_REGION        238
#define IDS_COMP_NPC_SPAWNER            239
#define IDS_COMP_FP_ACTIVEPRINTSHAPE    240
#define IDS_COMP_GUIMULTILINE           241
#define IDS_COMP_FP_WAKE                242
#define IDS_COMP_GUIPROXY               243
#define IDS_COMP_GUIPROXY_PROMPT        244
#define IDS_COMP_FILTER                 245
#define IDS_COMP_SOUNDBASE              246
#define IDS_COMP_STEREIZE               247
#define IDS_COMP_CLIMB_TRIGGER          248
#define IDS_COMP_CLIMB_BLOCKER          249
#define IDS_COMP_SWIVEL                 250
#define IDS_COMP_CHOOSE_OBJECT          251
#define IDS_COMP_MORPHLAY               252
#define IDS_COMP_MORPHSEQ               253
#define IDS_COMP_CHOSE_OBJECT           254
#define IDS_COMP_OBJECT_FOLLOWCAM       255
#define IDS_COMP_EMOTE                  256
#define IDS_COMP_WATER                  257
#define IDS_COMP_W_REFOBJECT            258
#define IDS_COMP_W_BASICWATER           259
#define IDS_COMP_W_ADVWATER             260
#define IDS_COMP_W_BASICSHORE           261
#define IDS_COMP_W_ADVSHORE             262
#define IDS_COMP_SHORE                  263
#define IDS_COMP_SHORE_CHOSE            264
#define IDS_COMP_GUIPROGRESS            265
#define IDS_COMP_W_ENVMAP               266
#define IDS_COMP_MAINTAINERS_MARKER     267
#define IDS_COMP_NOSHOW                 268
#define IDS_COMP_GUICLICKMAP            269
#define IDS_COMP_VISREGION              270
#define IDS_COMP_SMOOTHAV               271
#define IDS_COMP_GUISKIN                272
#define IDS_COMP_GUIMENUANCHOR          273
#define IDS_COMP_WDECAL                 274
#define IDS_COMP_ANIM_CAM_CMD           275
#define IDS_COMP_NETSYNC                276
#define IDS_COMP_RELREGION              277
#define IDS_COMP_REPRESENT              278
#define IDS_COMP_REPGROUP               279
#define IDS_COMP_PHYS_BRIDGE            280
#define IDS_COMP_SMOOTHBASE             281
#define IDS_COMP_SMOOTHSNAP             282
#define IDS_COMP_IMAGELIB               283
#define IDS_COMP_W_VTXHELP              284
#define IDS_COMP_PHYS_SUBWORLD          285
#define IDS_COMP_PARTICLE_FLOCK         286
#define IDS_COMP_EFFVISSET              287
#define IDS_COMP_ENVMAP                 288
#define IDS_COMP_W_GEOWATER             289
#define IDS_COMP_W_TEXWATER             290
#define IDS_COMP_SHOOTABLE              291
#define IDS_COMP_FP_BULLET              292
#define IDS_COMP_FP_TORPEDO             293
#define IDS_COMP_PANIC                  294
#define IDS_COMP_SOUNDPHYS              295
#define IDS_COMP_FORCE_CTT              296
#define IDS_COMP_MARKER                 297
#define IDS_COMP_LOSFADE                298
#define IDS_COMP_SORT_AS_OPAQUE         299
#define IDD_COMP_ROOM                   300
#define IDS_SWIM_DETECTOR_NODE          300
#define IDS_SWIM_CURRENT_NODE           301
#define IDD_COMP_PHYS_DETECTOR          302
#define IDS_COMP_OBJ_FLOCKER            302
#define IDD_COMP_ANIM                   303
#define IDS_COMP_GRASS_ROLL             303
#define IDS_COMP_ANIM_COMPRESS_ROLL     304
#define IDS_COMP_RIDE_ANIMATED_PHYS     305
#define IDD_COMP_ACTIVE                 306
#define IDD_COMP_RESPOND                307
#define IDD_COMP_ALIAS                  308
#define IDD_COMP_STDPORTAL              312
#define IDD_COMP_PLAYERSTART            313
#define IDD_COMP_TARGS                  314
#define IDD_COMP_INTEREST               315
#define IDD_COMP_AUTO                   316
#define IDD_COMP_PHYSICAL               317
#define IDD_COMP_SOUND3D                318
#define IDD_COMP_PHYS_TERRAIN           319
#define IDD_COMP_PHYS_PLAYER            320
#define IDD_COMP_CAMERA                 321
#define IDD_COMP_PHYS_SIMPLE            322
#define IDD_COMP_ANIM_AVATAR            325
#define IDD_COMP_SOUND_REVERB           326
#define IDD_COMP_AVATAR                 327
#define IDD_COMP_LIGHTMAP               328
#define IDD_COMP_IGNORE                 329
#define IDD_COMP_SOUNDMOD_COMPRESSOR    330
#define IDD_COMP_SOUNDMOD_DISTORT       331
#define IDD_COMP_SOUNDMOD_ECHO          332
#define IDD_COMP_SOUNDMOD_FLANGER       333
#define IDD_COMP_SOUNDMOD_GARGLE        334
#define IDD_COMP_SOUNDMOD_REVERB        335
#define IDD_COMP_SOUNDMOD_CHORUS        336
#define IDD_COMP_OCCLUSION              337
#define IDD_COMP_PHYS_PROXY_TERRAIN     338
#define IDD_COMP_SOUNDMOD_BIND          339
#define IDD_COMP_PARTICLE               340
#define IDD_COMP_CAMERACMD              341
#define IDD_COMP_PAGEINFO               342
#define IDD_COMP_PARTICLE_VOLUME        343
#define IDD_COMP_SMOOTH                 344
#define IDD_COMP_BARNEY                 345
#define IDD_COMP_LINEFOLLOW             346
#define IDD_COMP_RESPOND_ANIM           347
#define IDD_COMP_RESPOND_MTL            348
#define IDD_COMP_RESPOND_LINK           349
#define IDD_COMP_DETECTOR_CLICKABLE     350
#define IDD_COMP_RANDOMSOUND            352
#define IDD_COMP_DETECTOR_CLICK_DRAGGABLE 353
#define IDD_COMP_ONESHOT                354
#define IDD_COMP_PARTICLE_FADE          355
#define IDD_COMP_SOUNDBGND              356
#define IDD_COMP_FOLLOW                 357
#define IDD_COMP_LIGHTINC               358
#define IDD_COMP_INV_OBJECT             359
#define IDD_COMP_SOFTVOLUME             360
#define IDD_COMP_SOUND_REVERB_PARAMS    362
#define IDD_COMP_DETECTOR_REGION        363
#define IDD_COMP_DETECTOR_COLLISION     365
#define IDD_COMP_RESPOND_WAIT           367
#define IDD_COMP_PHYS_WHEEL_CONSTRAINT  368
#define IDD_COMP_PHYS_HINGE_CONSTRAINT  369
#define IDD_COMP_PHYS_SS_CONSTRAINT     370
#define IDD_COMP_LIGHTREGION            371
#define IDD_COMP_SOFTVOLUME_UNION       372
#define IDD_COMP_SOFTVOLUME_ISECT       373
#define IDD_COMP_SOFTVOLUME_NEGATE      374
#define IDD_COMP_PHYS_CRITTER           376
#define IDD_COMP_RESPOND_ANIMPICK       377
#define IDD_COMP_RESPOND_ENABLE         378
#define IDD_COMP_RESPOND_ONESHOT        379
#define IDD_COMP_SOUND_FADEPARAMS       380
#define IDD_COMP_SOUND_SOFTPARAMS       381
#define IDD_COMP_LOD_AVATAR             382
#define IDD_COMP_CAMERARGN              383
#define IDD_COMP_FIXEDCAM               384
#define IDD_COMP_AUTOCAM                385
#define IDD_COMP_CAMERA_TRANS           389
#define IDD_COMP_PHYS_CLIMBABLE         390
#define IDD_COMP_PHYS_SWIMSURF          391
#define IDD_COMP_PHYS_SWIM3D            392
#define IDD_COMP_PHYS_WALKABLE          393
#define IDD_COMP_PHYS_PUPPET            394
#define IDD_COMP_CAMERA_OCCLUDER        395
#define IDD_COMP_GUIDIALOG              396
#define IDD_COMP_PHYS_INVISIBLE         397
#define IDD_COMP_AVATAR_POA             398
#define IDD_COMP_OBJECT_POA             399
#define IDD_COMP_CAM_MAKEDEFAULT        400
#define IDD_COMP_PYTHON_FILE            401
#define IDD_COMP_LOS_WIDGET             402
#define IDD_COMP_GUIBUTTON              403
#define IDD_COMP_DISTRIBUTOR            404
#define IDD_COMP_GUIDRAGGABLE           405
#define IDD_COMP_CLUSTER                406
#define IDD_COMP_XREGION                407
#define IDD_COMP_GUILISTBOX             409
#define IDD_COMP_GUITEXTBOX             410
#define IDD_COMP_ANIM_EASE              411
#define IDD_COMP_IGNORELITE             412
#define IDD_COMP_GUIEDITBOX             413
#define IDD_COMP_FLEXIBILITY            414
#define IDD_COMP_GUITAG                 415
#define IDD_COMP_CAMERAPAN              417
#define IDD_COMP_BLOW                   418
#define IDD_PYTHON_FILE_WARN            419
#define IDD_COMP_XFORM                  420
#define IDD_COMP_FIRSTPERSON_CAM        421
#define IDD_COMP_BEHAVIOR_SITTING       422
#define IDD_COMP_GUIUDSCROLL            423
#define IDD_COMP_PHYS_CORE_GROUP        424
#define IDD_COMP_NAV_LADDER             425
#define IDD_COMP_RESPOND_CAMERA         426
#define IDD_COMP_TEMPLATE               427
#define IDD_COMP_GUIKNOB                428
#define IDD_COMP_GUIDRAGBAR             429
#define IDD_COMP_DIST_SPACING           430
#define IDD_COMP_DIST_ORIENT            431
#define IDD_COMP_DIST_ANGPROB           432
#define IDD_COMP_DIST_ALTPROB           433
#define IDD_COMP_DIST_CONFORM           434
#define IDD_COMP_DIST_BITMAP            435
#define IDD_COMP_DIST_RANDOMIZE         436
#define IDD_COMP_DIST_FADE              437
#define IDD_COMP_DIST_WIND              438
#define IDD_COMP_DIST_TEMPLATES         439
#define IDD_COMP_DIST_SCALE             440
#define IDD_COMP_DIST_ACTION            441
#define IDD_COMP_GUIRADIOGROUP          442
#define IDD_COMP_GUIPROCROLLOUT         443
#define IDD_COMP_LODFADE                444
#define IDD_COMP_GUIDYNDISPLAY          445
#define IDD_COMP_RESPOND_DELAY          446
#define IDD_PICK_MTL                    447
#define IDD_COMP_CLOTHING               448
#define IDD_COMP_RESPOND_CAMVIEW        449
#define IDD_COMP_CAMERA_RAIL            450
#define IDD_COMP_MULTIBEH_NORMAL        451
#define IDD_COMP_MULTIBEH               452
#define IDD_COMP_BLENDONTO              453
#define IDD_COMP_GUISCHEME              454
#define IDD_COMP_CAMERA_CIRCLE          455
#define IDD_COMP_UNLEASH                456
#define IDD_COMP_GEO_DICE               457
#define IDD_COMP_RESPOND_VISIBILITY     458
#define IDD_COMP_PARTICLE_WIND          459
#define IDD_COMP_FORCE_RTLIGHT          460
#define IDD_COMP_DETECTOR_ANIM          461
#define IDD_COMP_CAMERAZOOM             462
#define IDD_COMP_DETECTOR_MTL           463
#define IDD_PICK_NODE                   464
#define IDD_COMP_BLENDONTOADV           465
#define IDD_COMP_VEHICLE                466
#define IDD_COMP_PARTICLE_UNIWIND       467
#define IDD_COMP_DISTFADE               468
#define IDD_COMP_SOUNDGUI               469
#define IDD_COMP_SHADOW_CAST            473
#define IDD_COMP_SHADOW_RCV             474
#define IDD_COMP_SHADOW_LIGHT           475
#define IDD_COMP_SOUNDSRC               476
#define IDD_COMP_PHYS_SUBWORLD          478
#define IDD_COMP_RANDOMSOUND_GROUPS     479
#define IDD_COMP_FOOTSTEP_SOUND         480
#define IDD_COMP_RESPOND_FOOT_SURFACE   481
#define IDD_COMP_EAXLISTENER            482
#define IDD_COMP_EAXBUFFER              483
#define IDD_COMP_FP_FOOTPRINT           484
#define IDD_COMP_FP_RIPPLE              485
#define IDD_COMP_FP_DIRTY               486
#define IDD_COMP_FP_PRINTSHAPE          487
#define IDD_COMP_FP_PUDDLE              488
#define IDD_COMP_SUBWORLD_REGION        489
#define IDD_COMP_NPC_SPAWN              490
#define IDD_COMP_GUIMULTILINE           491
#define IDD_COMP_FP_ACTIVEPRINTSHAPE    494
#define IDD_COMP_FP_WAKE                495
#define IDD_COMP_GUIPROXY               496
#define IDD_COMP_FILTERINHERIT          497
#define IDD_COMP_SOUNDBASE              498
#define IDD_COMP_STEREIZE               499
#define IDD_COMP_CLIMB_TRIGGER          500
#define IDD_COMP_CLIMB_BLOCK            501
#define IDD_COMP_SWIVEL                 502
#define IDD_COMP_MORPHLAY               503
#define IDD_COMP_MORPHSEQ               504
#define IDD_COMP_OBJECT_FOLLOWCAM       505
#define IDD_COMP_EMOTE                  506
#define IDD_COMP_W_GEOWATER             507
#define IDD_COMP_W_ADVWATER             508
#define IDD_COMP_W_BASICSHORE           509
#define IDD_COMP_W_ADVSHORE             510
#define IDD_COMP_W_REFOBJECT            511
#define IDD_COMP_SHORE                  512
#define IDD_COMP_GUIPROGRESS            513
#define IDD_COMP_W_ENVMAP               514
#define IDD_COMP_MAINTAINERS_MARKER     515
#define IDD_COMP_NOSHOW                 516
#define IDD_COMP_GUICLICKMAP            517
#define IDD_COMP_VISREGION              518
#define IDD_COMP_SMOOTHAV               519
#define IDD_COMP_SKINEDIT               520
#define IDI_ZOOMIN                      520
#define IDD_COMP_GUISKIN                521
#define IDI_ZOOMOUT                     521
#define IDD_COMP_GUIMENUANCHOR          522
#define IDD_COMP_WDECAL                 523
#define IDD_COMP_ANIMCAM_COMMANDS       524
#define IDD_COMP_NETSYNC                525
#define IDD_COMP_RELREGION              526
#define IDD_COMP_REPRESENT              527
#define IDD_COMP_REPGROUP               528
#define IDD_COMP_PHYS_BRIDGE            529
#define IDD_COMP_SMOOTHBASE             530
#define IDD_COMP_SMOOTHSNAP             531
#define IDD_COMP_IMAGELIB               532
#define IDD_COMP_W_VTXHELP              533
#define IDD_COMP_PARTICLE_FLOCK         534
#define IDD_COMP_EFFVISSET              535
#define IDD_COMP_ENVMAP                 536
#define IDD_COMP_W_TEXWATER             537
#define IDD_COMP_SOUNDPHYS              538
#define IDD_COMP_SHOOTABLE              539
#define IDD_COMP_FP_BULLET              540
#define IDD_COMP_FP_TORPEDO             541
#define IDD_COMP_PANIC                  542
#define IDD_COMP_RESPOND_ENABLE_PHYS    543
#define IDD_COMP_RESPOND_CAM_FORCE      544
#define IDD_COMP_FORCE_CTT              545
#define IDD_COMP_MARKER                 546
#define IDD_COMP_LOSFADE                547
#define IDD_COMP_GZFADE                 548
#define IDD_COMP_DYNMAT                 549
#define IDD_COMP_SORT_AS_OPAQUE         550
#define IDD_COMP_RESPOND_SUBWORLD       552
#define IDD_PICK_LOCALIZATION           553
#define IDD_COMP_OBJ_FLOCKER            555
#define IDD_COMP_GRASS                  556
#define IDD_COMP_ANIM_COMPRESS          557
#define IDD_COMP_RIDE_ANIMATED_PHYS     558
#define IDC_LIST_TARGS                  1011
#define IDC_LIST_TARGS2                 1012
#define IDC_COMP_DISTRIB_PROBTEXMAP     1018
#define IDC_ADD_TARGS                   1027
#define IDC_DELETE_TARGS                1028
#define IDC_DET_COMBO                   1031
#define IDC_ONESHOT                     1036
#define IDC_ADD_CMD                     1038
#define IDC_REMOVE_CMD                  1039
#define IDC_ANIM_COMBO                  1039
#define IDC_CMD_LIST                    1040
#define IDC_COMP_LIGHTMAP_COLOR         1040
#define IDC_COMP_ALIAS                  1042
#define IDC_ANIM_GREEN_COMBO            1042
#define IDC_ANIM_OPEN_COMBO             1043
#define IDC_PLAYERSTART                 1046
#define IDC_COMP_PORTAL_ROOM1           1047
#define IDC_COMP_PORTAL_ROOM2           1048
#define IDC_COMP_INTEREST_EDIT1         1051
#define IDC_COMP_INTEREST_EDIT2         1052
#define IDC_COMP_INTEREST_SPIN1         1053
#define IDC_COMP_INTEREST_SPIN2         1054
#define IDC_COMP_PHYSICAL_EDIT1         1054
#define IDC_COMP_PHYSICAL_EDIT2         1055
#define IDC_COMP_PHYSICAL_SPIN1         1056
#define IDC_COMP_PHYSICAL_SPIN2         1057
#define IDC_COMP_PHYSICAL_EDIT3         1058
#define IDC_COMP_PHYSICAL_SPIN3         1059
#define IDC_COMP_PHYSICAL_P3SF_EDIT1    1062
#define IDC_COMP_PHYSICAL_P3SF_EDIT2    1063
#define IDC_COMP_PHYSICAL_P3SF_SPIN1    1064
#define IDC_COMP_PHYSICAL_P3SF_SPIN2    1065
#define IDC_COMP_PHYSICAL_P3SF_EDIT3    1066
#define IDC_COMP_PHYSICAL_P3SF_SPIN3    1067
#define IDC_COMP_PHYSICAL_P3ST_EDIT1    1068
#define IDC_COMP_NAV_LADDER_LOOPS_EDIT  1068
#define IDC_COMP_PHYSICAL_P3ST_EDIT2    1069
#define IDC_COMP_PHYSICAL_P3ST_SPIN1    1070
#define IDC_COMP_NAV_LADDER_LOOPS_SPIN  1070
#define IDC_COMP_PHYSICAL_P3ST_SPIN2    1071
#define IDC_COMP_PHYSICAL_P3ST_SPIN3    1073
#define IDC_RADIO_BBOX                  1074
#define IDC_RADIO_DOWN                  1074
#define IDC_RADIO_BSPHERE               1075
#define IDC_RADIO_UP                    1075
#define IDC_RADIO_REPORT_DYN            1075
#define IDC_RADIO_BHULL                 1076
#define IDC_RADIO_PICKSTATE             1077
#define IDC_RADIO_BSPHERE2              1078
#define IDC_COMP_PHYSICAL_P3ST_EDIT3    1079
#define IDC_RADIO_REPORT_BOTH           1079
#define IDC_RADIO_BLOCK_DYNAMICS        1079
#define IDC_RADIO_BLOCK_DYNAMIC         1079
#define IDC_RADIO_REPORT_AVATAR         1080
#define IDC_COMP_PARTICLE_PPS           1084
#define IDC_COMP_PARTICLE_PPS_SPIN      1085
#define IDC_COMP_SOUND3D_FILENAME_BTN   1090
#define IDC_GUI_BGALPHA                 1091
#define IDC_GUI_SFGALPHA                1092
#define IDC_GUI_SBGALPHA                1093
#define IDC_COMP_SOUND3D_EDIT3          1096
#define IDC_COMP_SOUND3D_SPIN3          1097
#define IDC_COMP_SOUND3D_EDIT4          1098
#define IDC_COMP_SOUND3D_SPIN4          1099
#define IDC_GUI_STEP                    1100
#define IDC_GUI_STEP_SPIN               1101
#define IDC_COMP_PHYS_TERRAIN_EDIT1     1105
#define IDC_COMP_PHYS_TERRAIN_SPIN1     1106
#define IDC_COMP_PHYS_TERRAIN_EDIT2     1107
#define IDC_COMP_ANIM_LOOP_CKBX         1108
#define IDC_COMP_PHYS_TERRAIN_SPIN2     1108
#define IDC_COMP_SOUND3D_LOOPCHKBOX     1108
#define IDC_COMP_ANIM_AUTOSTART_CKBX    1109
#define IDC_COMP_ANIM_USE_GLOBAL        1110
#define IDC_COMP_SOUND3D_AUTOSTART_CKBX 1111
#define IDC_COMP_ANIM_PHYSANIM          1111
#define IDC_COMP_PHYS_AGILITY_STATUS    1112
#define IDC_COMP_SOUND3D_CONEEFFECT_CKBX 1112
#define IDC_COMP_PHYS_WEIGHT_SPIN1      1113
#define IDC_COMP_PHYS_ACCEL_STATUS      1113
#define IDC_COMP_PHYS_TR_STATUS         1114
#define IDC_COMP_PHYS_AGILITY_SLIDER    1115
#define IDC_COMP_PHYS_WEIGHT_SLIDER     1116
#define IDC_RADIO_FIXEDCAM              1116
#define IDC_COMP_PHYS_ACCEL_SLIDER      1116
#define IDC_RADIO_FIXEDPANCAM           1117
#define IDC_COMP_PHYS_SIMP_EDIT1        1117
#define IDC_COMP_PHYS_SIMP_SPIN1        1118
#define IDC_COMP_PHYS_CRIT_MVEL_SPIN    1119
#define IDC_COMP_PHYS_CRIT_MVEL_EDIT    1120
#define IDC_COMP_PHYS_SIMP_EDIT2        1121
#define IDC_COMP_PHYS_SIMP_EDIT3        1122
#define IDC_COMP_PHYS_SIMP_SPIN2        1123
#define IDC_COMP_PHYS_PICKSTATE_BASE    1123
#define IDC_COMP_PHYS_SIMP_SPIN3        1124
#define IDC_COMP_PHYS_PICKSTATE_SIMP    1125
#define IDC_COMP_PHYS_PICKSTATE_TERRAIN 1125
#define IDC_COMP_PHYS_TR_SLIDER         1125
#define IDC_COMP_PHYS_PICKSTATE_PLAYER  1126
#define IDC_COMP_ROOM_AGE_TEXTBOX       1129
#define IDC_COMP_ROOM_DISTRICT_TEXTBOX  1130
#define IDC_COMP_ROOM_ROOM_TEXTBOX      1131
#define IDC_ANIM_NAMES                  1142
#define IDC_SOUND_FILENAME_TEXT         1143
#define IDC_LOOP_NAMES                  1145
#define IDC_ANIM_GLOBAL_LIST            1146
#define IDC_ADD_ACTIVATOR               1149
#define IDC_DEL_TARGS                   1151
#define IDC_COMP_SOUND_REVERB_BBOX      1152
#define IDC_DEL_TARGS2                  1152
#define IDC_COMP_SOUND_REVERB_BSPHERE   1153
#define IDC_COMP_SOUND_REVERB_BHULL     1154
#define IDC_COMP_SOUND_REVERB_DDLIST    1155
#define IDC_COMP_AVATAR_PROXY_PICKH     1156
#define IDC_COMP_AVATAR_PROXY_PICKT     1157
#define IDC_COMP_DISTRIB_PROBCOLORCHAN  1162
#define IDC_COMP_AVATAR_PROXY_PICKB     1163
#define IDC_COMP_LIGHTMAP_EDIT1         1163
#define IDC_COMP_LOD_AVATAR_ROOT_PICKB  1164
#define IDC_COMP_LIGHTMAP_SPIN1         1165
#define IDC_COMP_LOD_AVATAR_MESH_PICKB  1165
#define IDC_COMP_IGNORE_CKBX            1167
#define IDC_COMP_PHYS_PICKSTATE_DETECTOR 1168
#define IDC_COMP_AVATAR_PROXY_PICKH2    1170
#define IDC_COMP_AVATAR_PROXY_PICKT2    1171
#define IDC_COMP_LM_DUMMY               1172
#define IDC_COMP_LIGHT_SLIDER           1173
#define IDC_COMP_SOUND3D_VOLSLIDER      1175
#define IDC_COMP_SOUND3D_SLIDERVIEWER   1176
#define IDC_COMP_SOUND_REV_ROOMHFATTEN  1176
#define IDC_RESPONDERS                  1177
#define IDC_COMP_SOUND3D_VOLSLIDER2     1177
#define IDC_COMP_SOUND_REV_ROOMROLLOFF  1177
#define IDC_COMP_SOUND3D_SLIDERVIEWER2  1178
#define IDC_COMP_SOUND_REV_DECAYRATIO   1178
#define IDC_COMP_SOUND3D_ICONEANGLE_EDIT 1179
#define IDC_COMP_SOUND_REV_REFLECTDELAY 1179
#define IDC_COMP_SOUND3D_ICONEANGLE_SPIN 1180
#define IDC_COMP_SOUND_REV_REVERBDELAY  1180
#define IDC_COMP_SOUND3D_OCONEANGLE_EDIT 1181
#define IDC_COMP_SOUND_REV_MODALDENSITY 1181
#define IDC_COMP_SOUND3D_OCONEANGLE_SPIN 1182
#define IDC_COMP_SOUND_REV_REFHF        1182
#define IDC_COMP_SOUNDMOD_FEEDBACK_SPIN 1183
#define IDC_COMP_SOUND_REV_ROOMATTEN_EDIT 1183
#define IDC_COMP_SOUNDMOD_FEEDBACK_EDIT 1184
#define IDC_COMP_SOUND_REV_ROOMHFATTEN_EDIT 1184
#define IDC_COMP_SOUNDMOD_LOWFREQ_OSC_CUTOFF_EDIT 1185
#define IDC_COMP_SOUND_REV_ROOMROLLOFF_EDIT 1185
#define IDC_COMP_SOUNDMOD_LOWFREQ_OSC_CUTOFF_SPIN 1186
#define IDC_COMP_SOUND_REV_DECAYTIME_EDIT 1186
#define IDC_CLOTHING_GROUP              1186
#define IDC_COMP_SOUNDMOD_FEEDBACK_DELAY_EDIT 1187
#define IDC_COMP_SOUND_REV_DECAYRATIO_EDIT 1187
#define IDC_CLOTHING_TYPE               1187
#define IDC_COMP_SOUNDMOD_FEEDBACK_DELAY_SPIN 1188
#define IDC_COMP_SOUND_REV_REFLECTATTEN_EDIT 1188
#define IDC_COMP_SOUNDMOD_WET_EDIT      1189
#define IDC_COMP_SOUND_REV_REFLECTDELAY_EDIT 1189
#define IDC_COMP_SOUNDMOD_WET_SPIN      1190
#define IDC_COMP_SOUND_REV_REVERBATTEN_EDIT 1190
#define IDC_COMP_SOUNDMOD_DELAYMOD_EDIT 1191
#define IDC_COMP_SOUND_REV_REVERBDELAY_EDIT 1191
#define IDC_COMP_SOUNDMOD_DELAYMOD_SPIN 1192
#define IDC_COMP_SOUND_REV_ECHODENSITY_EDIT 1192
#define IDC_COMP_SOUNDMOD_LOWFREQ_DDLIST 1193
#define IDC_COMP_SOUND_REV_MODALDENSITY_EDIT 1193
#define IDC_COMP_SOUNDMOD_GAIN_EDIT     1194
#define IDC_COMP_SOUND_REV_REFHF_EDIT   1194
#define IDC_COMP_SOUNDMOD_GAIN_SPIN     1195
#define IDC_COMP_SOUNDMOD_ATTACK_EDIT   1196
#define IDC_COMP_SOUNDMOD_ATTACK_SPIN   1197
#define IDC_COMP_SOUNDMOD_RELEASE_EDIT  1198
#define IDC_COMP_SOUNDMOD_RELEASE_SPIN  1199
#define IDC_COMP_SOUNDMOD_COMPTHRESH_EDIT 1200
#define IDC_COMP_SOUNDMOD_COMPTHRESH_SPIN 1201
#define IDC_COMP_SOUNDMOD_COMPRATIO_EDIT 1202
#define IDC_COMP_SOUNDMOD_COMPRATIO_SPIN 1203
#define IDC_COMP_SOUNDMOD_ATTACKPRE_EDIT 1204
#define IDC_COMP_SOUNDMOD_GAIND_EDIT    1204
#define IDC_COMP_SOUNDMOD_ATTACKPRE_SPIN 1205
#define IDC_COMP_SOUNDMOD_GAIND_SPIN    1205
#define IDC_COMP_SOUNDMOD_INTENSE_EDIT  1206
#define IDC_COMP_SOUNDMOD_INTENSE_SPIN  1207
#define IDC_COMP_SOUNDMOD_EFFECTC_EDIT  1208
#define IDC_COMP_SOUNDMOD_EFFECTC_SPIN  1209
#define IDC_COMP_SOUNDMOD_EFFECTW_EDIT  1210
#define IDC_COMP_SOUNDMOD_EFFECTW_SPIN  1211
#define IDC_COMP_SOUNDMOD_LOWFREQCUT_EDIT 1212
#define IDC_COMP_SOUNDMOD_LOWFREQCUT_SPIN 1213
#define IDC_COMP_SOUNDMOD_SWAP_DELAY    1214
#define IDC_COMP_SOUNDMOD_LEFTFEEDB_EDIT 1215
#define IDC_COMP_SOUNDMOD_LEFTFEEDB_SPIN 1216
#define IDC_COMP_SOUNDMOD_RIGHTFEEDB_EDIT 1217
#define IDC_COMP_SOUNDMOD_RIGHTFEEDB_SPIN 1218
#define IDC_COMP_SOUNDMOD_FEEDBACK_DELAYF_EDIT 1219
#define IDC_COMP_SOUNDMOD_FEEDBACK_DELAYF_SPIN 1220
#define IDC_COMP_SOUNDMOD_MODRATE_EDIT  1221
#define IDC_COMP_SOUNDMOD_MODRATE_SPIN  1222
#define IDC_COMP_SOUNDMOD_WAVESHAPE_DDLIST 1223
#define IDC_COMP_SOUNDMOD_REVERBGAIN_EDIT 1224
#define IDC_COMP_SOUNDMOD_REVERBGAIN_SPIN 1225
#define IDC_COMP_SOUNDMOD_REVERBMIX_EDIT 1226
#define IDC_COMP_SOUNDMOD_REVERBMIX_SPIN 1227
#define IDC_COMP_SOUNDMOD_REVERBDELAY_EDIT 1228
#define IDC_COMP_SOUNDMOD_REVERBDELAY_SPIN 1229
#define IDC_COMP_SOUNDMOD_PHASEDIF_DDLIST 1231
#define IDC_COMP_OCCLUSION_CKBX         1232
#define IDC_COMP_PHYS_CUSTOMCHK         1234
#define IDC_ADD_SOUNDOBJ                1235
#define IDC_COMP_PARTICLE_NODIE         1235
#define IDC_COMP_CHECK_LOS              1236
#define IDC_COMP_PHYS_ALIGN_SHAPE_BOOL  1237
#define IDC_COMP_CHECK_LOS2             1237
#define IDC_COMP_CHECK_LOS3             1238
#define IDC_LOOP_COMBO                  1239
#define IDC_STATIC_VOLANGLE             1251
#define IDC_STATIC_FADEANGLE            1252
#define IDC_STATIC_SLIDERANGLE          1253
#define IDC_STATIC_SLIDER_START         1254
#define IDC_STATIC_SLIDER_END           1255
#define IDC_COMBO1                      1256
#define IDC_CAMERACMD_OFFSETX           1258
#define IDC_CAMERACMD_SPIN_OFFSETX      1259
#define IDC_CAMERACMD_OFFSETY           1260
#define IDC_PHYS_WIDTH_EDIT             1260
#define IDC_CAMERACMD_SPIN_OFFSETY      1261
#define IDC_PHYS_WIDTH_SPIN             1261
#define IDC_CAMERACMD_OFFSETZ           1262
#define IDC_CAMERACMD_OFFSETY2          1262
#define IDC_CAMERACMD_SPIN_OFFSETZ      1263
#define IDC_CAMERACMD_SPIN_OFFSETY2     1263
#define IDC_CAMERACMD_OFFSETX2          1264
#define IDC_CAMERACMD_SPIN_OFFSETX2     1265
#define IDC_COMP_CAMERACMD_PICKSTATE_BASE 1266
#define IDC_CAMERACMD_OFFSETX3          1266
#define IDC_COMP_LOCATION_AGECOMBO      1267
#define IDC_CAMERACMD_SPIN_OFFSETX3     1267
#define IDC_COMP_LOCATION_PAGECOMBO     1268
#define IDC_CAMERACMD_OFFSETX5          1268
#define IDC_CAMERACMD_SPIN_OFFSETX5     1269
#define IDC_CAMERACMD_OFFSETY4          1270
#define IDC_CAMERACMD_SPIN_OFFSETY4     1271
#define IDC_CAMERACMD_OFFSETZ2          1272
#define IDC_CAMERACMD_SPIN_OFFSETZ2     1273
#define IDC_FLOCK_CONFORM_DIST          1274
#define IDC_RADIO_LISTENER              1275
#define IDC_FLOCK_CONFORM_DIST_SPIN     1275
#define IDC_RADIO_CAMERA                1276
#define IDC_RADIO_OBJECT                1277
#define IDC_COMP_LINE_CHOOSE_OBJECT     1278
#define IDC_FLOCK_CONFORM_STR           1278
#define IDC_COMP_LINE_CHOOSE_PATH       1279
#define IDC_FLOCK_CONFORM_STR_SPIN      1279
#define IDC_LINKSPAWNPOINT              1280
#define IDC_FLOCK_REPEL_DIST            1280
#define IDC_LINKAGEFILENAME             1281
#define IDC_FLOCK_REPEL_DIST_SPIN       1281
#define IDC_LINKINGRULE                 1282
#define IDC_FLOCK_REPEL_STR             1282
#define IDC_LOOP_TEXT                   1283
#define IDC_LINKSPAWNPOINTTITLE         1283
#define IDC_FLOCK_REPEL_STR_SPIN        1283
#define IDC_LINKAGEINSTANCENAME         1284
#define IDC_FLOCK_GOAL_DIST             1284
#define IDC_FLOCK_GOAL_DIST_SPIN        1285
#define IDC_LINKAGELINKINANIMNAME       1285
#define IDC_COMP_CLICK_USEPROXY         1286
#define IDC_FLOCK_GOAL_STR              1286
#define IDC_PARENTAGEFILENAME           1286
#define IDC_COMP_CLICK_PROXY            1287
#define IDC_FLOCK_GOAL_STR_SPIN         1287
#define IDC_LINKAGELINKINANIMNAME2      1287
#define IDC_LINKAGEINSTANCEGUID         1287
#define IDC_FLOCK_MAX_SPEED             1288
#define IDC_COMP_CLICK_PROXYREGION      1289
#define IDC_FLOCK_MAX_SPEED_SPIN        1289
#define IDC_COMP_CLICK_DEG              1290
#define IDC_FLOCK_GOAL_CHASE_STR        1290
#define IDC_COMP_CLICK_DEGSPIN          1291
#define IDC_FLOCK_GOAL_CHASE_STR_SPIN   1291
#define IDC_FLOCK_FULL_CHASE_DIST       1292
#define IDC_COMP_RS_AUTOSTART           1293
#define IDC_FLOCK_FULL_CHASE_DIST_SPIN  1293
#define IDC_COMP_CLICK_OMNI             1294
#define IDC_RADIO_RS_NORMAL             1294
#define IDC_FLOCK_MAX_ORBIT_SPEED       1294
#define IDC_RADIO_RS_NOREP              1295
#define IDC_FLOCK_MAX_ORBIT_SPEED_SPIN  1295
#define IDC_RADIO_RS_FSREP              1296
#define IDC_RADIO_RS_FSSTOP             1297
#define IDC_RADIO_RS_SEQ                1298
#define IDC_COMP_RS_DELAYMIN            1299
#define IDC_COMP_RS_DELAYMIN_SPIN       1300
#define IDC_COMP_RS_DELAYMAX            1301
#define IDC_COMP_CLICK_DRAG_USEX        1301
#define IDC_COMP_RS_DELAYMAX_SPIN       1302
#define IDC_COMP_CLICK_DRAG_USE_LOOPX   1302
#define IDC_COMP_CLICK_DRAG_ANIMX       1303
#define IDC_COMP_CLICK_DRAG_OMNI        1305
#define IDC_COMP_CLICK_DRAG_TEXT1       1306
#define IDC_COMP_CLICK_DRAG_DEG         1307
#define IDC_RADIO_RS_DELAYSTART         1308
#define IDC_COMP_CLICK_DRAG_DEGSPIN     1308
#define IDC_RADIO_RS_DELAYEND           1309
#define IDC_COMP_CLICK_DRAG_USEPROXYPHYS 1309
#define IDC_RADIO_RS_DELAYNEVER         1310
#define IDC_COMP_CLICK_DRAG_PROXY       1310
#define IDC_COMP_CLICK_DRAG_ALLORNOT    1311
#define IDC_COMP_CLICK_DRAG_PROXYREGION 1312
#define IDC_COMP_AVATAR_FRICTION_SPIN   1313
#define IDC_COMP_CLICK_DRAG_USEYANIM    1313
#define IDC_COMP_CLICK_DRAG_ANIM_Y      1314
#define IDC_ENABLE                      1315
#define IDC_COMP_CLICK_DRAG_USE_LOOPY   1316
#define IDC_COMP_AVATAR_FRICTION_EDIT   1322
#define IDC_COMP_ONESHOT_ANIM_TEXTBOX   1325
#define IDC_COMP_ONESHOT_PLAY_BACK_BOOL 1326
#define IDC_COMP_ONESHOT_CONT_SPEED_BOOL 1327
#define IDC_SMART_SEEK                  1328
#define IDC_SIT_APP_LEFT                1329
#define IDC_NO_SEEK                     1329
#define IDC_COMP_ONESHOT_SEEK_FIELD_EDIT 1330
#define IDC_SIT_APP_RIGHT               1330
#define IDC_COMP_ONESHOT_SEEK_FIELD_SPIN 1331
#define IDC_SIT_NOFORWARD               1331
#define IDC_COMP_PARTICLE_CONE          1332
#define IDC_COMP_PARTICLE_CONE_SPIN     1333
#define IDC_COMP_PARTICLE_VELMIN        1334
#define IDC_COMP_PARTICLE_VELMIN_SPIN   1335
#define IDC_COMP_PARTICLE_VELMAX        1336
#define IDC_COMP_PARTICLE_VELMAX_SPIN   1337
#define IDC_COMP_PARTICLE_LIFEMIN       1338
#define IDC_COMP_PARTICLE_LIFEMIN_SPIN  1339
#define IDC_COMP_PARTICLE_LIFEMAX       1340
#define IDC_COMP_PARTICLE_LIFEMAX_SPIN  1341
#define IDC_COMP_PARTICLE_SCALEMIN      1342
#define IDC_COMP_PARTICLE_SCALEMIN_SPIN 1343
#define IDC_COMP_PARTICLE_SCALEMAX      1344
#define IDC_COMP_PARTICLE_SCALEMAX_SPIN 1345
#define IDC_GEN_TYPE                    1346
#define IDC_COMP_PARTICLE_GRAVITY       1347
#define IDC_COMP_PARTICLE_GRAVITY_SPIN  1348
#define IDC_COMP_PARTICLE_DRAG          1349
#define IDC_COMP_PARTICLE_DRAG_SPIN     1350
#define IDC_COMP_PARTICLE_VOLUME_NODE   1351
#define IDC_COMP_PARTICLE_PRESIM        1351
#define IDC_COMP_PARTICLE_FADEZ         1352
#define IDC_COMP_PARTICLE_PRESIM_SPIN   1352
#define IDC_COMP_PARTICLE_FADE_DIST     1353
#define IDC_COMP_PARTICLE_WIND_MULT     1353
#define IDC_COMP_PARTICLE_FADE_DIST_SPIN 1354
#define IDC_COMP_PARTICLE_WIND_MULT_SPIN 1354
#define IDC_COMP_CAMERACMD_CUT          1355
#define IDC_COMP_PARTICLE_MASS_RANGE    1355
#define IDC_COMP_CAMERACMD_WORLDSPACE   1356
#define IDC_COMP_PARTICLE_MASS_RANGE_SPIN 1356
#define IDC_COMP_PARTICLE_ROT_RANGE     1357
#define IDC_COMP_ANIM_AVATAR_SHAREBOOL  1358
#define IDC_COMP_PARTICLE_ROT_RANGE_SPIN 1358
#define IDC_COMP_ANIM_AVATAR_GLOBALBOOL 1359
#define IDC_COMP_FOLLOW_CHOOSE_OBJECT   1360
#define IDC_F_RADIO_PLAYER              1361
#define IDC_F_RADIO_CAMERA              1363
#define IDC_F_RADIO_LISTENER            1364
#define IDC_F_RADIO_OBJECT              1365
#define IDC_COMP_LIGHTINC_CHARS         1365
#define IDC_COMP_FOLLOW_X               1366
#define IDC_COMP_LIGHTINC_FILTER        1366
#define IDC_COMP_FOLLOW_Y               1367
#define IDC_COMP_INV_OBJECT_ITINERANTBOOL 1367
#define IDC_COMP_FOLLOW_Z               1368
#define IDC_COMP_INV_OBJECT_RESPAWNBOOL 1368
#define IDC_COMP_FOLLOW_ROTATE          1369
#define IDC_COMP_INV_OBJECT_CONSUMABLE  1369
#define IDC_COMP_FILTER_ACTIVE          1369
#define IDC_COMP_INV_OBJECT_LIFE_EDIT   1370
#define IDC_COMP_INV_OBJECT_LIFE_SPIN   1371
#define IDC_COMP_SOFTVOL_SOFT           1372
#define IDC_COMP_SOFTVOL_SOFT_SPIN      1373
#define IDC_COMP_DISTRIB_RNDPOSRADIUS   1374
#define IDC_COMP_SOFTVOL_INSIDE         1374
#define IDC_CODE                        1375
#define IDC_COMP_DISTRIB_RNDPOSRADIUS_SPIN 1375
#define IDC_COMP_SOFTVOL_INSIDE_SPIN    1375
#define IDC_BUTTON1                     1376
#define IDC_COMP_SOFTVOL_OUTSIDE        1376
#define IDC_COMP_SOUND_REV_ROOMATTEN    1377
#define IDC_COMP_SOFTVOL_OUTSIDE_SPIN   1377
#define IDC_GUI_ZOUT                    1377
#define IDC_COMP_SOUND_REV_DECAYTIME    1378
#define IDC_COMP_SOUND_REV_REFLECTATTEN 1379
#define IDC_COMP_PHYSGADGET_ENTERBOX    1380
#define IDC_CHECK_WAIT                  1381
#define IDC_COMP_PHYS_SUSPENSION_BUTTON 1382
#define IDC_COMP_SOUND_REV_REVERBATTEN  1383
#define IDC_COMP_PHYSGADGET_EXITBOX     1384
#define IDC_COMP_PHYS_ROTATION_BUTTON   1385
#define IDC_RADIO_FINISH                1386
#define IDC_COMP_SOUND_REV_ECHODENSITY  1387
#define IDC_RADIO_POINT                 1388
#define IDC_WAIT_WHO                    1390
#define IDC_WAIT_POINT                  1391
#define IDC_COMP_TEXT                   1392
#define IDC_COMP_PHYS_STEERING_BUTTON   1393
#define IDC_OBJ_TEXT                    1393
#define IDC_COMP_PHYS_POSITION_BUTTON   1394
#define IDC_COMP_PHYS_PARENT            1395
#define IDC_COMP_PHYS_HINGE_AXIS_RADIO  1396
#define IDC_COMP_PHYS_HINGE_AXIS_RADIO2 1397
#define IDC_COMP_PHYS_HINGE_AXIS_RADIO3 1398
#define IDC_COMP_PHY_SS_LENGTH_EDIT     1399
#define IDC_COMP_PHY_SS_LENGTH_SPIN     1400
#define IDC_COMP_PHYS_SS_REBOUND_EDIT   1401
#define IDC_COMP_PHYS_SS_REBOUND_SPIN   1402
#define IDC_COMP_PHYS_SS_STRENGTH_EDIT  1403
#define IDC_COMP_PHYS_SS_STRENGTH_SPIN  1404
#define IDC_COMP_PHYS_PINNED_STATE_BOOL 1405
#define IDC_STATE_COMBO                 1406
#define IDC_COMP_PHYS_USE_PARENT_BOOL   1406
#define IDC_COMP_LIGHTREGION_CHOOSE_VOLUME 1407
#define IDC_COMP_PHYS_PINNED_STATE_BOOL2 1407
#define IDC_ADD_VOLUME                  1408
#define IDC_SWITCH_COMBO                1408
#define IDC_COMP_SOFTVOLUME_NEGATE_CHOOSE_SUB 1409
#define IDC_UP_REPS                     1409
#define IDC_COMP_PHYS_FRICTION_SLIDER   1410
#define IDC_DOWN_REPS                   1410
#define IDC_COMP_PHYS_FRICTION_SPIN1    1411
#define IDC_VAL_REPS                    1411
#define IDC_COMP_PHYS_OPENANGLE_SPIN    1412
#define IDC_COMP_PHYS_OPENANGLE_EDIT    1413
#define IDC_COMP_PHYS_CLOSEANGLE_SPIN   1414
#define IDC_COMP_PHYS_CLOSEANGLE_EDIT   1415
#define IDC_COMP_PHYS_STRENGTH_SPIN     1416
#define IDC_STIFFNESS_SPIN              1416
#define IDC_COMP_PHYS_STRENGTH_SLIDER   1417
#define IDC_MTL_BUTTON                  1417
#define IDC_STRENGTH_SPIN               1417
#define IDC_COMP_PHYS_TAU_SPIN          1418
#define IDC_OBJ_LIST                    1418
#define IDC_COMP_PHYS_PICKHULL_CRIT     1418
#define IDC_NODE_BUTTON                 1418
#define IDC_BOUNCE_BUTTON               1418
#define IDC_COMP_PHYS_TAU_SLIDER        1419
#define IDC_COMP_LIST                   1419
#define IDC_COMP_PHYS_PUPPET_ROOT_PICKB 1419
#define IDC_MTL_NODE_BUTTON             1419
#define IDC_ANIM_BUTTON                 1420
#define IDC_COMP_PHYS_CRIT_ANIM_TXT     1420
#define IDC_PLACE_BUTTON                1420
#define IDC_ENABLE_CHECK                1421
#define IDC_OBJ_BUTTON                  1421
#define IDC_HIT_BUTTON                  1421
#define IDC_RESPONDER_BUTTON            1422
#define IDC_ENABLED                     1423
#define IDC_RESPONDER_NODE              1423
#define IDC_WAIT_ON_ME_CHECK            1424
#define IDC_SOUND3D_INENABLE            1425
#define IDC_SOUND3D_INLENGTH            1426
#define IDC_SOUND3D_INLENGTHSPIN        1427
#define IDC_SOUND3D_INTYPE              1428
#define IDC_SOUND3D_OUTENABLE           1431
#define IDC_SOUND3D_OUTTYPE             1432
#define IDC_SOUND3D_OUTLENGTH           1433
#define IDC_SOUND3D_OUTLENGTHSPIN       1434
#define IDC_COMP_SOUNDREGION_CHOOSE_VOLUME 1435
#define IDC_SOUND_SOFTENABLE            1436
#define IDC_MARKER_EDIT                 1437
#define IDC_COMP_LOD_AVATAR_STATE       1438
#define IDC_COMP_AVATAR_ROOT_PICKB      1447
#define IDC_COMP_AVATAR_MESH_PICKB      1448
#define IDC_COMP_CAMERARGN_PICKSTATE_BASE 1450
#define IDC_COMP_AUTOCAM_LOS            1451
#define IDC_COMP_AUTOCAM_POA_WORLDSPACE 1452
#define IDC_COMP_POA_WORLDSPACE         1452
#define IDC_COMP_OBJECTPOA_WORLDSPACE   1452
#define IDC_COMP_AUTOCAM_LOS2           1453
#define IDC_COMP_POS_WORLDSPACE         1453
#define IDC_COMP_AUTOCAM_POS_WORLDSPACE 1454
#define IDC_COMP_NAV_LADDER_COMBO       1455
#define IDC_COMP_AUTOCAM_LOS3           1455
#define IDC_COMP_AUTOCAM_VERTICAL       1456
#define IDC_COMP_AUTOCAM_RUN            1457
#define IDC_COMP_PHYS_INVIS_BOUNCE_EDIT 1461
#define IDC_COMP_PHYS_INVIS_BOUNCE_SPIN 1462
#define IDC_COMP_ANIM_EASE_IN_NONE      1463
#define IDC_GUI_CONRADIO                1463
#define IDC_COMP_ANIM_EASE_IN_CONST_ACCEL 1464
#define IDC_COMP_ANIM_EASE_IN_SPLINE    1465
#define IDC_COMP_PHYS_PUPPET_ANIM_TXT   1465
#define IDC_GUI_INHERITRADIO            1465
#define IDC_COMP_ANIM_EASE_IN_TIME      1466
#define IDC_GUI_CLOSERADIO              1466
#define IDC_COMP_ANIM_EASE_IN_TIME_SPIN 1467
#define IDC_GUI_NILRADIO                1467
#define IDC_COMP_ANIM_EASE_OUT_NONE     1468
#define IDC_COMP_ANIM_EASE_OUT_CONST_ACCEL 1469
#define IDC_COMP_ANIM_EASE_OUT_SPLINE   1470
#define IDC_COMP_ANIM_EASE_OUT_TIME     1471
#define IDC_COMP_ANIM_EASE_OUT_TIME_SPIN 1472
#define IDC_GUIDLG_NAME                 1473
#define IDC_COMP_ANIM_EASE_IN_MIN       1473
#define IDC_GUI_CONCMD                  1474
#define IDC_COMP_ANIM_EASE_IN_MIN_SPIN  1474
#define IDC_GUIDLG_AGE                  1474
#define IDC_PYTHON_FILE                 1475
#define IDC_COMP_ANIM_EASE_IN_MAX       1475
#define IDC_GUI_BGCOLOR                 1475
#define IDC_CHECK1                      1476
#define IDC_COMP_ANIM_EASE_IN_MAX_SPIN  1476
#define IDC_GUI_SFGCOLOR                1476
#define IDC_CHECK2                      1477
#define IDC_COMP_ANIM_EASE_OUT_MIN      1477
#define IDC_GUI_SBGCOLOR                1477
#define IDC_COMP_LOS_WIDGET_CB          1478
#define IDC_COMP_ANIM_EASE_OUT_MIN_SPIN 1478
#define IDC_CHECK3                      1478
#define IDC_COMP_LOS_WIDGET_LB          1479
#define IDC_COMP_ANIM_EASE_OUT_MAX      1479
#define IDC_CHECK4                      1479
#define IDC_COMP_LOS_WIDGET_REM_BTN     1480
#define IDC_COMP_ANIM_EASE_OUT_MAX_SPIN 1480
#define IDC_COMP_SOUND_DISABLELOD       1482
#define IDC_COMP_DISTRIB_SPACING        1483
#define IDC_COMP_DISTRIB_SPACING_SPIN   1484
#define IDC_COMP_DISTRIB_ALIGNVECX      1485
#define IDC_COMP_DISTRIB_ALIGNVECX_SPIN 1486
#define IDC_COMP_DISTRIB_ALIGNVECY      1487
#define IDC_COMP_DISTRIB_ALIGNVECY_SPIN 1488
#define IDC_COMP_DISTRIB_ALIGNVECZ      1489
#define IDC_COMP_DISTRIB_ALIGNVECZ_SPIN 1490
#define IDC_COMP_DISTRIB_POLARRANGE     1491
#define IDC_COMP_DISTRIB_POLARRANGE_SPIN 1492
#define IDC_COMP_DISTRIB_AZIMUTHRANGE   1493
#define IDC_COMP_DISTRIB_AZIMUTHRANGE_SPIN 1494
#define IDC_COMP_DISTRIB_ANGPROBX       1495
#define IDC_ADD_SAFE                    1496
#define IDC_COMP_DISTRIB_ANGPROBX_SPIN  1496
#define IDC_COMP_DISTRIB_OVERALLPROB    1497
#define IDC_DEL_SAFE                    1497
#define IDC_COMP_DISTRIB_OVERALLPROB_SPIN 1498
#define IDC_LIST_SAFE                   1498
#define IDC_COMP_DISTRIB_POLARBUNCH     1499
#define IDC_COMP_DISTRIB_POLARBUNCH_SPIN 1500
#define IDC_COMP_DISTRIB_SCALELOX       1501
#define IDC_COMP_DISTRIB_SCALELOX_SPIN  1502
#define IDC_COMP_DISTRIB_SCALEHIX       1503
#define IDC_COMP_DISTRIB_SCALEHIX_SPIN  1504
#define IDC_COMP_DISTRIB_SCALELOY       1505
#define IDC_COMP_DISTRIB_SCALELOY_SPIN  1506
#define IDC_COMP_DISTRIB_SCALELOZ       1507
#define IDC_COMP_DISTRIB_SCALELOZ_SPIN  1508
#define IDC_COMP_DISTRIB_SCALEHIY       1509
#define IDC_COMP_DISTRIB_SCALEHIY_SPIN  1510
#define IDC_COMP_DISTRIB_SCALEHIZ       1511
#define IDC_COMP_DISTRIB_SCALEHIZ_SPIN  1512
#define IDC_COMP_DISTRIB_ALIGNWGT       1513
#define IDC_COMP_DISTRIB_ALIGNWGT_SPIN  1514
#define IDC_COMP_DISTRIB_ANGPROBY       1515
#define IDC_COMP_DISTRIB_ANGPROBY_SPIN  1516
#define IDC_COMP_GUI_MODAL              1517
#define IDC_COMP_DISTRIB_REMAPFROMLO    1517
#define IDC_COMP_CLUSTERSIZE            1518
#define IDC_COMP_DISTRIB_FADEOUTOPAQ    1518
#define IDC_COMP_DISTRIB_REMAPFROMLO_SPIN 1519
#define IDC_COMP_BLOW_SPEED             1519
#define IDC_COMP_CLUSTERSIZE_SPIN       1520
#define IDC_COMP_DISTRIB_FADEOUTOPAQ_SPIN 1520
#define IDC_COMP_DISTRIB_REMAPTOLO      1521
#define IDC_COMP_BLOW_SPEED_SPIN        1521
#define IDC_CLUSTER_CLEAR               1522
#define IDC_COMP_DISTRIB_FADEOUTTRAN    1522
#define IDC_COMP_BLOW_FLUTTER           1522
#define IDC_COMP_DISTRIB_REMAPTOLO_SPIN 1523
#define IDC_COMP_BLOW_FLUTTER_SPIN      1523
#define IDC_COMP_DISTRIB_FADEOUTTRAN_SPIN 1524
#define IDC_COMP_BLOW_CONSTANCY         1524
#define IDC_COMP_DISTRIB_REMAPFROMHI    1525
#define IDC_COMP_BLOW_CONSTANCY_SPIN    1525
#define IDC_CLUSTER_DO_THE_DANCE        1526
#define IDC_COMP_DISTRIB_FADEINTRAN     1526
#define IDC_COMP_DISTRIB_REMAPFROMHI_SPIN 1527
#define IDC_COMP_DISTRIB_LOCK           1528
#define IDC_COMP_DISTRIB_REMAPTOHI      1529
#define IDC_COMP_DISTRIB_FADEINACTIVE   1530
#define IDC_COMP_DISTRIB_REMAPTOHI_SPIN 1531
#define IDC_COMP_DISTFADE_IN_ACTIVE     1531
#define IDC_RADIO_EACHENTRY             1531
#define IDC_RADIO_ENTRYCOUNT            1532
#define IDC_COMP_DISTRIB_FADEINTRAN_SPIN 1532
#define IDC_COMP_DISTRIB_ANGPROBZ       1533
#define IDC_RADIO_FIRSTEXIT             1534
#define IDC_COMP_DISTRIB_FADEINOPAQ     1534
#define IDC_COMP_DISTRIB_ANGPROBZ_SPIN  1535
#define IDC_RADIO_EXITCOUNT             1536
#define IDC_COMP_DISTRIB_FADEINOPAQ_SPIN 1536
#define IDC_COMP_DISTRIB_ANGPROBHI      1537
#define IDC_RADIO_EACHEXIT              1538
#define IDC_COMP_DISTRIB_LOCKSCALEXY    1538
#define IDC_COMP_DISTRIB_ANGPROBTRANS   1538
#define IDC_COMP_DISTRIB_ANGPROBHI_SPIN 1539
#define IDC_COMP_DISTRIB_ANGPROBLO      1540
#define IDC_COMP_DISTRIB_ANGPROBLO_SPIN 1541
#define IDC_GUI_INITTEXT                1542
#define IDC_COMP_DISTRIB_LOCKSCALEXYZ   1542
#define IDC_COMP_DISTRIB_ANGPROBTRANS_SPIN 1542
#define IDC_GUI_FONTSIZE                1543
#define IDC_COMP_DISTRIB_WINDBONEACTIVE 1543
#define IDC_GUI_FGAEDIT                 1544
#define IDC_DISTRIB_CLEAR               1545
#define IDC_GUI_BGAEDIT                 1545
#define IDC_DISTRIB_PREVIEW             1546
#define IDC_COMP_LINE_OFFSETACTIVE      1546
#define IDC_GUI_SFGAEDIT                1546
#define IDC_COMP_LINE_OFFSETDEGREES     1547
#define IDC_GUI_SBGAEDIT                1547
#define IDC_COMP_LINE_OFFSETDEGREES_SPIN 1548
#define IDC_COMP_LINE_OFFSETCLAMPACTIVE 1549
#define IDC_COMP_LINE_OFFSETCLAMP       1550
#define IDC_COMP_IGNORELITE_ON          1550
#define IDC_COMP_LINE_OFFSETCLAMP_SPIN  1551
#define IDC_COMP_IGNORELITE_OFF         1551
#define IDC_COMP_LINE_FORCETOLINE       1552
#define IDC_COMP_IGNORELITE_TOGGLE      1552
#define IDC_COMP_IGNORELITE_SELECTED    1553
#define IDC_COMP_LINE_SPEEDCLAMP        1553
#define IDC_COMP_FLEX_FLEX              1554
#define IDC_COMP_LINE_SPEEDCLAMP_SPIN   1554
#define IDC_COMP_FLEX_FLEX_SPIN         1555
#define IDC_COMP_LINE_SPEEDCLAMPACTIVE  1555
#define IDC_GUI_TAGCOMBO                1556
#define IDC_COMP_FLEX_INTRA             1556
#define IDC_Z_AXIS                      1557
#define IDC_COMP_FLEX_INTRA_SPIN        1557
#define IDC_X_AXIS                      1558
#define IDC_COMP_FLEX_INTER             1558
#define IDC_COMP_BLOW_STRENGTH          1559
#define IDC_COMP_FLEX_INTER_SPIN        1559
#define IDC_COMP_BLOW_STRENGTH_SPIN     1560
#define IDC_COMP_SOFTVOL_ENABLEPARTIAL  1562
#define IDC_COMP_SOFTUNION_ENABLEPARTIAL 1563
#define IDC_COMP_SOFTUNION_INSIDE       1564
#define IDC_COMP_SOFTUNION_INSIDE_SPIN  1565
#define IDC_COMP_SOFTUNION_OUTSIDE      1566
#define IDC_COMP_SOFTUNION_OUTSIDE_SPIN 1567
#define IDC_COMP_SOFTNEGATE_ENABLEPARTIAL 1568
#define IDC_COMP_SOFTNEGATE_INSIDE      1569
#define IDC_COMP_SOFTNEGATE_INSIDE_SPIN 1570
#define IDC_COMP_SOFTNEGATE_OUTSIDE     1571
#define IDC_COMP_SOFTNEGATE_OUTSIDE_SPIN 1572
#define IDC_COMP_SOFTISECT_ENABLEPARTIAL 1573
#define IDC_COMP_SOFTISECT_INSIDE       1574
#define IDC_COMP_SOFTISECT_INSIDE_SPIN  1575
#define IDC_COMP_SOFTISECT_OUTSIDE      1576
#define IDC_COMP_SOFTISECT_OUTSIDE_SPIN 1577
#define IDC_COMP_DISTRIB_WINDBONE       1578
#define IDC_RESPONDER_COMP              1580
#define IDC_COMP_PHYS_VISIBLE_BOOL      1581
#define IDC_CUSTOM1                     1582
#define IDC_COMP_PHYS_PINNED_BOOL       1585
#define IDC_COMP_PHYS_LOS_BOOL          1586
#define IDC_GUI_COMPSELBTN              1587
#define IDC_GROUP_TEXT                  1587
#define IDC_GUI_SCROLLCTRL              1588
#define IDC_GUI_COMPSELBTN2             1588
#define IDC_COMP_PHYS_GROUP_COMBO       1588
#define IDC_GUI_LOWER                   1589
#define IDC_COMP_PHYS_GROUP_LIST        1589
#define IDC_GUI_MDOWNSNDCOMP            1589
#define IDC_GUI_LOWER_SPIN              1590
#define IDC_COMP_PHYS_GROUP_REMOVE      1590
#define IDC_GUI_MUPSNDCOMP              1590
#define IDC_GUI_UPPER                   1591
#define IDC_GUI_MOVERSNDCOMP            1591
#define IDC_GUI_UPPER_SPIN              1592
#define IDC_GUI_MOFFSNDCOMP             1592
#define IDC_COMP_NAV_TRIGGER            1593
#define IDC_GUI_ANIMNODESEL             1593
#define IDC_GUI_SINGLESEL               1594
#define IDC_COMP_NAV_LADDER             1594
#define IDC_GUI_ANIMNODESEL2            1594
#define IDC_GUI_ANIMSNDCOMP             1594
#define IDC_GUI_XPARENT                 1595
#define IDC_GUI_DRAGCHILD               1595
#define IDC_GUI_DRAGDROPSRC             1596
#define IDC_NAME                        1597
#define IDC_GUI_DISABLEKEYS             1597
#define IDC_GUI_ALLOWMULTIROW           1598
#define IDC_CLEARED                     1599
#define IDC_GUI_SCROLLL2R               1599
#define IDC_GUI_SCALERES                1600
#define IDC_TRACKVIEW_SHOW              1601
#define IDC_GUI_PASSTHRU                1601
#define IDC_COMP_DISTRIB_ISOLATION      1602
#define IDC_GUI_ENABLETREE              1602
#define IDC_COMP_PARTICLE_FOLLOW_SYSTEM 1602
#define IDC_COMP_DISTRIB_ISOLATION_SPIN 1603
#define IDC_GUI_HANDSOFF                1603
#define IDC_COMP_DISTRIB_DENSITY        1604
#define IDC_COMP_DISTRIB_DENSITY_SPIN   1605
#define IDC_COMP_DISTRIB_SPACERND       1606
#define IDC_COMP_DISTRIB_SPACERND_SPIN  1607
#define IDC_COMP_DISTRIB_SEPARATION     1608
#define IDC_COMP_DISTRIB_ALTPROBLO      1609
#define IDC_COMP_DISTRIB_ALTPROBLO_SPIN 1610
#define IDC_COMP_DISTRIB_ALTPROBHI      1611
#define IDC_COMP_DISTRIB_ALTPROBHI_SPIN 1612
#define IDC_COMP_DISTRIB_ALTPROBTRANS   1613
#define IDC_COMP_DISTRIB_ALTPROBTRANS_SPIN 1614
#define IDC_COMP_DISTRIB_CONFORMMAX     1615
#define IDC_COMP_DISTRIB_CONFORMMAX_SPIN 1616
#define IDC_COMP_DISTRIB_OFFSETMIN      1617
#define IDC_COMP_DISTRIB_SEED           1617
#define IDC_COMP_DISTRIB_OFFSETMIN_SPIN 1618
#define IDC_COMP_CLUST_AUTOEXPORT       1618
#define IDC_COMP_DISTRIB_OFFSETMAX      1619
#define IDC_COMP_DISTRIB_SEED_SPIN      1619
#define IDC_COMP_CLUST_AUTOINSTANCE     1619
#define IDC_COMP_DISTRIB_OFFSETMAX_SPIN 1620
#define IDC_DETECTOR                    1621
#define IDC_COMP_DISTRIB_CONFORMTYPE    1621
#define IDC_GUI_ANIMATE                 1622
#define IDC_GUI_ADDCHECK                1622
#define IDC_GUI_DELCHECK                1623
#define IDC_GUI_MOUSEOVERANIM           1623
#define IDC_GUI_CHECKLIST               1624
#define IDC_GUI_MDOWNSND                1624
#define IDC_COMP_DISTRIB_FACENORMALS    1625
#define IDC_GUI_MUPSND                  1625
#define IDC_COMP_LODFADE_HASBASE        1626
#define IDC_GUI_MOVERSND                1626
#define IDC_COMP_LODFADE_BASE           1627
#define IDC_GUI_MOFFSND                 1627
#define IDC_COMP_LODFADE_DISTANCE       1628
#define IDC_COMP_LODFADE_DISTANCE_SPIN  1629
#define IDC_COMP_LODFADE_TRANSITION     1630
#define IDC_COMP_FADEOUTTIME            1630
#define IDC_COMP_LODFADE_TRANSITION_SPIN 1631
#define IDC_COMP_FADEOUTTIME_SPIN       1631
#define IDC_COMP_LODFADE_FADEBASE       1632
#define IDC_COMP_LODFADE_BASEFIRST      1633
#define IDC_GUI_PICKMAT                 1634
#define IDC_DELAY_EDIT                  1635
#define IDC_DELAY_SPIN                  1636
#define IDC_MTL_LIST                    1637
#define IDC_GUI_REVERSE                 1638
#define IDC_CLOTHING_LIST               1639
#define IDC_CLOTHING_ADD                1640
#define IDC_GUI_TRIGGERONUP             1640
#define IDC_CLOTHING_REMOVE             1641
#define IDC_GUI_ALLOWNONE               1642
#define IDC_GUI_DEFSEL                  1643
#define IDC_GUI_DEFSEL_SPIN             1644
#define IDC_GUI_VERSION                 1645
#define IDC_GUI_VERSION_SPIN            1646
#define IDC_ANIM_NAME                   1647
#define IDC_LOOP_FOREVER                1648
#define IDC_FORWARD_COMBO               1649
#define IDC_BACKWARD                    1650
#define IDC_DO_ADVANCE_TO               1651
#define IDC_GLOBAL_COORD                1652
#define IDC_NUM_LOOPS_EDIT              1653
#define IDC_NUM_LOOPS_SPIN              1654
#define IDC_REGRESS                     1655
#define IDC_ADD                         1656
#define IDC_ADVANCE                     1656
#define IDC_REMOVE                      1657
#define IDC_ADVANCE_STAGE_EDIT          1657
#define IDC_FREEZE_PHYS                 1658
#define IDC_ADVANCE_STAGE_SPIN          1658
#define IDC_REGRESS_STAGE_EDIT          1659
#define IDC_MULTI_REVERSE_CTL           1659
#define IDC_STAGE_LIST                  1660
#define IDC_REGRESS_STAGE_SPIN          1660
#define IDC_CHECK_ENTER                 1661
#define IDC_CHECK_LOOP                  1662
#define IDC_CHECK_ADVANCE               1663
#define IDC_CHECK_REGRESS               1664
#define IDC_COMP_BLENDONTO_SORTFACES    1665
#define IDC_DO_REGRESS_TO               1665
#define IDC_GUI_FONTBOLD                1666
#define IDC_GUI_FONTITALIC              1667
#define IDC_GUI_FGCOLOR                 1668
#define IDC_GUI_USEALPHAS               1669
#define IDC_GUI_FONTFACE                1670
#define IDC_GUI_FONTSIZE_SPIN           1671
#define IDC_GUI_FGALPHA                 1672
#define IDC_GUI_SCHEMEPREV              1673
#define IDC_COMP_GEO_DICE_MAXFACES      1674
#define IDC_COMP_GEO_DICE_MAXFACES_SPIN 1675
#define IDC_COMP_GEO_DICE_MAXSIZE       1676
#define IDC_COMP_GEO_DICE_MAXSIZE_SPIN  1677
#define IDC_COMP_GEO_DICE_MINFACES      1678
#define IDC_COMP_GEO_DICE_MINFACES_SPIN 1679
#define IDC_COMP_GEO_DICE_ACTIVE        1680
#define IDC_GUI_FONTSHADOWED            1681
#define IDC_COMP_GEO_DICE_OVERRIDE      1681
#define IDC_COMP_AVATAR_CLOTHING_GROUP  1682
#define IDC_COMP_AVATAR_SKELETON        1683
#define IDC_COMP_SMOOTH_ANGLE           1684
#define IDC_COMP_SMOOTH_ANGLE_SPIN      1685
#define IDC_COMP_PARTICLE_WIND_SCALEX   1686
#define IDC_COMP_SMOOTHAV_ANGLE         1686
#define IDC_COMP_PARTICLE_WIND_SCALEX_SPIN 1687
#define IDC_COMP_SMOOTHAV_ANGLE_SPIN    1687
#define IDC_COMP_PARTICLE_WIND_SCALEY   1688
#define IDC_CHECK_CHILDREN              1688
#define IDC_COMP_PARTICLE_WIND_SCALEY_SPIN 1689
#define IDC_CHECK_TRIGGER               1689
#define IDC_COMP_PARTICLE_WIND_SCALEZ   1690
#define IDC_CHECK_UNTRIGGER             1690
#define IDC_COMP_PARTICLE_WIND_SCALEZ_SPIN 1691
#define IDC_COMP_PARTICLE_WIND_SPEED    1692
#define IDC_EVENT_LIST                  1692
#define IDC_COMP_PARTICLE_WIND_SPEED_SPIN 1693
#define IDC_COMP_PARTICLE_WIND_STRENGTH 1694
#define IDC_COMP_PARTICLE_VOL_DEFAULT   1694
#define IDC_NODE_LIST                   1694
#define IDC_COMP_PARTICLE_WIND_STRENGTH_SPIN 1695
#define IDC_COMP_PARTICLE_VOL_DIE       1696
#define IDC_COMP_PARTICLE_WIND_CONSTANCY 1696
#define IDC_COMP_PARTICLE_VOL_BOUNCE    1697
#define IDC_COMP_PARTICLE_WIND_CONSTANCY_SPIN 1697
#define IDC_COMP_PARTICLE_VOL_BOUNCEAMT 1698
#define IDC_COMP_PARTICLE_WIND_SWIRL    1698
#define IDC_COMP_PARTICLE_VOL_BOUNCEAMT_SPIN 1699
#define IDC_COMP_PARTICLE_WIND_SWIRL_SPIN 1699
#define IDC_COMP_PARTICLE_VOL_FRICTIONAMT 1700
#define IDC_COMP_PARTICLE_WIND_MINSECS  1700
#define IDC_COMP_PARTICLE_WIND_CLAMPANG 1700
#define IDC_COMP_BLENDONTOADV_SORTFACES 1701
#define IDC_COMP_PARTICLE_WIND_MINSECS_SPIN 1701
#define IDC_COMP_PARTICLE_WIND_CLAMPANG_SPIN 1701
#define IDC_COMP_PARTICLE_VOL_FRICTIONAMT_SPIN 1702
#define IDC_COMP_PARTICLE_WIND_MAXSECS  1702
#define IDC_COMP_BLENDONTOADV_SORTOBJECTS 1703
#define IDC_COMP_PARTICLE_WIND_MAXSECS_SPIN 1703
#define IDC_COMP_BLENDONTOADV_ONTOBLENDING 1704
#define IDC_COMP_PARTICLE_WIND_RATE     1704
#define IDC_ROOM_SEQEDIT                1705
#define IDC_COMP_PARTICLE_WIND_RATE_SPIN 1705
#define IDC_ROOM_SEQSPIN                1706
#define IDC_COMP_PARTICLE_WIND_CLAMPANG2 1706
#define IDC_CHASSIS                     1707
#define IDC_COMP_PARTICLE_WIND_HORIZONTAL 1707
#define IDC_FL_WHEEL                    1708
#define IDC_COMP_PARTICLE_WIND_CLAMPANG_SPIN2 1708
#define IDC_FR_WHEEL                    1709
#define IDC_RL_WHEEL                    1710
#define IDC_RR_WHEEL                    1711
#define IDC_FL_HARDPOINT                1712
#define IDC_FR_HARDPOINT                1713
#define IDC_RL_HARDPOINT                1714
#define IDC_RR_HARDPOINT                1715
#define IDC_COMP_DISTFADE_OUT_ACTIVE    1716
#define IDC_COMP_DISTFADE_OUTSTART      1717
#define IDC_COMP_LOD_CLOTHING_STATE     1717
#define IDC_COMP_DISTFADE_OUTSTART_SPIN 1718
#define IDC_COMP_LOD_CLOTHING_MESH_PICKB 1718
#define IDC_COMP_DISTFADE_OUTEND        1719
#define IDC_COMP_DISTFADE_OUTEND_SPIN   1720
#define IDC_COMP_DISTFADE_INSTART       1721
#define IDC_COMP_DISTFADE_INSTART_SPIN  1722
#define IDC_COMP_DISTFADE_INEND         1723
#define IDC_COMP_DISTFADE_INEND_SPIN    1724
#define IDC_JUSTIFYRADIO                1725
#define IDC_JUSTRADIO2                  1726
#define IDC_ORIENTATION_RADIO           1726
#define IDC_JUSTRADIO3                  1727
#define IDC_ORIENTATION_RADIO2          1727
#define IDC_GUI_MOUSEMAPREL             1728
#define IDC_GUI_MOUSEMAPANIM            1729
#define IDC_RADIO_FORCE_ON              1729
#define IDC_GUI_MOUSEMAPSCRN            1730
#define IDC_RADIO_FORCE_OFF             1730
#define IDC_COMP_SHADOW_LIGHT_FALLOFF   1731
#define IDC_COMP_SHADOW_LIGHT_FALLOFF_SPIN 1732
#define IDC_COMP_SHADOW_LIGHT_MAXDIST   1733
#define IDC_SND_CHANSRC1                1733
#define IDC_COMP_SHADOW_LIGHT_MAXDIST_SPIN 1734
#define IDC_SND_CHANSRC2                1734
#define IDC_COMP_SHADOW_LIGHT_POWER     1735
#define IDC_COMP_SHADOW_LIGHT_POWER_SPIN 1736
#define IDC_COMP_SHADOW_LIGHT_SHADOWONLY 1737
#define IDC_COMP_SHADOW_LIGHT_OBEYGROUPS 1738
#define IDC_COMP_SHADOW_LIGHT_SELFSHADOW 1739
#define IDC_SND_ISSTEREO_HIDDEN         1749
#define IDC_COMP_SHADOW_CAST_SELFSHADOW 1752
#define IDC_SND_PRIORITY                1752
#define IDC_COMP_PHYS_SUBW_EDIT1        1753
#define IDC_SND_PRIORITY_SPIN           1753
#define IDC_COMP_SHADOW_CAST_BLUR       1753
#define IDC_COMP_PHYS_SUBW_EDIT2        1754
#define IDC_COMP_SHADOW_CAST_ATTEN      1754
#define IDC_COMP_PHYS_SUBW_EDIT3        1755
#define IDC_COMP_SHADOW_CAST_LIMIT      1755
#define IDC_SND_LOCALONLY               1756
#define IDC_SND_CATEGORY                1758
#define IDC_COMP_LIGHTMAP_COMPRESS      1759
#define IDC_COMP_LIGHTMAP_SHARED        1760
#define IDC_COMP_RS_USEALL              1760
#define IDC_COMP_RS_GROUPLIST           1761
#define IDC_COMP_RS_GROUP_ADD           1762
#define IDC_COMP_RS_GROUP_REMOVE        1763
#define IDC_COMP_RS_GROUP_SPIN          1764
#define IDC_COMP_RS_GROUP               1765
#define IDC_COMP_FOOTSTEP_SOUND_SURFACE 1766
#define IDC_COMP_FOOTSTEP_SOUND_PICK    1767
#define IDC_COMP_RESPOND_FOOT_SURFACE   1768
#define IDC_PYTHON_GLOBAL               1769
#define IDC_EAX_PRESET                  1770
#define IDC_EAX_CUSTOM                  1771
#define IDC_EAX_CUSTFILE                1772
#define IDC_EAX_PRESET_COMBO            1773
#define IDC_EAX_SOFTREGION              1774
#define IDC_EAX_ENABLE                  1775
#define IDC_EAX_ROOMAUTO                1776
#define IDC_EAX_ROOMHFAUTO              1777
#define IDC_EAX_ROOMHF                  1778
#define IDC_EAX_ROOMHF_EDIT             1779
#define IDC_EAX_ROOM                    1780
#define IDC_EAX_ROOM_EDIT               1781
#define IDC_EAX_OUTSIDEVOLHF            1782
#define IDC_SND_TRACKVIEW               1782
#define IDC_EAX_OUTSIDEVOLHF_EDIT       1783
#define IDC_EAX_AIRABSORPTFACT          1784
#define IDC_COMP_FP_WIDTH               1784
#define IDC_EAX_AIRABSORPTFACT_EDIT     1785
#define IDC_COMP_FP_WIDTH_SPIN          1785
#define IDC_EAX_ROOMROLLOFFFACT         1786
#define IDC_COMP_FP_LENGTH              1786
#define IDC_TRIGGER_ON_FACING_CHECK     1786
#define IDC_EAX_ROOMROLLOFFFACT_EDIT    1787
#define IDC_COMP_FP_LENGTH_SPIN         1787
#define IDC_WALKING_FORWARD_CHECK       1787
#define IDC_EAX_DOPPLERFACT             1788
#define IDC_COMP_FP_INTENSITY           1788
#define IDC_EAX_DOPPLERFACT_EDIT        1789
#define IDC_COMP_FP_INTENSITY_SPIN      1789
#define IDC_EAX_ROLLOFFFACT             1790
#define IDC_EAX_ROLLOFFFACT_EDIT        1791
#define IDC_COMP_FP_LIFESPAN2           1792
#define IDC_EAX_ENABLEOCCLUSION         1792
#define IDC_COMP_FP_LIFESPAN_SPIN2      1793
#define IDC_EAX_STARTOCC                1793
#define IDC_EAX_ENDOCC                  1794
#define IDC_COMP_FP_DIRTYTIME           1794
#define IDC_COMP_FP_SCALE               1794
#define IDC_EAX_OCCLUSION               1795
#define IDC_COMP_FP_DIRTYTIME_SPIN      1795
#define IDC_COMP_FP_SCALE_SPIN          1795
#define IDC_EAX_OCCLUSION_EDIT          1796
#define IDC_RADIO_ALPHA                 1796
#define IDC_EAX_OCCLFRATIO              1797
#define IDC_RADIO_MADD                  1797
#define IDC_EAX_OCCLFRATIO_EDIT         1798
#define IDC_RADIO_ADD                   1798
#define IDC_EAX_OCCROOMRATIO            1799
#define IDC_RADIO_MULT                  1799
#define IDC_EAX_OCCROOMRATIO_EDIT       1800
#define IDC_COMP_FP_TEXMAP              1800
#define IDC_EAX_OCCDIRECTRATIO          1801
#define IDC_COMP_FP_PARTYTIME           1801
#define IDC_EAX_OCCDIRECTRATIO_EDIT     1802
#define IDC_COMP_FP_PARTYTIME_SPIN      1802
#define IDC_EAX_OCCREGION               1803
#define IDC_EAX_OCCPRESET               1804
#define IDC_ADD_DECAL                   1805
#define IDC_COMP_WIDTH                  1806
#define IDC_COMP_WIDTH_SPIN             1807
#define IDC_COMP_LENGTH                 1808
#define IDC_ADD_NOTIFY                  1808
#define IDC_COMP_LENGTH_SPIN            1809
#define IDC_ADD_PARTICLE                1809
#define IDC_COMP_HEIGHT                 1810
#define IDC_COMP_HEIGHT_SPIN            1811
#define IDC_ADD_NOTIFY2                 1812
#define IDC_DETECT_LOCAL_CHECK          1814
#define IDC_LINKNAMELABEL               1815
#define IDC_CHECK_SKIPFFSOUND           1815
#define IDC_NPC_SPAWN_MODEL_TEXT_BOX    1816
#define IDC_NPC_SPAWN_ACCOUNT_TEXT_BOX  1817
#define IDC_NPC_SPAWN_AUTOSPAWN_BOOL    1818
#define IDC_COMP_LOD_AVATAR_BONELIST    1819
#define IDC_COMP_LOD_AVATAR_BONE_ADD    1820
#define IDC_COMP_LOD_AVATAR_BONE_REMOVE 1821
#define IDC_COMP_LOD_AVATAR_GROUP       1822
#define IDC_COMP_LOD_AVATAR_GROUP_SPIN  1823
#define IDC_CLOTHING_CLEARMESH          1824
#define IDC_GUI_BETTERHIT               1828
#define IDC_RAND_COMBINESOUNDS          1829
#define IDC_PH_NO_SYNC_CHK              1830
#define IDC_PH_INACTIVE_CHK             1831
#define IDC_COMP_FILTER_NOX             1832
#define IDC_PH_AVANIMPUSHABLE           1832
#define IDC_COMP_FILTER_NOY             1833
#define IDC_COMP_FILTER_NOZ             1834
#define IDC_SMARTSEEK                   1835
#define IDC_COMP_STEREIZE_LEFT          1836
#define IDC_COMP_STEREIZE_AMB           1837
#define IDC_COMP_STEREIZE_AMB_SPIN      1838
#define IDC_COMP_STEREIZE_TRANS         1839
#define IDC_COMP_STEREIZE_TRANS_SPIN    1840
#define IDC_COMP_STEREIZE_ANG           1841
#define IDC_COMP_STEREIZE_ANG_SPIN      1842
#define IDC_COMP_STEREIZE_MAXDIST       1843
#define IDC_COMP_STEREIZE_MAXDIST_SPIN  1844
#define IDC_COMP_STEREIZE_MINDIST       1845
#define IDC_COMP_STEREIZE_MINDIST_SPIN  1846
#define IDC_COMP_CLIMB_COMMAND          1847
#define IDC_COMP_CLIMB_DIRECTION        1848
#define IDC_COMP_WALL_PICK              1849
#define IDC_CAMERA_VEL_SPIN             1850
#define IDC_CAMERA_DECEL                1851
#define IDC_CAMERA_DECEL_SPIN           1852
#define IDC_CAMERA_ACCEL2               1853
#define IDC_CAMERA_ACCEL_SPIN2          1854
#define IDC_CAMERA_VEL2                 1855
#define IDC_CAMERA_VEL_SPIN2            1856
#define IDC_CAMERA_DECEL2               1857
#define IDC_CAMERA_DECEL_SPIN2          1858
#define IDC_CAMERA_ACCEL                1859
#define IDC_CAMERA_ACCEL_SPIN           1860
#define IDC_CAMERA_VEL                  1861
#define IDC_VER_TEXT                    1862
#define IDC_CHECK_IGNORE                1863
#define IDC_RADIO_PLAYER                1864
#define IDC_COMP_CHOOSE_OBJECT          1865
#define IDC_COMP_OFFSETACTIVE           1870
#define IDC_COMP_OFFSETX                1871
#define IDC_COMP_OFFSETX_SPIN           1872
#define IDC_COMP_OFFSETY                1873
#define IDC_BODY_UNKNOWN                1873
#define IDC_DRIVE                       1873
#define IDC_COMP_OFFSETY_SPIN           1874
#define IDC_BODY_UPPER                  1874
#define IDC_COMP_OFFSETZ                1875
#define IDC_BODY_FULL                   1875
#define IDC_COMP_OFFSETZ_SPIN           1876
#define IDC_COMP_OFFSETLOCAL            1877
#define IDC_FADE_IN                     1877
#define IDC_COMP_PIVOTY                 1878
#define IDC_FADE_OUT                    1878
#define IDC_EMO_FADEIN                  1879
#define IDC_EMO_FADEIN_SPIN             1880
#define IDC_EMO_FADEOUT_SPIN            1881
#define IDC_EMO_FADEOUT                 1882
#define IDC_COMP_W_GEO_MINLEN           1883
#define IDC_COMP_W_GEO_MINLEN_SPIN      1884
#define IDC_COMP_W_ZEROOPAC             1885
#define IDC_COMP_W_GEO_MAXLEN           1885
#define IDC_COMP_W_ZEROOPAC_SPIN        1886
#define IDC_COMP_W_GEO_MAXLEN_SPIN      1886
#define IDC_COMP_W_DEPTHOPAC            1887
#define IDC_COMP_W_SHORETINT            1887
#define IDC_COMP_W_DEPTHOPAC_SPIN       1888
#define IDC_COMP_W_SHOREOPAC            1888
#define IDC_COMP_W_ZEROREFL             1889
#define IDC_COMP_W_SHOREOPAC_SPIN       1889
#define IDC_COMP_W_GEO_AMPOVERLEN       1889
#define IDC_COMP_W_ZEROREFL_SPIN        1890
#define IDC_COMP_W_WISPINESS            1890
#define IDC_COMP_W_FINGER               1890
#define IDC_COMP_W_GEO_AMPOVERLEN_SPIN  1890
#define IDC_COMP_W_DEPTHREFL            1891
#define IDC_COMP_W_WISPINESS_SPIN       1891
#define IDC_COMP_W_FINGER_SPIN          1891
#define IDC_COMP_W_GEO_CHOP             1891
#define IDC_COMP_W_DEPTHREFL_SPIN       1892
#define IDC_COMP_W_PERIOD               1892
#define IDC_COMP_W_REFOBJECT            1892
#define IDC_COMP_W_GEO_CHOP_SPIN        1892
#define IDC_COMP_W_ZEROWAVE             1893
#define IDC_COMP_W_PERIOD_SPIN          1893
#define IDC_COMP_SHORE_CHOSE            1893
#define IDC_COMP_W_GEO_ANGLEDEV         1893
#define IDC_COMP_W_ZEROWAVE_SPIN        1894
#define IDC_COMP_W_ENVOBJECT            1894
#define IDC_COMP_W_EDGEOPAC             1894
#define IDC_COMP_W_GEO_ANGLEDEV_SPIN    1894
#define IDC_COMP_W_DEPTHWAVE            1895
#define IDC_COMP_W_ENVSIZE              1895
#define IDC_COMP_W_EDGEOPAC_SPIN        1895
#define IDC_COMP_W_GEO_SPECMUTE         1895
#define IDC_COMP_W_DEPTHWAVE_SPIN       1896
#define IDC_COMP_W_ENVSIZE_SPIN         1896
#define IDC_COMP_W_EDGERADIUS           1896
#define IDC_COMP_W_GEO_SPECMUTE_SPIN    1896
#define IDC_COMP_W_ENVRADIUS            1897
#define IDC_COMP_W_EDGERADIUS_SPIN      1897
#define IDC_COMP_W_ENVRADIUS_SPIN       1898
#define IDC_AGELINKSPAWNPTLABEL         1899
#define IDC_COMP_W_ENVREFRESH           1899
#define IDC_RADIO_BROKEN                1900
#define IDC_COMP_W_ENVREFRESH_SPIN      1900
#define IDC_AGELINKSPAWNPTTITLE         1900
#define IDC_RADIO_CALIBRATED            1901
#define IDC_AGELINKSPAWNPTTITLE2        1901
#define IDC_RADIO_REPAIRED              1902
#define IDC_AGELINKSPAWNPTTITLE3        1902
#define IDC_GUI_REPORTDRAG              1903
#define IDC_GUI_HIDECURSOR              1904
#define IDC_GUI_USEDRAGCHILD            1904
#define IDC_GUI_SNAPSTART               1905
#define IDC_COMP_NOSHOW_SHOWABLE        1905
#define IDC_COMP_VISREGION_CHOOSE_VOLUME 1906
#define IDC_COMP_VISREGION_DRAW         1907
#define IDC_COMP_VISREGION_LIGHT        1908
#define IDC_COMP_VISREGION_OCC          1909
#define IDC_COMP_NOSHOW_AFFECTPHYS      1909
#define IDC_COMP_NOSHOW_AFFECTDRAW      1910
#define IDC_COMP_VISREGION_NOT          1910
#define IDC_COMP_SMOOTHAV_DIST          1911
#define IDC_COMP_VISREGION_DIS          1911
#define IDC_COMP_SMOOTHAV_DIST_SPIN     1912
#define IDC_GUI_ELEMENTS                1913
#define IDC_GUI_HORZSCROLL              1914
#define IDC_GUI_VERTSCROLL              1915
#define IDC_GUI_INFO                    1916
#define IDC_GUI_PREVIEW                 1917
#define IDC_GUI_EDITELEM                1918
#define IDC_GUI_ZIN                     1919
#define IDC_GUI_IMARGIN                 1920
#define IDC_GUI_IMARGIN_SPIN            1921
#define IDC_GUI_BMARGIN                 1922
#define IDC_GUI_BMARGIN_SPIN            1923
#define IDC_GUI_SKIN                    1924
#define IDC_GUI_NEVERCLOSE              1925
#define IDC_GUI_MODALOUTSIDE            1926
#define IDC_GUI_HOVER                   1927
#define IDC_ALIGNRADIO1                 1929
#define IDC_ALIGNRADIO2                 1930
#define IDC_COMP_WDECAL_CHOSE           1930
#define IDC_ALIGNRADIO3                 1931
#define IDC_BEGINONPUSH                 1931
#define IDC_ALIGNRADIO4                 1932
#define IDC_STOPONPOP                   1932
#define IDC_RESETONPOP                  1933
#define IDC_COMP_SMOOTHAV_POS           1934
#define IDC_COMP_SMOOTH_POS             1935
#define IDC_COMP_SMOOTH_COLOR           1936
#define IDC_LOCAL_ONLY_CHECK            1936
#define IDC_OVERRIDE_CHECK              1939
#define IDC_PHYS_ALLOW_RADIO            1943
#define IDC_PHYS_NOSAVE_RADIO           1944
#define IDC_PHYS_DENY_RADIO             1945
#define IDC_ANIM_ALLOW_RADIO            1946
#define IDC_ANIM_NOSAVE_RADIO           1947
#define IDC_ANIM_DENY_RADIO             1948
#define IDC_SND_ALLOW_RADIO             1949
#define IDC_SND_NOSAVE_RADIO            1950
#define IDC_SND_DENY_RADIO              1951
#define IDC_MAT_ALLOW_RADIO             1952
#define IDC_MAT_NOSAVE_RADIO            1953
#define IDC_MAT_DENY_RADIO              1954
#define IDC_RESP_ALLOW_RADIO            1955
#define IDC_RESP_NOSAVE_RADIO           1956
#define IDC_RESP_DENY_RADIO             1957
#define IDC_XREG_ALLOW_RADIO            1958
#define IDC_XREG_NOSAVE_RADIO           1959
#define IDC_XREG_DENY_RADIO             1960
#define IDC_COMP_LOD_AVATAR_MTL         1961
#define IDC_SIT_APP_FRONT               1962
#define IDC_COMP_RELREGION_CHOOSE_VOLUME 1963
#define IDC_COMP_SHADOW_CAST_BLURSCALE  1967
#define IDC_COMP_SHADOW_CAST_BLURSCALE_SPIN 1968
#define IDC_COMP_SHADOW_CAST_ATTENSCALE 1969
#define IDC_COMP_REPRESENT_QUALITY      1969
#define IDC_COMP_SHADOW_CAST_ATTENSCALE_SPIN 1970
#define IDC_ADD_REPS                    1970
#define IDC_COMP_SHADOW_CAST_BOOST      1971
#define IDC_LIST_REPS                   1971
#define IDC_COMP_SHADOW_CAST_BOOST_SPIN 1972
#define IDC_DEL_REPS                    1972
#define IDC_COMP_WDECAL_ENV             1973
#define IDC_COMP_SHADOW_QUALITY         1973
#define IDC_SECT_LIST                   1974
#define IDC_STIFFNESS_EDIT              1975
#define IDC_UP_BUTTON                   1976
#define IDC_DN_BUTTON                   1977
#define IDC_STRENGTH_EDIT               1978
#define IDC_DEF_STR_BUTTON              1979
#define IDC_COMP_SMOOTHBASE_DIST        1980
#define IDC_COMP_SMOOTHBASE_DIST_SPIN   1981
#define IDC_COMP_SMOOTHBASE_ANGLE       1982
#define IDC_COMP_SMOOTHBASE_ANGLE_SPIN  1983
#define IDC_COMP_SMOOTHBASE_POS         1984
#define IDC_COMP_SMOOTHSNAP_DIST        1985
#define IDC_COMP_SMOOTHSNAP_DIST_SPIN   1986
#define IDC_COMP_SMOOTHSNAP_ANGLE       1987
#define IDC_COMP_SMOOTHSNAP_ANGLE_SPIN  1988
#define IDC_COMP_SMOOTHSNAP_POS         1989
#define IDC_COMP_SMOOTH_CHOSE           1990
#define IDC_IMAGE_LIST                  1991
#define IDC_IMAGE_ADD                   1992
#define IDC_IMAGE_REMOVE                1993
#define IDC_IMAGE_EDIT                  1994
#define IDC_IL_COMPRESS                 1995
#define IDC_IL_FORCEPOW2                1996
#define IDC_SND_INCIDENTAL              1997
#define IDC_COMP_PARTICLE_WIND_REFOBJECT 1998
#define IDC_FLOCK_TARGET_OFFSETX        2001
#define IDC_FLOCK_TARGET_OFFSETX_SPIN   2002
#define IDC_FLOCK_TARGET_OFFSETY        2003
#define IDC_FLOCK_TARGET_OFFSETZ        2004
#define IDC_FLOCK_TARGET_OFFSETY_SPIN   2005
#define IDC_FLOCK_TARGET_OFFSETZ_SPIN   2006
#define IDC_COMP_EFFVISSET_HIDENORMAL   2007
#define IDC_COMP_ENVMAP_YON             2008
#define IDC_COMP_ENVMAP_YON_SPIN        2009
#define IDC_COMP_ENVMAP_REFRESHRATE     2010
#define IDC_COMP_ENVMAP_REFRESHRATE_SPIN 2011
#define IDC_COMP_ENVMAP_ENVSIZE         2012
#define IDC_COMP_ENVMAP_ENVSIZE_SPIN    2013
#define IDC_COMP_ENVMAP_INCCHARS        2014
#define IDC_COMP_W_TEX_MINLEN           2015
#define IDC_COMP_ENVMAP_FOGSTART        2015
#define IDC_COMP_W_TEX_MINLEN_SPIN      2016
#define IDC_COMP_ENVMAP_FOGSTART_SPIN   2016
#define IDC_COMP_W_TEX_MAXLEN           2017
#define IDC_COMP_W_TEX_MAXLEN_SPIN      2018
#define IDC_COMP_W_TEX_AMPOVERLEN       2019
#define IDC_COMP_W_TEX_AMPOVERLEN_SPIN  2020
#define IDC_COMP_W_TEX_CHOP             2021
#define IDC_COMP_W_TEX_CHOP_SPIN        2022
#define IDC_COMP_W_TEX_NOISE            2023
#define IDC_COMP_W_TEX_NOISE_SPIN       2024
#define IDC_STATIC_BUTTON_NOTIFY        2024
#define IDC_COMP_W_TEX_RIPPLESCALE      2025
#define IDC_COMBO_BUTTON_NOTIFYTYPE     2025
#define IDC_COMP_W_TEX_RIPPLESCALE_SPIN 2026
#define IDC_COMP_W_TEX_ANGLEDEV         2027
#define IDC_COMP_W_TEX_ANGLEDEV_SPIN    2028
#define IDC_COMP_W_TEX_SPECSTART        2029
#define IDC_COMP_W_TEX_SPECSTART_SPIN   2030
#define IDC_COMP_W_TEX_SPECEND          2031
#define IDC_COMP_W_TEX_SPECEND_SPIN     2032
#define IDC_SND_GROUP                   2033
#define IDC_SND_AGAINST                 2034
#define IDC_SND_IMPACT                  2035
#define IDC_SND_CLEAR_IMPACT            2036
#define IDC_SND_SLIDE                   2037
#define IDC_SND_CLEAR_SLIDE             2038
#define IDC_GUI_LANGUAGE                2039
#define IDC_COMP_PANIC_ANIM             2041
#define IDC_RADIO_THIRD                 2042
#define IDC_RADIO_FIRST                 2043
#define IDC_CHECK_STREAM                2044
#define IDC_CAMERA_LOS                  2045
#define IDC_IGNOREFOV                   2047
#define IDC_COMP_W_SPECULARTINT         2048
#define IDC_RADIO_ENTER                 2049
#define IDC_RADIO_EXIT                  2050
#define IDC_COLLIDABLE_CHECK            2051
#define IDC_MARKER_PHYS                 2052
#define IDC_ANIM_RED_COMBO              2053
#define IDC_SWIM_CURRENT_NONE           2054
#define IDC_COMP_BOUNDSCENTER           2054
#define IDC_SWIM_CURRENT_SPIRAL         2055
#define IDC_COMP_FADEINTIME             2055
#define IDC_SWIM_CURRENT_ROTATION       2056
#define IDC_COMP_FADEINTIME_SPIN        2056
#define IDC_SWIM_CURRENT_ROTATION_SPIN  2057
#define IDC_COMP_GZ_OPAQUE              2057
#define IDC_SWIM_CURRENT_PULL           2058
#define IDC_COMP_GZ_OPAQUE_SPIN         2058
#define IDC_SWIM_CURRENT_PULL_NEAR_DIST 2058
#define IDC_SWIM_CURRENT_PULL_SPIN      2059
#define IDC_COMP_GZ_TRANSP              2059
#define IDC_SWIM_CURRENT_PULL_NEAR_DIST_SPIN 2059
#define IDC_COMP_GZ_TRANSP_SPIN         2060
#define IDC_SWIM_DETECTOR_NODE          2060
#define IDC_SWIM_CURRENT_NODE           2061
#define IDC_SUBWORLD_ENTER              2061
#define IDC_SUBWORLD_EXIT               2062
#define IDC_SWIM_CURRENT_PULL_FAR_VEL   2062
#define IDC_COMP_ENVMAP_FOGCOLOR        2063
#define IDC_SWIM_CURRENT_PULL_FAR_VEL_SPIN 2063
#define IDC_SWIM_BUOYANCY_UP            2064
#define IDC_GUI_ANIMSND                 2064
#define IDC_SWIM_BUOYANCY_UP_SPIN       2065
#define IDC_GUI_USE_LOCALIZATION        2065
#define IDC_SWIM_MAX_UP_VEL             2066
#define IDC_GUI_LOCALIZATION_PATH       2066
#define IDC_SWIM_MAX_UP_VEL_SPIN        2067
#define IDC_GUI_SELECT_LOC_PATH         2067
#define IDC_SWIM_BUOYANCY_DOWN          2068
#define IDC_LOCALIZATIONTREE            2068
#define IDC_SWIM_BUOYANCY_DOWN_SPIN     2069
#define IDC_EDIT1                       2069
#define IDC_LOCALIZATIONSTRING          2069
#define IDC_BODYAGENAME_EDIT            2069
#define IDC_SWIM_CURRENT_PULL_NEAR_VEL  2070
#define IDC_OBJ_FLOCKER_USE_TARGET_ROTATION 2070
#define IDC_SWIM_CURRENT_PULL_NEAR_VEL_SPIN 2071
#define IDC_COMP_ANIM_COMPRESS_NONE     2071
#define IDC_SWIM_CURRENT_PULL_FAR_DIST  2072
#define IDC_COMP_ANIM_COMPRESS_LOW      2072
#define IDC_SWIM_CURRENT_PULL_FAR_DIST_SPIN 2073
#define IDC_COMP_ANIM_COMPRESS_HIGH     2073
#define IDC_SWIM_CURRENT_STRAIGHT       2074
#define IDC_COMP_ANIM_COMPRESS_THRESHOLD 2074
#define IDC_SWIM_CURRENT_STRAIGHT_NEAR_DIST 2075
#define IDC_COMP_ANIM_COMPRESS_THRESHOLD_SPIN 2075
#define IDC_SWIM_CURRENT_STRAIGHT_NEAR_DIST_SPIN 2076
#define IDC_PHYS_HEIGHT_EDIT            2076
#define IDC_SWIM_CURRENT_STRAIGHT_FAR_VEL 2077
#define IDC_PHYS_HEIGHT_SPIN            2077
#define IDC_SWIM_CURRENT_STRAIGHT_FAR_VEL_SPIN 2078
#define IDC_RADIO_BLOCK_AVATAR          2078
#define IDC_SWIM_CURRENT_STRAIGHT_NEAR_VEL 2079
#define IDC_IGNORE_REGION_CHECK         2079
#define IDC_SWIM_CURRENT_STRAIGHT_NEAR_VEL_SPIN 2080
#define IDC_BODYFOOTSTEPPAGE_EDIT       2080
#define IDC_SWIM_CURRENT_STRAIGHT_FAR_DIST 2081
#define IDC_ANIMATIONPREFIX_EDIT        2081
#define IDC_SWIM_CURRENT_STRAIGHT_FAR_DIST_SPIN 2082
#define IDC_STATIC_FRICTION_LABEL       2082
#define IDC_COMP_CLICKABLE_FRIC_EDIT1   2083
#define IDC_COMP_CLICKABLE_FRIC_SPIN1   2084
#define IDC_ARBITRATION_CHECK           2085
#define IDC_COMP_ENVMAP_ENVSIZ          2312
#define IDC_GRASS_DIR_X                 2854
#define IDC_GRASS_DIR_X_SPIN            2855
#define IDC_GRASS_DIR_Y                 2856
#define IDC_GRASS_DIR_Y_SPIN            2857
#define IDC_GRASS_DIST_X                2858
#define IDC_GRASS_DIST_X_SPIN           2859
#define IDC_GRASS_DIST_Y                2860
#define IDC_GRASS_DIST_Y_SPIN           2861
#define IDC_GRASS_DIST_Z                2862
#define IDC_GRASS_DIST_Z_SPIN           2863
#define IDC_GRASS_SPEED                 2864
#define IDC_GRASS_SPEED_SPIN            2865
#define IDC_GRASS_WAVE                  2866
#define IDC_OBJ_FLOCKER_BOID_BUTTON     3019
#define IDC_OBJ_FLOCKER_SEP_RADIUS      3022
#define IDC_OBJ_FLOCKER_SEP_RADIUS_SPIN 3023
#define IDC_OBJ_FLOCKER_SEP_STRENGTH    3024
#define IDC_OBJ_FLOCKER_SEP_STRENGTH_SPIN 3025
#define IDC_OBJ_FLOCKER_SLIMIT_MIN      3038
#define IDC_OBJ_FLOCKER_SLIMIT_MIN_SPIN 3039
#define IDC_OBJ_FLOCKER_HIDE_TARGET     3042
#define IDC_OBJ_FLOCKER_SLIMIT_MAX      3045
#define IDC_OBJ_FLOCKER_WANDER_STRENGTH 3046
#define IDC_OBJ_FLOCKER_WANDER_STRENGTH_SPIN 3047
#define IDC_OBJ_FLOCKER_GOAL_STRENGTH   3048
#define IDC_OBJ_FLOCKER_GOAL_STRENGTH_SPIN 3050
#define IDC_OBJ_FLOCKER_COH_RADIUS      3051
#define IDC_OBJ_FLOCKER_COH_RADIUS_SPIN 3052
#define IDC_OBJ_FLOCKER_COH_STRENGTH    3053
#define IDC_OBJ_FLOCKER_COH_STRENGTH_SPIN 3054
#define IDC_OBJ_FLOCKER_NUM_BOIDS       3055
#define IDC_OBJ_FLOCKER_NUM_BOIDS_SPIN  3056
#define IDC_OBJ_FLOCKER_RANDOM_ANIM_START 3057
#define IDC_OBJ_FLOCKER_MAX_FORCE       3063
#define IDC_OBJ_FLOCKER_MAX_FORCE_SPIN  3064
#define IDC_OBJ_FLOCKER_SLIMIT_MAX_SPIN 3066
#define IDC_GUI_SKINBMAP                3070
#define IDC_COMP_ENVMAP_CUBIC           3319
#define IDC_COMP_ENVMAP_SINGLE_CAM      3320
#define IDC_COMP_ENVMAP_REMOVE_STRING   3358
#define IDC_COMP_ENVMAP_ADD_STRING      3359
#define IDC_COMP_ENVMAP_ADD_STRING_BOX  3360
#define IDC_COMP_ENVMAP_NAMES_LISTBOX   3361

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        559
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         2086
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
