//{{NO_DEPENDENCIES}}
// Microsoft Developer Studio generated include file.
// Used by plRTLights.rc
//
#define IDS_PW_GRID                     1
#define IDD_SPHEREPARAM                 101
#define IDD_SPHEREPARAM2                101
#define IDB_SPINNER                     102
#define IDD_CYLINDERPARAM               102
#define IDD_CYLINDERPARAM2              102
#define IDC_SPINNERCUR                  103
#define IDD_BOXPARAM                    103
#define IDD_BOXPARAM2                   103
#define IDD_SHADOWMAP_PARAMS            103
#define IDD_WAVEPARAM                   104
#define IDD_SCAMERA                     105
#define IDD_SCAMERAPARAM                105
#define IDD_LIGHT_PARAM                 106
#define IDD_CYLINDERPARAM1              107
#define IDD_DIRLIGHTPARAM               108
#define IDD_DUMMY1                      109
#define IDD_DUMMY2                      110
#define IDD_DUMMY3                      111
#define IDD_DUMMY4                      112
#define IDD_SPHEREPARAM1                113
#define IDD_LIGHT_ANIM                  113
#define IDD_DUMMY5                      114
#define IDD_DUMMY6                      115
#define IDD_FSPOTLIGHTPARAM             116
#define IDD_SPOTLIGHT                   116
#define IDD_SPLINEPARAM                 117
#define IDD_SPLINEPARAM1                117
#define IDD_NGONPARAM2                  118
#define IDD_NGONPARAM1                  119
#define IDD_DONUTPARAM2                 120
#define IDD_DONUTPARAM1                 121
#define IDD_SAMPLEPARAM                 122
#define IDD_FCAMERAPARAM                123
#define IDD_PATCHGRIDPARAM              124
#define IDD_TRIPATCHPARAM               125
#define IDD_PSPHEREPARAM1               126
#define IDD_PSPHEREPARAM2               127
#define IDD_TORUSPARAM1                 128
#define IDB_HYBRIDKEYBUTTONS            128
#define IDD_TORUSPARAM2                 129
#define IDB_MASK_HYBRIDKEYBUTTONS       129
#define IDD_MORPHPARAM                  130
#define IDD_MORPHPARAM2                 130
#define IDD_MORPHPARAM1                 131
#define IDD_FREE_SPOTLIGHT              132
#define IDD_LIGHT_SHADOW                134
#define IDD_LIGHT_SHADOW3               134
#define IDD_RECTANGLEPARAM              135
#define IDD_BOOLPARAM1                  136
#define IDD_BOOLPARAM2                  137
#define IDD_TAPEHELPER                  138
#define IDD_SPHEREPARAM3                139
#define IDD_CYLINDERPARAM3              140
#define IDD_TORUSPARAM3                 141
#define IDD_TUBEPARAM1                  142
#define IDD_TUBEPARAM2                  143
#define IDD_TUBEPARAM3                  144
#define IDD_BOXPARAM1                   145
#define IDD_BOXPARAM3                   146
#define IDD_CONEPARAM1                  147
#define IDD_CONEPARAM2                  148
#define IDD_CONEPARAM3                  149
#define IDD_HEDRAPARAM                  150
#define IDD_HELIXPARAM1                 151
#define IDD_HELIXPARAM2                 152
#define IDB_TEXT_BUTTONS                152
#define IDD_DONUTPARAM3                 153
#define IDB_TEXT_MASKBUTTONS            153
#define IDD_NGONPARAM3                  154
#define IDB_FOV                         154
#define IDD_HELIXPARAM3                 156
#define IDC_CROSS_HAIR                  156
#define IDD_RECTANGLEPARAM3             157
#define IDD_RECTANGLEPARAM2             158
#define IDB_FOVMASK                     158
#define IDD_RECTANGLEPARAM1             159
#define IDB_CI_TORUS32_MASK             159
#define IDD_CIRCLEPARAM2                160
#define IDB_CI_SPHERE16_MASK            160
#define IDD_CIRCLEPARAM1                161
#define IDB_CI_SPHERE32                 161
#define IDD_ELLIPSEPARAM3               162
#define IDB_CI_SPHERE32_MASK            162
#define IDD_ELLIPSEPARAM2               163
#define IDB_CI_TEAPOT16                 163
#define IDD_ELLIPSEPARAM1               164
#define IDB_CI_TEAPOT16_MASK            164
#define IDD_CIRCLEPARAM3                165
#define IDB_CI_TEAPOT32                 165
#define IDD_ARCPARAM3                   166
#define IDB_CI_TEAPOT32_MASK            166
#define IDD_ARCPARAM2                   167
#define IDB_CI_TORUS16                  167
#define IDD_ARCPARAM1                   168
#define IDB_CI_TORUS16_MASK             168
#define IDD_RAINPARAM                   169
#define IDB_CI_TORUS32                  169
#define IDD_STARPARAM2                  170
#define IDB_CI_SPHERE16                 170
#define IDD_STARPARAM1                  171
#define IDD_SNOWPARAM                   172
#define IDD_TEXTPARAM                   173
#define IDD_INTERPPARAMS                174
#define IDD_SPLINEPARAM2                175
#define IDD_TEAPOTPARAM1                176
#define IDD_TEAPOTPARAM2                177
#define IDD_TEAPOTPARAM3                178
#define IDD_CUBICMORPH_KEYINFO          179
#define IDD_BARYMORPH_KEYINFO           180
#define IDD_OMNI                        181
#define IDD_BONEPARAMS                  182
#define IDD_BONEPARAMS_OLD              182
#define IDD_PATCHGRIDPARAM2             183
#define IDD_TRIPATCHPARAM2              184
#define IDD_PROTHELPER                  185
#define IDD_LIGHT_ATTEN                 186
#define IDD_PCAM_CUSTOM                 188
#define IDD_PCAM_STANDARD               190
#define IDD_LIGHT_SHADOW1               191
#define IDB_PUSHPIN                     192
#define IDD_GRIDPARAM3                  192
#define IDB_LOCK_ADJACENT               193
#define IDD_GRIDPARAM2                  193
#define IDD_GRIDPARAM1                  194
#define IDB_LOCK_SEPERATED              195
#define IDD_LIGHT_SHADOW2               195
#define IDD_LIGHT_EMITTER               196
#define IDD_PROJ_DIRECTIONAL            196
#define IDD_CAMERA_DOF                  197
#define IDB_SUBOBJTYPES                 198
#define IDD_BONEPARAMS_NEW              198
#define IDB_MASK_SUBOBJTYPES            199
#define IDD_NEWBONE                     199
#define IDC_RADIUS                      1000
#define IDC_SEGMENTS                    1001
#define IDC_AMPLITUDE                   1001
#define IDC_PARAM_P                     1001
#define IDC_TI_ARCFROM                  1001
#define IDC_BOOL_BNAME                  1001
#define IDC_CREATEDIAMETER              1002
#define IDC_CYCLES                      1002
#define IDC_HEMISPHERE                  1002
#define IDC_CAPSEGMENTS                 1002
#define IDC_PARAM_Q                     1002
#define IDC_TI_ARCTO                    1002
#define IDC_CREATERADIUS                1003
#define IDC_PHASE                       1003
#define IDC_SCALE_P                     1003
#define IDC_SEGSPINNER                  1004
#define IDC_NUMNODES                    1004
#define IDC_SCALE_Q                     1004
#define IDC_RADSPINNER                  1005
#define IDC_CAPSEGSPINNER               1005
#define IDC_OBSMOOTH                    1006
#define IDC_AMPSPINNER                  1006
#define IDC_PARAM_PSPIN                 1006
#define IDC_TI_ARCFROMSPINNER           1006
#define IDC_LENGTH                      1007
#define IDC_CYCSPINNER                  1007
#define IDC_HEMISPHERESPINNER           1007
#define IDC_PARAM_QSPIN                 1007
#define IDC_TI_ARCTOSPINNER             1007
#define IDC_LENSPINNER                  1008
#define IDC_PHSSPINNER                  1008
#define IDC_SCALE_PSPIN                 1008
#define IDC_SIDES                       1009
#define IDC_NUMSPINNER                  1009
#define IDC_SCALE_QSPIN                 1009
#define IDC_POINTS                      1009
#define IDC_SCALESPINNER                1009
#define IDC_SIDESPINNER                 1010
#define IDC_HEIGHT                      1010
#define IDC_HEIGHTEDIT                  1010
#define IDC_SCALE_R                     1010
#define IDC_POINTSSPINNER               1010
#define IDC_WIDTHSPINNER                1011
#define IDC_PIESLICESPIN1               1011
#define IDC_SCALE_RSPIN                 1011
#define IDC_DISTORTSPINNER              1011
#define IDC_HEIGHTSPINNER               1012
#define IDC_PIESLICESPIN2               1012
#define IDC_DISTORT                     1012
#define IDC_FILLETSPINNER               1012
#define IDC_BROWSE                      1013
#define IDC_HSEGSPIN                    1013
#define IDC_RADSPINNER2                 1013
#define IDC_CAPSEGSPIN                  1013
#define IDC_AP_FILLETSPINNER            1013
#define IDC_OBJFILENAME                 1014
#define IDC_HSEGS                       1014
#define IDC_FOV                         1015
#define IDC_WSEGSPIN                    1015
#define IDC_AP_FILLETSPINNER2           1015
#define IDC_FOVSPINNER                  1016
#define IDC_WSEGS                       1016
#define IDC_LRED                        1017
#define IDC_LSEGSPIN                    1017
#define IDC_FOVSPINNER2                 1017
#define IDC_LREDSPINNER                 1018
#define IDC_LSEGS                       1018
#define IDC_FOV2                        1018
#define IDC_PROT_PICK_TARGET1           1018
#define IDC_SHOWCAMCONE                 1019
#define IDC_PROT_PICK_TARGET2           1019
#define IDC_RENDERSEGSPINNER            1019
#define IDC_CHECK1                      1020
#define IDC_SHOW_CONE                   1020
#define IDC_BOOL_OPTIMIZE               1020
#define IDC_SHOWHORZLINE                1020
#define IDC_SPEC_LEN                    1020
#define IDC_HEMI_RECENTER               1020
#define IDC_SLICEON                     1020
#define IDC_ARCPIE                      1020
#define IDC_HIDE_EMITTER                1020
#define IDC_TEXT_MANUAL_UPDATE          1020
#define IDC_BONES_ASSIGNIK              1020
#define IDC_BONE_SIDEFINS               1020
#define IDC_LIGHT_ATTENBOOL             1020
#define IDC_AMBIENT_ONLY_STUB           1020
#define IDC_LGREEN                      1021
#define IDC_BUTTON1                     1021
#define IDC_CREATE_MORPHKEY             1021
#define IDC_15MM                        1021
#define IDC_SCALE_RESET                 1021
#define IDC_REVERSE                     1021
#define IDC_BARYMORPH_100TOTAL          1021
#define IDC_BONES_ASSIGNIKROOT          1021
#define IDC_BONE_FRONTFIN               1021
#define IDC_LGREENSPINNER               1022
#define IDC_BUTTON2                     1022
#define IDC_PROJ_IMAGE                  1022
#define IDC_20MM                        1022
#define IDC_DELETE_MORPHTARG            1022
#define IDC_BONES_CREATEENDEFFECTOR     1022
#define IDC_BONE_BACKFIN                1022
#define IDC_LBLUE                       1023
#define IDC_RADIO1                      1023
#define IDC_BUTTON3                     1023
#define IDC_TARG_REFERENCE              1023
#define IDC_RECT_LIGHT                  1023
#define IDC_24MM                        1023
#define IDC_BOOL_UNION                  1023
#define IDC_HEMI_SQUASH                 1023
#define IDC_SMOOTH_ALL                  1023
#define IDC_FAM_TETRA                   1023
#define IDC_HELIX_CW                    1023
#define IDC_PARTICLE_DOTS               1023
#define IDC_PART_BOTH                   1023
#define IDC_INSCRIBED                   1023
#define IDC_BONE_REFINE                 1023
#define IDC_LIGHT_ATTEN_LINEAR_RADIO    1023
#define IDC_LBLUESPINNER                1024
#define IDC_RADIO2                      1024
#define IDC_BUTTON4                     1024
#define IDC_TARG_COPY                   1024
#define IDC_CIRCLE_LIGHT                1024
#define IDC_28MM                        1024
#define IDC_BOOL_INTERSECTION           1024
#define IDC_HEMI_CHOP                   1024
#define IDC_SMOOTH_SIDES                1024
#define IDC_FAM_OCTA                    1024
#define IDC_HELIX_CCW                   1024
#define IDC_PARTICLE_TICKS              1024
#define IDC_PART_BODY                   1024
#define IDC_CIRCUMSCRIBED               1024
#define IDC_LIGHT_ATTEN_QUAD_RADIO      1024
#define IDC_RADIO3                      1025
#define IDC_BUTTON5                     1025
#define IDC_LHOTSIZESPINNER             1025
#define IDC_TARG_MOVE                   1025
#define IDC_35MM                        1025
#define IDC_MAP_RANGE                   1025
#define IDC_BOOL_DIFFERENCEA            1025
#define IDC_SMOOTH_NONE                 1025
#define IDC_FAM_DODEC                   1025
#define IDC_PART_LID                    1025
#define IDC_BOOL_DIFFERENCEAB           1025
#define IDC_LIGHT_ATTEN_NONE_RADIO      1025
#define IDC_RADIO4                      1026
#define IDC_BUTTON6                     1026
#define IDC_LHOTSIZE                    1026
#define IDC_TARG_INSTANCE               1026
#define IDC_50MM                        1026
#define IDC_BOOL_DISPRESULT             1026
#define IDC_FAM_STAR1                   1026
#define IDC_SMOOTH_STRIPES              1026
#define IDC_ATM_OPACITY                 1026
#define IDC_BUTTON7                     1027
#define IDC_LFALLOFFSPINNER             1027
#define IDC_85MM                        1027
#define IDC_BOOL_DIFFERENCEB            1027
#define IDC_BOOL_DIFFERENCEBA           1027
#define IDC_ATM_COLAMT                  1027
#define IDC_CHECK2                      1028
#define IDC_BUTTON8                     1028
#define IDC_LFALLOFF                    1028
#define IDC_135MM                       1028
#define IDC_TICKMARKS                   1028
#define IDC_BOOL_SHOWHIDDENOPS          1028
#define IDC_GENTEXTURE                  1028
#define IDC_PARTICLE_CONSTANTRATE       1028
#define IDC_BONE_AUTOLINK               1028
#define IDC_BONE_GENMAP                 1028
#define IDC_BUTTON9                     1029
#define IDC_LTDISTSPINNER               1029
#define IDC_200MM                       1029
#define IDC_BONE_COPYIKPARAMS           1029
#define IDC_DEPTH                       1029
#define IDC_BUTTON10                    1030
#define IDC_LASPECT_SPIN                1030
#define IDC_CREATE_VIEW                 1030
#define IDC_BONE_MATCHALIGNMENT         1030
#define IDC_ENABLE_MP_EFFECT            1030
#define IDC_DEPTHSPINNER                1030
#define IDC_BUTTON11                    1031
#define IDC_LASPECT                     1031
#define IDC_PREVIEW_MP_EFFECT           1031
#define IDC_LIST1                       1032
#define IDC_MORPHTARG_LIST              1032
#define IDC_LBLUR_SPIN                  1032
#define IDC_BOOL_OPERANDS               1032
#define IDC_BARYMORPH_TARGLIST          1032
#define IDC_MP_EFFECT_REFFECT_PER_PASS  1032
#define IDC_SCROLLBAR2                  1033
#define IDC_LBLUR                       1033
#define IDC_KEYTIME                     1033
#define IDC_KEYTIMESPIN                 1034
#define IDC_SCROLLBAR1                  1035
#define IDC_SCROLLBAR3                  1035
#define IDC_TCB_T                       1035
#define IDC_SCROLLBAR4                  1036
#define IDC_TCB_TSPIN                   1036
#define IDC_EDIT1                       1037
#define IDC_TEXTENTRY                   1037
#define IDC_TCB_C                       1037
#define IDC_TCB_CSPIN                   1038
#define IDC_USER1                       1039
#define IDC_PICK_MORPHTARG              1039
#define IDC_LIGHT_COLOR                 1039
#define IDC_TCB_B                       1039
#define IDC_ICORNER                     1040
#define IDC_TCB_BSPIN                   1040
#define IDC_SHADOW_COLOR                1040
#define IDC_LIGHT_COLOR_SPECULAR        1040
#define IDC_ISMOOTH                     1041
#define IDC_BARYMORPH_PERCENT           1041
#define IDC_DCORNER                     1042
#define IDC_OBCIRCULAR                  1042
#define IDC_BARYMORPH_PERCENTSPIN       1042
#define IDC_DSMOOTH                     1043
#define IDC_RADIUS1                     1043
#define IDC_DBEZIER                     1044
#define IDC_RAD1SPINNER                 1044
#define IDC_RADIUS2                     1045
#define IDC_RAD2SPINNER                 1046
#define IDC_TORUS_ROT                   1047
#define IDC_TURNS                       1047
#define IDC_TORUS_ROTSPIN               1048
#define IDC_TORUS_TWIST                 1049
#define IDC_TURNSSPINNER                1049
#define IDC_SHOW_RANGES                 1050
#define IDC_TORUS_TWISTSPIN             1050
#define IDC_TURNSEDIT                   1050
#define IDC_BIASSPINNER                 1051
#define IDC_SHOW_RANGES1                1051
#define IDC_BIASEDIT                    1052
#define IDC_SHOW_DECAY                  1053
#define IDC_USE_ATTEN                   1062
#define IDC_START_RANGE_SPIN            1063
#define IDC_START_RANGE                 1064
#define IDC_END_RANGE_SPIN              1065
#define IDC_END_RANGE                   1066
#define IDC_LMULTSPINNER                1067
#define IDC_LMULT                       1068
#define IDC_LTDIST                      1069
#define IDC_SSTEPSSPINNER               1069
#define IDC_USE_ATTEN1                  1069
#define IDC_TDIST                       1070
#define IDC_SHAPESTEPS                  1070
#define IDC_AFFECT_DIFFUSE              1070
#define IDC_TDISTSPINNER                1071
#define IDC_AFFECT_SPECULAR             1071
#define IDC_HITHER_SPIN                 1072
#define IDC_LCONTRAST                   1072
#define IDC_DIFFSOFT                    1072
#define IDC_LVSPINNER                   1073
#define IDC_HITHER                      1073
#define IDC_LV                          1074
#define IDC_YON_SPIN                    1074
#define IDC_LSSPINNER                   1075
#define IDC_YON                         1075
#define IDC_LS                          1076
#define IDC_LHSPINNER                   1077
#define IDC_LH                          1078
#define IDC_LCONTRASTSPIN               1079
#define IDC_AMBIENT_ONLY                1080
#define IDC_OVERSHOOT                   1081
#define IDC_DECAY_EDIT                  1082
#define IDC_PROJECTOR                   1083
#define IDC_DECAY_SPIN                  1084
#define IDC_PROJ_NOCOMPRESS             1084
#define IDC_BITMAP_FIT                  1085
#define IDC_PROJ_NOMIP                  1085
#define IDC_LIGHT_DIFFUSE               1086
#define IDC_LIGHT_ON                    1087
#define IDC_PREVKEY                     1090
#define IDC_NEXTKEY                     1091
#define IDC_KEYNUM                      1092
#define IDC_NAMES                       1142
#define IDC_LOOP                        1143
#define IDC_AUTO_START                  1144
#define IDC_LOOPS                       1145
#define IDC_REFRESH                     1146
#define IDC_TARGNAME                    1157
#define IDC_LIGHT_ATTEN_SLIDER          1175
#define IDC_TCB_GRAPH                   1179
#define IDC_SOFTEN_DIFFUSE              1180
#define IDC_DIFFSOFTSPIN                1181
#define IDC_LCONTRASTSPIN2              1190
#define IDC_LCONTRAST2                  1191
#define IDC_ADAPTIVE                    1225
#define IDC_SC_SLICEON                  1238
#define IDC_SC_SLICE1                   1239
#define IDC_SC_SLICE1SPIN               1240
#define IDC_SC_SLICE2                   1241
#define IDC_SC_SLICE2SPIN               1242
#define IDC_PROT_TARGET1_NAME           1274
#define IDC_PROT_TARGET2_NAME           1275
#define IDC_OPTIMIZE                    1500
#define IDC_LENS                        3000
#define IDC_LENSSPINNER                 3001
#define IDC_MAP_BIAS                    3002
#define IDC_MAP_BIAS_SPIN               3003
#define IDC_MAP_SIZE                    3004
#define IDC_MAP_SIZE_SPIN               3005
#define IDC_RT_BIAS                     3006
#define IDC_RT_BIAS_SPIN                3007
#define IDC_LENGTHEDIT                  3009
#define IDC_WIDTHEDIT                   3010
#define IDC_PICK_BOOLOPERAND            3011
#define IDC_FILLET                      3011
#define IDC_SCALEEDIT                   3011
#define IDC_BOOL_RECALC                 3012
#define IDC_AP_FILLET2                  3012
#define IDC_RENDERSEGEDIT               3012
#define IDC_BOOL_EXTRACTOP              3013
#define IDC_BOOL_DISPOPS                3015
#define IDC_BOOL_UPDATERENDER           3016
#define IDC_BOOL_UPDATEMANUAL           3017
#define IDC_BOOL_UPDATEALWAYS           3018
#define IDC_BOOL_UPDATESELECT           3019
#define IDC_TI_POSX                     3019
#define IDC_TI_POSXSPIN                 3020
#define IDC_TI_POSY                     3021
#define IDC_TI_POSYSPIN                 3022
#define IDC_TI_CREATE                   3023
#define IDC_TI_POSZ                     3024
#define IDC_PIESLICE1                   3024
#define IDC_TEXTITALIC                  3024
#define IDC_TI_POSZSPIN                 3025
#define IDC_PIESLICE2                   3025
#define IDC_TEXTUNDERLINE               3025
#define IDC_TI_CLOSE                    3026
#define IDC_TEXTLEFT                    3026
#define IDC_RADSPINNER1                 3027
#define IDC_TI_FINISH                   3027
#define IDC_TEXTCENTER                  3027
#define IDC_CREATECUBE                  3028
#define IDC_TEXTRIGHT                   3028
#define IDC_CREATEBOX                   3029
#define IDC_TEXTJUSTIFIED               3029
#define IDC_FAM_STAR2                   3030
#define IDC_VERT_BASIC                  3031
#define IDC_VERT_CENTER                 3032
#define IDC_VERT_SIDES                  3033
#define IDC_RADIUSSPIN                  3034
#define IDC_MANUAL_CLIP                 3035
#define IDC_CREATEEDGE                  3036
#define IDC_VPT_PARTICLES               3036
#define IDC_CREATECENTER                3037
#define IDC_VPT_PARTICLESSPIN           3037
#define IDC_ARCFROM                     3038
#define IDC_PARTICLE_SIZE               3038
#define IDC_ARCFROMSPINNER              3039
#define IDC_PARTICLE_SIZESPIN           3039
#define IDC_ARCTO                       3040
#define IDC_PARTICLE_START              3040
#define IDC_ARCTOSPINNER                3041
#define IDC_PARTICLE_STARTSPIN          3041
#define IDC_CREATE_EEC                  3042
#define IDC_PARTICLE_LIFE               3042
#define IDC_TEXTFONT                    3042
#define IDC_CREATE_CEE                  3043
#define IDC_PARTICLE_LIFESPIN           3043
#define IDC_TEXTSIZEEDIT                3043
#define IDC_EMITTER_WIDTH               3044
#define IDC_TEXTSIZESPINNER             3044
#define IDC_EMITTER_WIDTHSPIN           3045
#define IDC_TEXTBOLD                    3045
#define IDC_TEXTKERNINGEDIT             3045
#define IDC_EMITTER_HEIGHT              3046
#define IDC_TEXTKERNINGSPINNER          3046
#define IDC_EMITTER_HEIGHTSPIN          3047
#define IDC_TEXTLEADINGEDIT             3047
#define IDC_PARTICLE_SPEED              3048
#define IDC_TEXTLEADINGSPINNER          3048
#define IDC_PARTICLE_SPEEDSPIN          3049
#define IDC_PARTICLE_VARIATION          3050
#define IDC_PARTICLE_VARIATIONSPIN      3051
#define IDC_PARTICLE_CUST               3052
#define IDC_TEXTEXAMPLE                 3053
#define IDC_PARTICLE_BIRTHRATE          3053
#define IDC_PARTICLE_BIRTHRATESPIN      3054
#define IDC_PARTICLE_MAXRATE            3055
#define IDC_NO_CROSSOVER                3056
#define IDC_PARTICLE_TUMBLE             3056
#define IDC_RND_PARTICLES               3056
#define IDC_FAR_RANGE                   3057
#define IDC_PARTICLE_TUMBLESPIN         3057
#define IDC_RND_PARTICLESSPIN           3057
#define IDC_FAR_RANGE_SPIN              3058
#define IDC_PARTICLE_SCALE              3058
#define IDC_NEAR_RANGE                  3059
#define IDC_PARTICLE_SCALESPIN          3059
#define IDC_NEAR_RANGE_SPIN             3060
#define IDC_REND_PARTICLES              3060
#define IDC_TI_ADDPOINT                 3061
#define IDC_REND_PARTICLESSPIN          3061
#define IDC_MAP_RANGE_SPIN              3062
#define IDC_GLOBAL_SET                  3063
#define IDC_CAST_SHADOWS                3064
#define IDC_ATM_OPACITY_SPIN            3064
#define IDC_ABS_MAP_BIAS                3065
#define IDC_SHADOW_MAPS                 3066
#define IDC_RAY_TRACED_SHADOWS          3067
#define IDC_LT_EFFECT_SHADCOL           3068
#define IDC_EXCLUDE_DLG                 3069
#define IDC_PROJ_MAPNAME                3070
#define IDC_ATM_COLAMT_SPIN             3070
#define IDC_PARTICLE_REND1              3071
#define IDC_TEAPART                     3071
#define IDC_PARTICLE_REND2              3072
#define IDC_PARTICLE_REND3              3073
#define ID_STATIC                       3073
#define IDC_PARTICLE_TUMBLE_TXT         3074
#define IDC_TEA_BODY                    3074
#define IDC_PARTICLE_SCALE_TXT          3075
#define IDC_TEA_HANDLE                  3075
#define IDC_BOOL_ANAME                  3075
#define IDC_PARTICLE_BIRTHRATE_TXT      3076
#define IDC_TEA_SPOUT                   3076
#define IDC_MORPHTARG_NAME              3076
#define IDC_TEA_LID                     3077
#define IDC_IS_ORTHO                    3080
#define IDC_AP_FILLET                   3081
#define IDC_BARYMORPH_TARGETLEBEL       3082
#define IDC_BARYMORPH_PERCENTLABEL      3083
#define IDC_BARYMORPH_TOTAL             3084
#define IDC_ATMOS_SHADOWS               3085
#define IDC_START_RANGE1                4001
#define IDC_START_RANGE1_SPIN           4002
#define IDC_END_RANGE1                  4003
#define IDC_END_RANGE1_SPIN             4004
#define IDC_BOOL_EXTRACT_INTANCE        4005
#define IDC_BOOL_EXTRACT_COPY           4006
#define IDC_TARG_DISTANCE               4007
#define IDC_TEXT_UPDATE                 4008
#define IDC_BONES_AUTOBONE              4009
#define IDC_FOV_TYPE                    4010
#define IDC_ATT_NONE                    4020
#define IDC_ATT_INV                     4021
#define IDC_ATT_INVSQ                   4022
#define IDC_TAPE_X_AXIS                 4030
#define IDC_TAPE_Y_AXIS                 4031
#define IDC_TAPE_Z_AXIS                 4032
#define IDC_TAPE_XY_PLANE               4033
#define IDC_TAPE_YZ_PLANE               4034
#define IDC_TAPE_ZX_PLANE               4035
#define IDC_PROT_ANGLE                  4036
#define IDC_SHADPROJ_MAPNAME            4037
#define IDC_CONTRAST_T                  4038
#define IDC_DIFFSOFT_T                  4039
#define IDC_LIGHT_TYPE                  4041
#define IDC_CAM_TYPE                    4042
#define IDC_LIGHT_DECAY                 4043
#define IDC_MP_EFFECT                   4043
#define IDC_PCAM_PLAN                   4050
#define IDC_PCAM_BOTTOM                 4051
#define IDC_PCAM_LEFT                   4052
#define IDC_PCAM_SHOW_VOLUME            4052
#define IDC_PCAM_RIGHT                  4053
#define IDC_PCAM_SHOW_ENV               4053
#define IDC_PCAM_FRONT                  4054
#define IDC_PCAM_NEAR_ENV               4054
#define IDC_PCAM_BACK                   4055
#define IDC_PCAM_NEAR_ENV_SPINNER       4055
#define IDC_PCAM_QUADRANT1              4056
#define IDC_PCAM_FAR_ENV                4056
#define IDC_PCAM_QUADRANT2              4057
#define IDC_PCAM_FAR_ENV_SPINNER        4057
#define IDC_PCAM_QUADRANT3              4058
#define IDC_PCAM_UPDATE                 4058
#define IDC_PCAM_QUADRANT4              4059
#define IDC_SHADOW_TYPE                 4059
#define IDC_PCAM_DIMETRIC15             4060
#define IDC_SHAD_MULT                   4060
#define IDC_PCAM_DIMETRIC45             4061
#define IDC_SHAD_MULT_SPIN              4061
#define IDC_USE_SHAD_COLMAP             4062
#define IDC_EMITTER_ENABLE              4063
#define IDC_TOTALFACES                  4063
#define IDC_EMITTER_CA_PHOTONS_LBL      4064
#define IDC_EMITTER_DECAY_LBL           4065
#define IDC_EMITTER_CA_PHOTONS          4066
#define IDC_EMITTER_CA_PHOTONS_SPIN     4067
#define IDC_EMITTER_ENERGY              4068
#define IDC_PCAM_LOCK_X2Z               4069
#define IDC_EMITTER_ENERGY_SPIN         4069
#define IDC_PCAM_LOCK_X2Y               4070
#define IDC_EMITTER_ENERGY_LBL          4070
#define IDC_PCAM_LOCK_Y2Z               4071
#define IDC_EMITTER_DECAY               4071
#define IDC_PCAM_ANGLE_X                4072
#define IDC_EMITTER_GI_PHOTONS_LBL      4072
#define IDC_PCAM_ANGLE_X_SPINNER        4073
#define IDC_EMITTER_GI_PHOTONS          4073
#define IDC_PCAM_ANGLE_Y                4074
#define IDC_EMITTER_GI_PHOTONS_SPIN     4074
#define IDC_PCAM_ANGLE_Y_SPINNER        4075
#define IDC_PCAM_ANGLE_Z                4076
#define IDC_PCAM_ANGLE_Z_SPINNER        4077
#define IDC_PCAM_CLIP_NEAR              4084
#define IDC_PCAM_CLIP_NEAR_SPINNER      4085
#define IDC_PCAM_CLIP_FAR               4086
#define IDC_PCAM_CLIP_FAR_SPINNER       4087
#define IDC_PCAM_SHOW_SECTION           4088
#define IDC_PCAM_FIX_HEIGHT             4089
#define IDC_PCAM_FIX_WIDTH              4090
#define IDC_PCAM_FIX_ASPECT             4091
#define IDC_PCAM_HEIGHT                 4092
#define IDC_PCAM_HEIGHT_SPINNER         4093
#define IDC_PCAM_WIDTH                  4094
#define IDC_PCAM_WIDTH_SPINNER          4095
#define IDC_PCAM_ASPECT                 4096
#define IDC_PCAM_ASPECT_SPINNER         4097
#define IDC_OBJECT_SHADOWS              4098
#define IDC_DOF_FSTOP_LBL               4099
#define IDC_DOF_ENABLE                  4100
#define IDC_DOF_FSTOP                   4101
#define IDC_DOF_FSTOP_SPIN              4102
#define IDC_GROUP_CAUSTICS              4103
#define IDC_GROUP_GLOBALILLUM           4104
#define IDC_BONE_WIDTH                  4105
#define IDC_BONE_WIDTHSPIN              4106
#define IDC_BONE_HEIGHTSPIN             4107
#define IDC_BONE_IKSOLVER               4108
#define IDC_BONE_HEIGHT                 4108
#define IDC_BONE_TAPERSPIN              4109
#define IDC_BONE_TAPER                  4110
#define IDC_BONE_SIDEFINS_SIZE          4111
#define IDC_BONE_SIDEFINS_SIZESPIN      4112
#define IDC_BONE_SIDEFINS_START_TAPER   4113
#define IDC_BONE_SIDEFINS_START_TAPERSPIN 4114
#define IDC_BONE_SIDEFINS_END_TAPER     4115
#define IDC_BONE_SIDEFINS_END_TAPERSPIN 4116
#define IDC_BONE_FRONTFIN_SIZE          4117
#define IDC_BONE_FRONTFIN_START_TAPER   4118
#define IDC_BONE_FRONTFIN_END_TAPER     4119
#define IDC_BONE_FRONTFIN_SIZESPIN      4120
#define IDC_BONE_FRONTFIN_START_TAPERSPIN 4121
#define IDC_BONE_FRONTFIN_END_TAPERSPIN 4122
#define IDC_BONE_BACKFIN_SIZE           4123
#define IDC_BONE_BACKFIN_START_TAPER    4124
#define IDC_BONE_BACKFIN_END_TAPER      4125
#define IDC_BONE_BACKFIN_SIZESPIN       4126
#define IDC_BONE_BACKFIN_START_TAPERSPIN 4127
#define IDC_BONE_BACKFIN_END_TAPERSPIN  4128
#define IDC_SHADBIAS                    4130
#define IDC_SHADBIAS_SPIN               4131
#define IDC_SHADSIZE                    4132
#define IDC_SHADSIZE_SPIN               4133
#define IDC_SHADSAMPLE_RANGE            4134
#define IDC_SHADSAMPLE_RANGE_SPIN       4135
#define IDC_ABSOLUTE_MAPBIAS            4136
#define IDC_LIGHT_ATTEN                 4137
#define IDC_LIGHT_ATTEN_SPIN            4138
#define IDC_WIDTH                       4139
#define IDC_ADD                         4141
#define IDC_MULT                        4142
#define IDC_MADD                        4143
#define IDC_ILLUMINATE                  4144
#define IDS_DS_CREATE                   10008
#define IDS_DB_FREE                     10009
#define IDS_DB_BONES                    10010
#define IDS_DB_BASIC                    10011
#define IDS_DB_RING_ARRAY               10012
#define IDS_DB_SLAVECONTROL             10013
#define IDS_DB_SLAVE_CONTROL            10014
#define IDS_DB_TAPEHELPER               10015
#define IDS_DB_BONES_CLASS              10016
#define IDS_RB_TEAPOT_CLASS             10017
#define IDS_TH_TEXT_CLASS               10018
#define IDS_RB_TORUS_CLASS              10019
#define IDS_TH_TRI_PATCH_CLASS          10020
#define IDS_DB_DIRECTIONAL_CLASS        10021
#define IDS_DS_TDIRECTIONAL_CLASS       10022
#define IDS_DB_FREE_SPOT_CLASS          10023
#define IDS_DB_SLAVECONTROL_CLASS       10024
#define IDS_DB_TARGET_CLASS             10025
#define IDS_DB_PROTRACTOR               10026
#define IDS_DB_PROJDIR_CLASS            10026
#define IDS_DB_PROTHELPER_CLASS         10027
#define IDS_DB_PROT_CLASS               10028
#define IDS_DS_RINGARRAYPAR             10037
#define IDS_DS_RADIUS                   10038
#define IDS_DS_CYCLES                   10039
#define IDS_DS_AMPLITUDE                10040
#define IDS_DS_PHASE                    10041
#define IDS_CT_SURF                     10042
#define IDS_CT_CAP                      10043
#define IDS_CT_SLICE                    10044
#define IDS_DS_EXCLUDE__                10122
#define IDS_DS_INCLUDE__                10123
#define IDS_DS_LIGHTCOL                 10175
#define IDS_DS_SPECCOL                  10176
#define IDS_DB_TDIST                    20072
#define IDS_DB_MULTIPLIER               20315
#define IDS_DB_ATTENSTART               20316
#define IDS_DB_ATTENEND                 20317
#define IDS_DB_HOTSIZE                  20318
#define IDS_DB_FALLSIZE                 20319
#define IDS_DB_COLOR                    20320
#define IDS_DB_ASPECT_RATIO             20323
#define IDS_DB_TAPE_LENGTH              20326
#define IDS_DB_NRANGE                   20453
#define IDS_DB_FRANGE                   20454
#define IDS_RB_OBJECT                   30004
#define IDS_RB_PARAMETERS               30028
#define IDS_RB_ANGLE                    30029
#define IDS_RB_AMOUNT                   30031
#define IDS_RB_LENGTH                   30038
#define IDS_RB_WIDTH                    30039
#define IDS_RB_HEIGHT                   30040
#define IDS_RB_WSEGS                    30041
#define IDS_RB_HSEGS                    30042
#define IDS_RB_LSEGS                    30043
#define IDS_RB_FOV                      30044
#define IDS_RB_RADIUS                   30045
#define IDS_RB_SEGS                     30046
#define IDS_RB_SIDES                    30047
#define IDS_RB_SMOOTH                   30048
#define IDS_RB_RED                      30049
#define IDS_RB_GREEN                    30050
#define IDS_RB_BLUE                     30051
#define IDS_RB_HOTSIZE                  30052
#define IDS_RB_TRANSFORM                30053
#define IDS_RB_BASEPARAMS               30054
#define IDS_DB_TARGET                   30055
#define IDS_DB_DOT_TARGET               30056
#define IDS_DB_OMNI                     30057
#define IDS_DB_TARGET_SPOT              30058
#define IDS_DB_DIRECTIONAL              30059
#define IDS_DB_FREE_SPOT                30060
#define IDS_DB_NONE                     30061
#define IDS_RB_OBJ_MOD                  30062
#define IDS_DB_PROJDIR                  30062
#define IDS_RB_WORLD_MOD                30063
#define IDS_DB_GENERAL_PARAMS           30064
#define IDS_DB_DIR_PARAMS               30065
#define IDS_DB_SPOT_PARAMS              30066
#define IDS_DB_SHADOW_PARAMS            30067
#define IDS_DB_SELECT_TO_FIT            30068
#define IDS_DB_OMNI_LIGHT               30069
#define IDS_DB_DIR_LIGHT                30070
#define IDS_DB_DIRECT                   30071
#define IDS_DB_FSPOT                    30072
#define IDS_DB_SPOT                     30073
#define IDS_DB_LIGHT                    30074
#define IDS_DB_TAPE                     30075
#define IDS_DB_GENERAL                  30076
#define IDS_DB_TARGET_SPOT_CLASS        30077
#define IDS_DB_TAPE_CLASS               30078
#define IDS_LIGHT_ANIM                  30079
#define IDS_RB_EDITKEYINFO              30128
#define IDS_DB_OMNI_CLASS               30129
#define IDS_RB_MORPH_CLASS              30130
#define IDS_RB_SNOW_CLASS               30131
#define IDS_RB_GEOMETERIC               30157
#define IDS_RB_SHAPES                   30158
#define IDS_RB_LIGHTS                   30159
#define IDS_RB_CAMERAS                  30160
#define IDS_RB_HELPERS                  30161
#define IDS_RB_SPACEWARPS               30162
#define IDS_RB_SYSTEMS                  30163
#define IDS_DB_CAMERA                   30164
#define IDS_DB_SIMPLECAM                30165
#define IDS_DB_SIMPLECAM_CLASS          30166
#define IDS_RB_PICKOPERAND              30263
#define IDS_RB_PRIMITIVES               30264
#define IDS_PW_PRIMITIVES               30265
#define IDS_PW_CREATIONMETHOD           30266
#define IDS_PW_KEYBOARDENTRY            30267
#define IDS_PW_PARAMETERS               30268
#define IDS_PW_LENGTH                   30269
#define IDS_PW_WIDTH                    30270
#define IDS_PW_HEIGHT                   30271
#define IDS_PW_WSEGS                    30272
#define IDS_PW_LSEGS                    30273
#define IDS_PW_HSEGS                    30274
#define IDS_PW_SCALE                    30275
#define IDS_PW_RSEG                     30276
#define IDS_PW_MAPPING                  30277
#define IDS_PW_POS                      30278
#define IDS_PW_LEFTOVER                 30279
#define IDS_RB_BOOLEAN                  30475
#define IDS_RB_COMPOUNDOBJECTS          30476
#define IDS_RB_INVALIDBOOLEAN           30477
#define IDS_RB_OPERANDS                 30478
#define IDS_RB_PICKBOOLEAN              30479
#define IDS_RB_OPERANDA                 30480
#define IDS_RB_OPERANDATRANSFORM        30481
#define IDS_RB_OPERANDB                 30482
#define IDS_RB_OPERANDBTRANSFORM        30483
#define IDS_RB_OPERAND                  30484
#define IDS_RB_CUBICMORPHCONTROL        30485
#define IDS_RB_TARGETNUMBER             30486
#define IDS_RB_MORPH                    30487
#define IDS_RB_MORPHOBJECT              30488
#define IDS_RB_PICKTARGETS              30489
#define IDS_RB_CURRENTTARGETS           30490
#define IDS_RB_SPRAY                    30491
#define IDS_RB_SNOW                     30492
#define IDS_RB_PARTICLESYSTEMS          30493
#define IDS_RB_VIEWPARTICLES            30494
#define IDS_RB_DROPSIZE                 30495
#define IDS_RB_SPEED                    30496
#define IDS_RB_VARIATION                30497
#define IDS_RB_STARTTIME                30498
#define IDS_RB_LIFETIME                 30499
#define IDS_RB_BIRTHRATE                30500
#define IDS_RB_TUMBLE                   30501
#define IDS_RB_TUMBLERATE               30502
#define IDS_RB_SPHERE                   30503
#define IDS_RB_CREATIONMETHOD           30504
#define IDS_RB_KEYBOARDENTRY            30505
#define IDS_RB_HEMISPHERE               30506
#define IDS_RB_BOX                      30507
#define IDS_RB_CYLINDER                 30508
#define IDS_RB_CIRCLESEGMENTS           30509
#define IDS_RB_CAPSEGMENTS              30510
#define IDS_RB_SLICEON                  30511
#define IDS_RB_SLICEFROM                30512
#define IDS_RB_SLICETO                  30513
#define IDS_RB_GENTEXCOORDS             30514
#define IDS_RB_CONE                     30515
#define IDS_RB_RADIUS1                  30516
#define IDS_RB_RADIUS2                  30517
#define IDS_RB_TEAPOT                   30518
#define IDS_DB_TARGET_CAM               30519
#define IDS_RB_TORUS                    30520
#define IDS_RB_ROTATION2                30521
#define IDS_RB_TWIST                    30522
#define IDS_RB_HEDRA                    30523
#define IDS_RB_FAMILY                   30524
#define IDS_RB_PVALUE                   30525
#define IDS_RB_QVALUE                   30526
#define IDS_RB_PSCALE                   30527
#define IDS_RB_QSCALE                   30528
#define IDS_RB_RSCALE                   30529
#define IDS_RB_TUBE                     30530
#define IDS_RB_SEGMENTS                 30531
#define IDS_DB_FREE_CAM                 30532
#define IDS_RB_BOOLEAN_CLASS            30533
#define IDS_RB_BOX_CLASS                30534
#define IDS_DB_FREE_CLASS               30535
#define IDS_RB_MORPHOBJECT_CLASS        30536
#define IDS_RB_CUBICMORPHCONTROL_CLASS  30537
#define IDS_RB_SPHERE2                  30543
#define IDS_RB_CREATIONMETHOD2          30544
#define IDS_RB_FROM                     30545
#define IDS_RB_TO                       30546
#define IDS_RB_KEYBOARDENTRY2           30547
#define IDS_RB_HEMISPHERE2              30548
#define IDS_RB_BOX2                     30549
#define IDS_RB_CYLINDER2                30550
#define IDS_RB_CIRCLESEGMENTS2          30551
#define IDS_RB_CREATIONMETHOD3          30552
#define IDS_RB_KEYBOARDENTRY3           30553
#define IDS_RB_CIRCLESEGMENTS3          30554
#define IDS_RB_CREATIONMETHOD4          30555
#define IDS_RB_BODY                     30633
#define IDS_RB_LID                      30634
#define IDS_RB_SPOUT                    30635
#define IDS_RB_HANDLE                   30636
#define IDS_RB_HEIGHTSEGS               30639
#define IDS_RB_MAPSIZE                  30640
#define IDS_RB_MAPBIAS                  30641
#define IDS_RB_MAPRANGE                 30642
#define IDS_RB_RAYBIAS                  30643
#define IDS_RB_NEARPLANE                30644
#define IDS_RB_FARPLANE                 30645
#define IDS_RB_PICKMORPHTARGET          30657
#define IDS_RB_CREATEMORPHKEY           30658
#define IDS_RB_BOOLEANABORTED           30661
#define IDS_RB_BOOLEACOMPLETED          30662
#define IDS_RB_FLAKESIZE                30676
#define IDS_TH_RADIUS                   31033
#define IDS_TH_CIRCULAR                 31034
#define IDS_TH_SIDES                    31035
#define IDS_TH_RADIUS1                  31036
#define IDS_TH_RADIUS2                  31037
#define IDS_TH_PARAMETERS               31038
#define IDS_TH_LINE                     31079
#define IDS_TH_FROM                     31161
#define IDS_TH_TO                       31162
#define IDS_TH_DISTORTION               31163
#define IDS_TH_STARPOINTS               31164
#define IDS_TH_TURNS                    31165
#define IDS_TH_BIAS                     31166
#define IDS_TH_NEEDTWOSPLINEPOINTS      31188
#define IDS_TH_ERRORTWOCONSECUTIVE      31189
#define IDS_TH_NGON                     31259
#define IDS_TH_SPLINES                  31260
#define IDS_TH_CREATION_METHOD          31261
#define IDS_TH_KEYBOARD_ENTRY           31262
#define IDS_TH_TRI_PATCH                31263
#define IDS_TH_PATCH_GRIDS              31264
#define IDS_TH_ARC                      31265
#define IDS_TH_CIRCLE                   31266
#define IDS_TH_RECTANGLE                31267
#define IDS_TH_STAR                     31268
#define IDS_TH_DONUT                    31269
#define IDS_TH_TEXT                     31270
#define IDS_TH_HELIX                    31271
#define IDS_TH_ELLIPSE                  31272
#define IDS_TH_QUAD_PATCH               31273
#define IDS_TH_MAX_TEXT                 31274
#define IDS_TH_SIZE                     31275
#define IDS_TH_INTERPOLATION            31276
#define IDS_TH_ARC_CLASS                31277
#define IDS_TH_HEIGHT                   31278
#define IDS_TH_CIRCLE_CLASS             31279
#define IDS_TH_DIRECTION                31280
#define IDS_TH_ARIAL                    31281
#define IDS_TH_QUADPATCH                31282
#define IDS_TH_QUADPATCHOBJECT          31283
#define IDS_TH_TRIPATCH                 31284
#define IDS_TH_TRIPATCHOBJECT           31285
#define IDS_TH_HELIX_CLASS              31286
#define IDS_RB_CONE_CLASS               31287
#define IDS_RB_CYLINDER_CLASS           31288
#define IDS_TH_DONUT_CLASS              31289
#define IDS_TH_ELLIPSE_CLASS            31290
#define IDS_RB_HEDRA_CLASS              31291
#define IDS_DB_LIGHT_CLASS              31292
#define IDS_TH_NGON_CLASS               31293
#define IDS_TH_QUADPATCHOBJECT_CLASS    31294
#define IDS_RB_SPRAY_CLASS              31295
#define IDS_TH_RECTANGLE_CLASS          31296
#define IDS_DB_RING_ARRAY_CLASS         31297
#define IDS_RB_SPHERE_CLASS             31298
#define IDS_TH_LINE_CLASS               31299
#define IDS_TH_STAR_CLASS               31300
#define IDS_DB_TAPEHELPER_CLASS         31301
#define IDS_TH_TRIPATCHOBJECT_CLASS     31302
#define IDS_RB_TUBE_CLASS               31303
#define IDS_TH_QUAD_PATCH_CLASS         31304
#define IDS_TH_SIMPSPLINE               31315
#define IDS_DS_PARAMCHG                 31316
#define IDS_RB_DELETEMORPHTARG          31317
#define IDS_DB_ORTHO_WIDTH              31318
#define IDS_AP_EXTENDED                 31319
#define IDS_AP_FILLET                   31320
#define IDS_AP_FILLET1                  31321
#define IDS_AP_FILLET2                  31322
#define IDS_RB_BARYMORPHCONTROL         31323
#define IDS_DS_TDIRECTIONAL             31324
#define IDS_DS_TDIRECT                  31325
#define IDS_DS_TDIR_LIGHT               31326
#define IDS_DS_ATTENSTARTNEAR           31327
#define IDS_DS_ATTENENDNEAR             31328
#define IDS_DS_PROJ_PARAMS              31329
#define IDS_PROJ_PARAMS                 31329
#define IDS_RB_EXTRACTOP                31330
#define IDS_RB_BONEPARAMS               31331
#define IDS_DS_CONTRAST                 31332
#define IDS_SM_PATCH                    31333
#define IDS_PROJWIDTH                   31333
#define IDS_SM_EDITABLEMESH             31334
#define IDS_PROJHEIGHT                  31334
#define IDS_SM_NURBS_SURFACE            31335
#define IDS_PROJDEPTH                   31335
#define IDS_TH_LEADING                  31336
#define IDS_TH_KERNING                  31337
#define IDS_RB_BARYMORPHCONTROL_CLASS   31338
#define IDS_TH_SCRIBE                   31339
#define IDS_DS_DIFFSOFT                 31340
#define IDS_RB_PRIMLIB                  31341
#define IDS_DS_SHADCOL                  31342
#define IDS_DS_SETTYPE                  31343
#define IDS_DS_SETCAMTYPE               31344
#define IDS_AP_SLICEON                  31345
#define IDS_AP_SLICETO                  31346
#define IDS_AP_SLICEON3                 31347
#define IDS_AP_SLICEFROM                31347
#define IDS_DECAY_NONE                  31348
#define IDS_DECAY_INVERSE               31349
#define IDS_DECAY_INVSQ                 31350
#define IDS_ATTEN_PARAM                 31351
#define IDS_PRS_ORTHOLINE_CLASS         31352
#define IDS_DECAY_RADIUS                31352
#define IDS_ATMOS_OPACITY               31353
#define IDS_ATMOS_COLAMT                31354
#define IDS_PARRALLEL_CAMERA            31355
#define IDS_PARALLEL_CAMERA_CLASS       31356
#define IDS_PCAM_CUSTOM_GROUP           31357
#define IDS_PCAM_STANDARD_GROUP         31358
#define IDS_PCAM_AXIS_ANGLE_X           31359
#define IDS_PCAM_AXIS_ANGLE_Y           31360
#define IDS_PCAM_AXIS_ANGLE_Z           31361
#define IDS_PCAM_HEIGHT                 31362
#define IDS_PCAM_WIDTH                  31363
#define IDS_PCAM_ASPECT                 31364
#define IDS_SECTION_UPDATE              31365
#define IDS_LOCK_X2Z                    31366
#define IDS_LOCK_X2Y                    31367
#define IDS_LOCK_Y2Z                    31368
#define IDS_PCAM_FIX_HEIGHT             31369
#define IDS_PCAM_FIX_WIDTH              31370
#define IDS_PCAM_FIX_ASPECT             31371
#define IDS_PARALLEL_CAMERA             31372
#define IDS_DS_PROJMAP                  31373
#define IDS_DS_SHADPROJMAP              31374
#define IDS_DS_SHAD_GEN                 31375
#define IDS_DS_SETSHADTYPE              31376
#define IDS_PW_CV                       31377
#define IDS_SHAD_DENSITY                31379
#define IDS_EMITTER                     31380
#define IDS_EMITTER_ENABLE              31381
#define IDS_EMITTER_ENERGY              31382
#define IDS_EMITTER_CA_PHOTONS          31383
#define IDS_DOF                         31384
#define IDS_DOF_ENABLE                  31385
#define IDS_DOF_FSTOP                   31386
#define IDS_TH_VIZ_TEXT                 31387
#define IDS_EMITTER_GI_PHOTONS          31388
#define IDS_PW_PLANE_ERROR              31389
#define IDS_PW_PLANE_MEMORY_ERROR       31390
#define IDS_BONE_WIDTH                  31391
#define IDS_BONE_HEIGHT                 31392
#define IDS_BONE_TAPER                  31393
#define IDS_BONE_LENGTH                 31394
#define IDS_BONE_SIDEFINS               31395
#define IDS_BONE_SF_SIZE                31396
#define IDS_BONE_SF_STARTTAPER          31397
#define IDS_BONE_SF_ENDTAPER            31398
#define IDS_BONE_FRONTFIN               31399
#define IDS_BONE_FF_SIZE                31400
#define IDS_BONE_FF_STARTTAPER          31401
#define IDS_BONE_FF_ENDTAPER            31402
#define IDS_BONE_BACKFIN                31403
#define IDS_BONE_BF_SIZE                31404
#define IDS_BONE_BF_STARTTAPER          31405
#define IDS_BONE_BF_ENDTAPER            31406
#define IDS_BONE_GENMAP                 31407
#define IDS_BONE_IK_ROLLUP_NAME         31408
#define IDS_BONE_OBJ_NAME               31409
#define IDS_BONE_IKSOLVER_HD            31410
#define IDS_BONE_UNDO_DELETE_BONE       31411
#define IDS_BONE_UNDO_ASSIGN_IK         31412
#define IDS_MP_EFFECT                   31413
#define IDS_MP_EFFECT_ENABLE            31414
#define IDS_MP_EFF_REND_EFF_PER_PASS    31416
#define IDS_BONE_REFINE                 31420
#define IDS_DS_CAMPRESET                31421
#define IDS_DS_MULTIPASS                31422
#define IDS_HISOLVER                    31423
#define IDS_RTLIGHT_ON                  31424
#define IDS_LIGHT_GEN_PARAMS            31425
#define IDS_LIGHT_ATTEN_PARAMSS         31426
#define IDS_LIGHT_SPOT_PARAMS           31427
#define IDS_DS_HUE                      31428
#define IDS_DS_SAT                      31429
#define IDS_DS_VAL                      31430
#define IDS_DS_DIFFON                   31431
#define IDS_DS_SPEC                     31432
#define IDS_DS_AMBI                     31433
#define IDS_DS_USENEAR                  31434
#define IDS_DS_SHOWNEARRANGES           31435
#define IDS_DS_USEFARATTEN              31436
#define IDS_DS_SHOWFARRANGES            31437
#define IDS_DB_DECAY_STATE              31438
#define IDS_DS_SHOWDECAY                31439
#define IDS_DS_SHOWCONE                 31440
#define IDS_DS_OVERSHOOT                31441
#define IDS_DS_LIGHTSHAPE_RATIO         31442
#define IDS_DB_LIGHTTYPE                31443
#define IDS_DS_RED                      31444
#define IDS_DS_GREEN                    31445
#define IDS_DS_BLUE                     31446
#define IDS_LIGHT_SHADOWS               31447
#define IDS_DS_USESHADOWSS              31448
#define IDS_DS_USESHADOWGLOBS           31449
#define IDS_DS_SHADCOLORS               31450
#define IDS_DS_DENSITYSHADOWS           31451
#define IDS_DS_USESHADOWMAPS            31452
#define IDS_DS_SHADOWMAPBUTTONS         31453
#define IDS_DS_LIGHTEFFECTS_SHADS       31454
#define IDS_DS_ATMOS_SHADS              31455
#define IDS_DS_ATMOS_SHAD_OPACS         31456
#define IDS_DS_ATMOS_SHAD_COLORS        31457
#define IDS_LIGHT_SHADOWMAP_PARAMSS     31458
#define IDS_DS_SHADOWMAP_BIASS          31459
#define IDS_DS_SHADOWMAP_SIZES          31460
#define IDS_DS_SHADOWMAP_SAMPLESS       31461
#define IDS_DS_SHADOWMAP_ABSOLULTE_BIASS 31462
#define IDS_DS_CASTSHADOWSS             31463
#define IDS_DS_LIGHT_ATTEN_SLIDER       31464
#define IDC_STATIC                      -1

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        201
#define _APS_NEXT_COMMAND_VALUE         40001
#define _APS_NEXT_CONTROL_VALUE         4145
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
