/*==LICENSE==*

CyanWorlds.com Engine - MMOG client, server and tools
Copyright (C) 2011  Cyan Worlds, Inc.

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.

Additional permissions under GNU GPL version 3 section 7

If you modify this Program, or any covered work, by linking or
combining it with any of RAD Game Tools Bink SDK, Autodesk 3ds Max SDK,
NVIDIA PhysX SDK, Microsoft DirectX SDK, OpenSSL library, Independent
JPEG Group JPEG library, Microsoft Windows Media SDK, or Apple QuickTime SDK
(or a modified version of those libraries),
containing parts covered by the terms of the Bink SDK EULA, 3ds Max EULA,
PhysX SDK EULA, DirectX SDK EULA, OpenSSL and SSLeay licenses, IJG
JPEG Library README, Windows Media SDK EULA, or QuickTime SDK EULA, the
licensors of this Program grant you additional
permission to convey the resulting work. Corresponding Source for a
non-source form of such a combination shall include the source code for
the parts of OpenSSL and IJG JPEG Library used as well as that of the covered
work.

You can contact Cyan Worlds, Inc. by email legal@cyan.com
 or by snail mail at:
      Cyan Worlds, Inc.
      14617 N Newport Hwy
      Mead, WA   99021

*==LICENSE==*/

#include "plVulkanShaders.h"

// Generated by glslangValidator -x at build time; see this library's
// CMakeLists.txt. The generated files are bare comma-separated hex words, so
// they drop straight into an initializer.

static const uint32_t s_fixedPipelineVertexShader[] = {
#include "ShaderSrc/FixedPipeline.vert.spv.h"
};

static const uint32_t s_fixedPipelineFragmentShader[] = {
#include "ShaderSrc/FixedPipeline.frag.spv.h"
};

const plVulkanShaderBlob kFixedPipelineVertexShader{
    s_fixedPipelineVertexShader, sizeof(s_fixedPipelineVertexShader)
};

const plVulkanShaderBlob kFixedPipelineFragmentShader{
    s_fixedPipelineFragmentShader, sizeof(s_fixedPipelineFragmentShader)
};

static const uint32_t s_plateVertexShader[] = {
#include "ShaderSrc/Plate.vert.spv.h"
};

static const uint32_t s_plateFragmentShader[] = {
#include "ShaderSrc/Plate.frag.spv.h"
};

const plVulkanShaderBlob kPlateVertexShader{
    s_plateVertexShader, sizeof(s_plateVertexShader)
};

const plVulkanShaderBlob kPlateFragmentShader{
    s_plateFragmentShader, sizeof(s_plateFragmentShader)
};

static const uint32_t s_textFontVertexShader[] = {
#include "ShaderSrc/TextFont.vert.spv.h"
};

static const uint32_t s_textFontFragmentShader[] = {
#include "ShaderSrc/TextFont.frag.spv.h"
};

const plVulkanShaderBlob kTextFontVertexShader{
    s_textFontVertexShader, sizeof(s_textFontVertexShader)
};

const plVulkanShaderBlob kTextFontFragmentShader{
    s_textFontFragmentShader, sizeof(s_textFontFragmentShader)
};

static const uint32_t s_shadowCasterVertexShader[] = {
#include "ShaderSrc/ShadowCaster.vert.spv.h"
};

static const uint32_t s_shadowCasterFragmentShader[] = {
#include "ShaderSrc/ShadowCaster.frag.spv.h"
};

const plVulkanShaderBlob kShadowCasterVertexShader{
    s_shadowCasterVertexShader, sizeof(s_shadowCasterVertexShader)
};

const plVulkanShaderBlob kShadowCasterFragmentShader{
    s_shadowCasterFragmentShader, sizeof(s_shadowCasterFragmentShader)
};

static const uint32_t s_shadowApplyVertexShader[] = {
#include "ShaderSrc/ShadowApply.vert.spv.h"
};

static const uint32_t s_shadowApplyFragmentShader[] = {
#include "ShaderSrc/ShadowApply.frag.spv.h"
};

const plVulkanShaderBlob kShadowApplyVertexShader{
    s_shadowApplyVertexShader, sizeof(s_shadowApplyVertexShader)
};

const plVulkanShaderBlob kShadowApplyFragmentShader{
    s_shadowApplyFragmentShader, sizeof(s_shadowApplyFragmentShader)
};

static const uint32_t s_avatarVertexShader[] = {
#include "ShaderSrc/Avatar.vert.spv.h"
};

static const uint32_t s_avatarFragmentShader[] = {
#include "ShaderSrc/Avatar.frag.spv.h"
};

const plVulkanShaderBlob kAvatarVertexShader{
    s_avatarVertexShader, sizeof(s_avatarVertexShader)
};

const plVulkanShaderBlob kAvatarFragmentShader{
    s_avatarFragmentShader, sizeof(s_avatarFragmentShader)
};

static const uint32_t s_fullscreenVertexShader[] = {
#include "ShaderSrc/Fullscreen.vert.spv.h"
};

static const uint32_t s_blurFragmentShader[] = {
#include "ShaderSrc/Blur.frag.spv.h"
};

static const uint32_t s_gammaFragmentShader[] = {
#include "ShaderSrc/Gamma.frag.spv.h"
};

const plVulkanShaderBlob kFullscreenVertexShader{
    s_fullscreenVertexShader, sizeof(s_fullscreenVertexShader)
};

const plVulkanShaderBlob kBlurFragmentShader{
    s_blurFragmentShader, sizeof(s_blurFragmentShader)
};

const plVulkanShaderBlob kGammaFragmentShader{
    s_gammaFragmentShader, sizeof(s_gammaFragmentShader)
};

static const uint32_t s_grassVertexShader[] = {
#include "ShaderSrc/Grass.vert.spv.h"
};

static const uint32_t s_grassFragmentShader[] = {
#include "ShaderSrc/Grass.frag.spv.h"
};

const plVulkanShaderBlob kGrassVertexShader{
    s_grassVertexShader, sizeof(s_grassVertexShader)
};

const plVulkanShaderBlob kGrassFragmentShader{
    s_grassFragmentShader, sizeof(s_grassFragmentShader)
};

static const uint32_t s_compCosinesVertexShader[] = {
#include "ShaderSrc/CompCosines.vert.spv.h"
};

static const uint32_t s_compCosinesFragmentShader[] = {
#include "ShaderSrc/CompCosines.frag.spv.h"
};

const plVulkanShaderBlob kCompCosinesVertexShader{
    s_compCosinesVertexShader, sizeof(s_compCosinesVertexShader)
};

const plVulkanShaderBlob kCompCosinesFragmentShader{
    s_compCosinesFragmentShader, sizeof(s_compCosinesFragmentShader)
};

static const uint32_t s_biasNormalsVertexShader[] = {
#include "ShaderSrc/BiasNormals.vert.spv.h"
};

static const uint32_t s_biasNormalsFragmentShader[] = {
#include "ShaderSrc/BiasNormals.frag.spv.h"
};

const plVulkanShaderBlob kBiasNormalsVertexShader{
    s_biasNormalsVertexShader, sizeof(s_biasNormalsVertexShader)
};

const plVulkanShaderBlob kBiasNormalsFragmentShader{
    s_biasNormalsFragmentShader, sizeof(s_biasNormalsFragmentShader)
};

static const uint32_t s_waveRipVertexShader[] = {
#include "ShaderSrc/WaveRip.vert.spv.h"
};

static const uint32_t s_waveRipFragmentShader[] = {
#include "ShaderSrc/WaveRip.frag.spv.h"
};

const plVulkanShaderBlob kWaveRipVertexShader{
    s_waveRipVertexShader, sizeof(s_waveRipVertexShader)
};

const plVulkanShaderBlob kWaveRipFragmentShader{
    s_waveRipFragmentShader, sizeof(s_waveRipFragmentShader)
};

static const uint32_t s_waveDec1LayVertexShader[] = {
#include "ShaderSrc/WaveDec1Lay_7.vert.spv.h"
};

static const uint32_t s_waveDec1LayFragmentShader[] = {
#include "ShaderSrc/CbaseAbase.frag.spv.h"
};

const plVulkanShaderBlob kWaveDec1LayVertexShader{
    s_waveDec1LayVertexShader, sizeof(s_waveDec1LayVertexShader)
};

const plVulkanShaderBlob kWaveDec1LayFragmentShader{
    s_waveDec1LayFragmentShader, sizeof(s_waveDec1LayFragmentShader)
};

static const uint32_t s_waveDecEnvVertexShader[] = {
#include "ShaderSrc/WaveDecEnv.vert.spv.h"
};

static const uint32_t s_waveDecEnvFragmentShader[] = {
#include "ShaderSrc/WaveDecEnv.frag.spv.h"
};

const plVulkanShaderBlob kWaveDecEnvVertexShader{
    s_waveDecEnvVertexShader, sizeof(s_waveDecEnvVertexShader)
};

const plVulkanShaderBlob kWaveDecEnvFragmentShader{
    s_waveDecEnvFragmentShader, sizeof(s_waveDecEnvFragmentShader)
};

static const uint32_t s_waveFixedVertexShader[] = {
#include "ShaderSrc/WaveSet7.vert.spv.h"
};

static const uint32_t s_waveFixedFragmentShader[] = {
#include "ShaderSrc/WaveSet7.frag.spv.h"
};

const plVulkanShaderBlob kWaveFixedVertexShader{
    s_waveFixedVertexShader, sizeof(s_waveFixedVertexShader)
};

const plVulkanShaderBlob kWaveFixedFragmentShader{
    s_waveFixedFragmentShader, sizeof(s_waveFixedFragmentShader)
};
