//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by MaxPlasmaMtls.rc
//
#define IDS_LAYER                       400
#define IDS_MAX_CAMERA_LAYER            401
#define IDS_PASS_MTL                    402
#define IDS_PASS_BASIC                  403
#define IDS_PASS_ADV                    404
#define IDS_PASS_LAYERS                 405
#define IDS_PASS_OUTPUT                 406
#define IDS_LAYER_TEX                   407
#define IDS_LAYER_BASIC                 408
#define IDS_MULTI_MTL                   409
#define IDS_DECAL_MTL                   410
#define IDS_COMP_MTL                    411
#define IDS_PASS_ANIM                   412
#define IDS_STATIC_ENVMAP_LAYER         413
#define IDS_PARTICLE_HEIGHT             414
#define IDS_DYNAMIC_ENVMAP_LAYER        415
#define IDS_BASIC_AMB                   416
#define IDS_BASIC_COLOR                 417
#define IDS_BASIC_OPAC                  418
#define IDS_PASS_ANIM_EASE              419
#define IDS_MAX_CAMERA_LAYER_PROPS      420
#define IDS_CAM_LAYER_CAMERA            421
#define IDS_CAM_LAYER_ROOT_NODE         422
#define IDS_BASIC_RUNCOLOR              428
#define IDS_BASIC_SPECCOLOR             429
#define IDS_BUMP_MTL                    430
#define IDS_BITMAP_CLIPU                432
#define IDS_BITMAP_CLIPV                433
#define IDS_BITMAP_CLIPW                434
#define IDS_BITMAP_CLIPH                435
#define IDS_STATIC_ENVMAP_LAYER_TEX     436
#define IDS_CUBIC_RENDER_TITLE          437
#define IDS_BITMAP_TEXSIZE              438
#define IDS_BITMAP_BASENAME             439
#define IDS_SELECT_NODE                 440
#define IDS_PARTICLE_MTL                441
#define IDS_PARTICLE_OPACITY            442
#define IDS_PARTICLE_COLOR              443
#define IDS_PARTICLE_WIDTH              444
#define IDS_PARTICLE_AMB_COLOR          445
#define IDS_SELECT_ANCHOR               446
#define IDS_DYNAMIC_ENVMAP_LAYER_TEX    447
#define IDS_DYN_TEXT_LAYER              449
#define IDS_DYN_TEXT_LAYER_PROPS        450
#define IDS_CLOTHING_MTL                451
#define IDS_ANGLE_ATTEN_LAYER           452
#define IDS_ANGLE_ATTEN_LAYER_PROPS     453
#define IDS_ANIMSTEALTH                 454
#define IDS_STEALTH_NAME                455
#define IDS_NTWATCHER_NAME              456
#define IDB_BUTTONS                     457
#define IDB_MASKBUTTONS                 458
#define IDB_DETAILBGND                  459
#define IDD_PASS_BASIC                  700
#define IDD_LAYER_BASIC                 701
#define IDD_LAYER_TEX                   702
#define IDD_PASS_LAYERS                 703
#define IDD_MULTIPASS                   704
#define IDD_PASS_ADV                    705
#define IDD_DECAL_LAYERS                706
#define IDD_DECAL_BASIC                 707
#define IDD_COMPOSITE                   708
#define IDD_PASS_ANIM                   709
#define IDD_STATIC_ENVMAP_LAYER         710
#define IDD_PARTICLE                    711
#define IDD_DYNAMIC_ENVMAP_LAYER        712
#define IDD_BUMP_BASIC                  713
#define IDD_BUMP_ANIM                   714
#define IDD_DYN_TEXT_LAYER              715
#define IDD_CLOTHING                    716
#define IDD_PASS_ANIM_EASE              717
#define IDD_ANGLE_ATTEN_LAYER           718
#define IDD_STEALTH_ANIM                719
#define IDD_MAX_CAMERA_LAYER            720
#define IDC_PLACEHOLDER                 1209
#define IDC_CLOTHING_FORCED_ACC         1285
#define IDC_LAYER_EDIT                  3004
#define IDC_LAYER_SPIN                  3005
#define IDC_ALPHA_TEXT                  3006
#define IDC_DISCARD_ALPHA               3007
#define IDC_BLEND_TEXT                  3008
#define IDC_NO_FILTERING                3009
#define IDC_USE_BITMAP                  3010
#define IDC_SCALE_NONE                  3011
#define IDC_MIPBLUR_SPIN                3012
#define IDC_SCALE_ALL                   3013
#define IDC_NO_DISCARD                  3014
#define IDC_SCALE_HALF                  3015
#define IDC_LAYER_NAME                  3016
#define IDC_LAYER1                      3018
#define IDC_LAYER2                      3020
#define IDC_MIPBIAS_SPIN                3021
#define IDC_LEFT_NAME                   3022
#define IDC_TOP_ON                      3023
#define IDC_TOP_NAME                    3024
#define IDC_BLEND_TEXT3                 3025
#define IDC_BACK_NAME                   3025
#define IDC_LAYER_ALPHA                 3026
#define IDC_RIGHT_NAME                  3026
#define IDC_BOTTOM_NAME                 3027
#define IDC_LAYER_ADD                   3028
#define IDC_GENERATE_FACES              3028
#define IDC_LAYER_MULTIPLY              3029
#define IDC_OUTPUTA_DISCARD             3032
#define IDC_OUTPUTA_ADD                 3034
#define IDC_OUTPUTA_MULT                3035
#define IDC_OUTPUTB_NONE                3036
#define IDC_OUTPUTB_ALPHA               3037
#define IDC_OUTPUTB_ADD                 3038
#define IDC_LOCK_AD                     3040
#define IDC_LOCK_COLORS                 3041
#define IDC_Z_ZNOWRITE                  3042
#define IDC_SHADE_NO_FOG                3043
#define IDC_SHADE_SOFTSHADOW            3044
#define IDC_SHADE_NO_PROJ               3045
#define IDC_SHADE_VERTEXSHADE           3046
#define IDC_SHADE_NOSHADE               3047
#define IDC_SHADE_SPECULAR              3048
#define IDC_ALPHA_TEST_HIGH             3048
#define IDC_SHADE_WHITE                 3049
#define IDC_USAGE_TYPE                  3050
#define IDC_LAYER_RELOAD                3051
#define IDC_LAYER_COLOR_AMB             3052
#define IDC_LAYER_LOAD_GEN              3052
#define IDC_LAYER_COLOR                 3053
#define IDC_CLOTHING_TINT2              3053
#define IDC_LAYER_RUNCOLOR              3054
#define IDC_HSMAX_LAYER_RGBOUT          3054
#define IDC_LAYER_SPECCOLOR             3055
#define IDC_HSMAX_LAYER_ALPHAOUT        3055
#define IDC_HSMAX_LAYER_RGBOUT2         3056
#define IDC_HSMAX_LAYER_ALPHAOUT2       3057
#define IDC_CLIP_X                      3058
#define IDC_BASE_FILENAME               3058
#define IDC_CLIP_XSPIN                  3059
#define IDC_CLIP_Y                      3060
#define IDC_CLIP_YSPIN                  3061
#define IDC_CLIP_W                      3062
#define IDC_CLIP_WSPIN                  3063
#define IDC_CLIP_H                      3064
#define IDC_CLIP_HSPIN                  3065
#define IDC_BM_CLIP                     3066
#define IDC_BM_CROP_IMAGE               3067
#define IDC_BM_CROP                     3068
#define IDC_BM_PLACE                    3069
#define IDC_TEX1                        3070
#define IDC_EXPORTWIDTH                 3070
#define IDC_EXPORTWIDTH_SPINNER         3071
#define IDC_TEXON1                      3071
#define IDC_TEX2                        3072
#define IDC_EXPORTHEIGHT                3072
#define IDC_TEXON2                      3073
#define IDC_EXPORTHEIGHT_SPINNER        3073
#define IDC_TEX3                        3074
#define IDC_DT_LMARGIN                  3074
#define IDC_TEXON3                      3075
#define IDC_DT_LMARGIN_SPIN             3075
#define IDC_TEX4                        3076
#define IDC_TEXON4                      3077
#define IDC_DT_TMARGIN                  3078
#define IDC_TEX5                        3078
#define IDC_DT_TMARGIN_SPIN             3079
#define IDC_TEXON5                      3079
#define IDC_DT_RMARGIN                  3080
#define IDC_TEX6                        3080
#define IDC_DT_RMARGIN_SPIN             3081
#define IDC_TEXON6                      3081
#define IDC_DT_BMARGIN                  3082
#define IDC_TEX7                        3082
#define IDC_DT_BMARGIN_SPIN             3083
#define IDC_TEXON7                      3083
#define IDC_DT_FONTSIZE                 3084
#define IDC_TEX8                        3084
#define IDC_DT_FONTSIZE_SPIN            3085
#define IDC_TEXON8                      3085
#define IDC_TEX9                        3086
#define IDC_TEXON9                      3087
#define IDC_TEX10                       3088
#define IDC_TEXON10                     3089
#define IDC_Z_ZNOREAD                   3090
#define IDC_Z_INC                       3092
#define IDC_MISC_WIRE                   3093
#define IDC_MISC_TWOSIDED               3094
#define IDC_MISC_MESHOUTLINES           3095
#define IDC_USE_MIPBIAS                 3096
#define IDC_BLEND_INV_COLOR             3097
#define IDC_BLEND_INV_ALPHA             3098
#define IDC_BLEND_NO_COLOR              3099
#define IDC_USAGE_SETUP                 3100
#define IDC_Z_ZCLEAR                    3101
#define IDC_FORCE_NONCOMPRESSED         3102
#define IDC_SH_EDIT                     3103
#define IDC_REFRACT                     3103
#define IDC_TR_EDIT                     3105
#define IDC_MIPBLUR_EDIT                3106
#define IDC_MIPBIAS_EDIT                3107
#define IDC_MTL_USE_GLOBAL              3110
#define IDC_SH_SPIN                     3112
#define IDC_TR_SPIN                     3114
#define IDC_USE_DETAIL                  3129
#define IDC_DETAIL_SAMPLE               3130
#define IDC_DETAIL_START_SIZE_EDIT      3131
#define IDC_DETAIL_START_SIZE_SPIN      3132
#define IDC_DETAIL_START_OPAC_EDIT      3133
#define IDC_DETAIL_START_OPAC_SPIN      3134
#define IDC_DETAIL_STOP_SIZE_EDIT       3135
#define IDC_DETAIL_STOP_SIZE_SPIN       3136
#define IDC_DETAIL_STOP_OPAC_EDIT       3137
#define IDC_DETAIL_STOP_OPAC_SPIN       3138
#define IDC_COMBO2                      3139
#define IDC_COMBO3                      3140
#define IDC_NAMES                       3142
#define IDC_LOOP                        3143
#define IDC_AUTO_START                  3144
#define IDC_LOOPS                       3145
#define IDC_REFRESH_ANIMS               3146
#define IDC_LAYER_EMISSIVE_CB           3147
#define IDC_FRONT_NAME                  3148
#define IDC_TEXSIZE_EDIT                3149
#define IDC_TEXSIZE_SPIN                3150
#define IDC_PARTICLE_HEIGHT             3151
#define IDC_FARDIST_EDIT                3151
#define IDC_PARTICLE_HEIGHT_SPIN        3152
#define IDC_FARDIST_SPIN                3152
#define IDC_PARTICLE_WIDTH              3153
#define IDC_PARTICLE_WIDTH_SPIN         3154
#define IDC_PARTICLE_XTILE              3155
#define IDC_PARTICLE_XTILE_SPIN         3156
#define IDC_PARTICLE_YTILE              3157
#define IDC_PARTICLE_YTILE_SPIN         3158
#define IDC_PARTICLE_OPACITY            3159
#define IDC_PARTICLE_OPACITY_SPIN       3160
#define IDC_PARTICLE_COLOR              3161
#define IDC_PARTICLE_NORMAL             3162
#define IDC_PARTICLE_TEXTURE            3163
#define IDC_CLOTHING_TEXTURE2           3164
#define IDC_PARTICLE_ORIENT_VELOCITY    3164
#define IDC_CLOTHING_TEXTURE3           3165
#define IDC_PARTICLE_ORIENT_UP          3165
#define IDC_CLOTHING_TEXTURE4           3166
#define IDC_PARTICLE_BLEND_ALPHA        3166
#define IDC_PARTICLE_BLEND_ADD          3167
#define IDC_PARTICLE_AMB_COLOR          3168
#define IDC_ANCHOR_NODE                 3169
#define IDC_PARTICLE_ORIENT_VELSTRETCH  3169
#define IDC_USEMAXFOG                   3170
#define IDC_PARTICLE_ORIENT_VELFLOW     3170
#define IDC_SCOL_LABEL                  3172
#define IDC_RCOL_LABEL                  3173
#define IDC_INTEN_EDIT                  3174
#define IDC_INTEN_SPIN                  3175
#define IDC_CLOTHING_TILE1_NAME         3176
#define IDC_CLOTHING_TILE2_NAME         3177
#define IDC_DUMMY_EDIT1                 3178
#define IDC_CLOTHING_TILE3_NAME         3178
#define IDC_DUMMY_SPIN1                 3179
#define IDC_CLOTHING_TILE4_NAME         3179
#define IDC_DUMMY_EDIT2                 3180
#define IDC_CLOTHING_TEXTURE1           3180
#define IDC_DUMMY_SPIN2                 3181
#define IDC_CLOTHING_TILESET            3181
#define IDC_CLOTHING_TILE1_SIZE         3182
#define IDC_CLOTHING_TILE2_SIZE         3183
#define IDC_CLOTHING_TILE3_SIZE         3184
#define IDC_CLOTHING_TILE4_SIZE         3185
#define IDC_CLOTHING_LAYER              3186
#define IDC_DYNTEXT_MAKESTATIC          3186
#define IDC_DT_TEXT                     3187
#define IDC_DT_FONTFACE                 3188
#define IDC_DOUBLE_FADE                 3189
#define IDC_TRANSP_ANGLE_0              3190
#define IDC_TRANSP_ANGLE_0_SPIN         3191
#define IDC_OPAQUE_ANGLE_0              3192
#define IDC_PARTICLE_NOFILTER           3192
#define IDC_OPAQUE_ANGLE_0_SPIN         3193
#define IDC_TRANSP_ANGLE_1              3194
#define IDC_TRANSP_ANGLE_1_SPIN         3195
#define IDC_OPAQUE_ANGLE_1              3196
#define IDC_OPAQUE_ANGLE_1_SPIN         3197
#define IDC_REFLECT                     3198
#define IDC_LO_CLAMP                    3199
#define IDC_CLOTHING_DESCRIPTION        3199
#define IDC_LO_CLAMP_SPIN               3200
#define IDC_CLOTHING_THUMBNAIL          3200
#define IDC_HI_CLAMP                    3201
#define IDC_USEINITIMAGE                3201
#define IDC_HI_CLAMP_SPIN               3202
#define IDC_INITIMAGE                   3202
#define IDC_INITIMAGE_RELOAD            3203
#define IDC_DYNTEXT_ALPHA               3204
#define IDC_CLOTHING_DEFAULT            3205
#define IDC_MTL_GLOBAL_NAME             3207
#define IDC_CLOTHING_CUSTOM_TEXT_SPECS  3208
#define IDC_Z_ZONLY                     3391
#define IDC_PASS_ANIM_EASE_IN_NONE      3463
#define IDC_PASS_ANIM_EASE_IN_CONST_ACCEL 3464
#define IDC_PASS_ANIM_EASE_IN_SPLINE    3465
#define IDC_PASS_ANIM_EASE_IN_TIME      3466
#define IDC_PASS_ANIM_EASE_IN_TIME_SPIN 3467
#define IDC_PASS_ANIM_EASE_OUT_NONE     3468
#define IDC_PASS_ANIM_EASE_OUT_CONST_ACCEL 3469
#define IDC_PASS_ANIM_EASE_OUT_SPLINE   3470
#define IDC_PASS_ANIM_EASE_OUT_TIME     3471
#define IDC_PASS_ANIM_EASE_OUT_TIME_SPIN 3472
#define IDC_PASS_ANIM_EASE_IN_MIN       3473
#define IDC_PASS_ANIM_EASE_IN_MIN_SPIN  3474
#define IDC_PASS_ANIM_EASE_IN_MAX       3475
#define IDC_PASS_ANIM_EASE_IN_MAX_SPIN  3476
#define IDC_PASS_ANIM_EASE_OUT_MIN      3477
#define IDC_PASS_ANIM_EASE_OUT_MIN_SPIN 3478
#define IDC_PASS_ANIM_EASE_OUT_MAX      3479
#define IDC_PASS_ANIM_EASE_OUT_MAX_SPIN 3480
#define IDC_DETAIL_CURVE_CTRL           3481
#define IDC_RELOAD_ANIMS                3482
#define IDC_CLOTHING_TINT1              3483
#define IDC_CAM_LAYER_REFLECT           3484
#define IDC_CAM_LAYER_EXPLICIT_CAM      3485
#define IDC_CAM_LAYER_UV_SRC            3486
#define IDC_CAM_LAYER_CAMERA            3487
#define IDC_CAM_LAYER_ROOT_NODE         3488
#define IDC_CAM_LAYER_EXPLICIT_CAM2     3489
#define IDC_CAM_LAYER_FORCE             3490
#define IDC_CAM_LAYER_DISABLE_COLOR     3491

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        200
#define _APS_NEXT_COMMAND_VALUE         50000
#define _APS_NEXT_CONTROL_VALUE         3492
#define _APS_NEXT_SYMED_VALUE           200
#endif
#endif
